// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto.proto

package proto

import (
	pcommon "example.com/brave-revival/src/proto/pcommon"
	pmaster "example.com/brave-revival/src/proto/pmaster"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *pcommon.Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Empty) GetError() *pcommon.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type PlayerSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlayerId          uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname          string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Comment           string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	JobId             uint32                 `protobuf:"varint,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobLevel          uint32                 `protobuf:"varint,5,opt,name=job_level,json=jobLevel,proto3" json:"job_level,omitempty"`
	Power             uint32                 `protobuf:"varint,6,opt,name=power,proto3" json:"power,omitempty"`
	GuildId           uint64                 `protobuf:"varint,7,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	GuildMemberType   uint32                 `protobuf:"varint,8,opt,name=guild_member_type,json=guildMemberType,proto3" json:"guild_member_type,omitempty"`
	FavoriteEquipment uint32                 `protobuf:"varint,9,opt,name=favorite_equipment,json=favoriteEquipment,proto3" json:"favorite_equipment,omitempty"`
	LoginAt           string                 `protobuf:"bytes,10,opt,name=login_at,json=loginAt,proto3" json:"login_at,omitempty"`
	MaxJobLevel       uint32                 `protobuf:"varint,11,opt,name=max_job_level,json=maxJobLevel,proto3" json:"max_job_level,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlayerSummary) Reset() {
	*x = PlayerSummary{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSummary) ProtoMessage() {}

func (x *PlayerSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSummary.ProtoReflect.Descriptor instead.
func (*PlayerSummary) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerSummary) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerSummary) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerSummary) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *PlayerSummary) GetJobId() uint32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *PlayerSummary) GetJobLevel() uint32 {
	if x != nil {
		return x.JobLevel
	}
	return 0
}

func (x *PlayerSummary) GetPower() uint32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *PlayerSummary) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *PlayerSummary) GetGuildMemberType() uint32 {
	if x != nil {
		return x.GuildMemberType
	}
	return 0
}

func (x *PlayerSummary) GetFavoriteEquipment() uint32 {
	if x != nil {
		return x.FavoriteEquipment
	}
	return 0
}

func (x *PlayerSummary) GetLoginAt() string {
	if x != nil {
		return x.LoginAt
	}
	return ""
}

func (x *PlayerSummary) GetMaxJobLevel() uint32 {
	if x != nil {
		return x.MaxJobLevel
	}
	return 0
}

type PlayerExist struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Error            *pcommon.Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	PlayerSummary    *PlayerSummary         `protobuf:"bytes,2,opt,name=player_summary,json=playerSummary,proto3" json:"player_summary,omitempty"`
	WorldDescription string                 `protobuf:"bytes,3,opt,name=world_description,json=worldDescription,proto3" json:"world_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayerExist) Reset() {
	*x = PlayerExist{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerExist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerExist) ProtoMessage() {}

func (x *PlayerExist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerExist.ProtoReflect.Descriptor instead.
func (*PlayerExist) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerExist) GetError() *pcommon.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *PlayerExist) GetPlayerSummary() *PlayerSummary {
	if x != nil {
		return x.PlayerSummary
	}
	return nil
}

func (x *PlayerExist) GetWorldDescription() string {
	if x != nil {
		return x.WorldDescription
	}
	return ""
}

type AccountAuthorize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	BanType       uint32                 `protobuf:"varint,2,opt,name=ban_type,json=banType,proto3" json:"ban_type,omitempty"`
	BanInterval   uint64                 `protobuf:"varint,3,opt,name=ban_interval,json=banInterval,proto3" json:"ban_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountAuthorize) Reset() {
	*x = AccountAuthorize{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountAuthorize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountAuthorize) ProtoMessage() {}

func (x *AccountAuthorize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountAuthorize.ProtoReflect.Descriptor instead.
func (*AccountAuthorize) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *AccountAuthorize) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AccountAuthorize) GetBanType() uint32 {
	if x != nil {
		return x.BanType
	}
	return 0
}

func (x *AccountAuthorize) GetBanInterval() uint64 {
	if x != nil {
		return x.BanInterval
	}
	return 0
}

type AccountCertificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *pmaster.Version       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountCertificate) Reset() {
	*x = AccountCertificate{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCertificate) ProtoMessage() {}

func (x *AccountCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCertificate.ProtoReflect.Descriptor instead.
func (*AccountCertificate) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

func (x *AccountCertificate) GetVersion() *pmaster.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Photon        string                 `protobuf:"bytes,1,opt,name=photon,proto3" json:"photon,omitempty"`
	Chat          string                 `protobuf:"bytes,2,opt,name=chat,proto3" json:"chat,omitempty"`
	Party         string                 `protobuf:"bytes,3,opt,name=party,proto3" json:"party,omitempty"`
	Notify        string                 `protobuf:"bytes,4,opt,name=notify,proto3" json:"notify,omitempty"`
	Gvg           string                 `protobuf:"bytes,5,opt,name=gvg,proto3" json:"gvg,omitempty"`
	Realtime      string                 `protobuf:"bytes,6,opt,name=realtime,proto3" json:"realtime,omitempty"`
	GvgHosts      int32                  `protobuf:"varint,7,opt,name=gvg_hosts,json=gvgHosts,proto3" json:"gvg_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{5}
}

func (x *Host) GetPhoton() string {
	if x != nil {
		return x.Photon
	}
	return ""
}

func (x *Host) GetChat() string {
	if x != nil {
		return x.Chat
	}
	return ""
}

func (x *Host) GetParty() string {
	if x != nil {
		return x.Party
	}
	return ""
}

func (x *Host) GetNotify() string {
	if x != nil {
		return x.Notify
	}
	return ""
}

func (x *Host) GetGvg() string {
	if x != nil {
		return x.Gvg
	}
	return ""
}

func (x *Host) GetRealtime() string {
	if x != nil {
		return x.Realtime
	}
	return ""
}

func (x *Host) GetGvgHosts() int32 {
	if x != nil {
		return x.GvgHosts
	}
	return 0
}

type Revision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Terms         int32                  `protobuf:"varint,1,opt,name=terms,proto3" json:"terms,omitempty"`
	PrivacyPolicy int32                  `protobuf:"varint,2,opt,name=privacy_policy,json=privacyPolicy,proto3" json:"privacy_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revision) Reset() {
	*x = Revision{}
	mi := &file_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revision) ProtoMessage() {}

func (x *Revision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revision.ProtoReflect.Descriptor instead.
func (*Revision) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{6}
}

func (x *Revision) GetTerms() int32 {
	if x != nil {
		return x.Terms
	}
	return 0
}

func (x *Revision) GetPrivacyPolicy() int32 {
	if x != nil {
		return x.PrivacyPolicy
	}
	return 0
}

type Etc struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Host           *Host                  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Language       string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Environment    string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Gmt            float32                `protobuf:"fixed32,4,opt,name=gmt,proto3" json:"gmt,omitempty"`
	StoreReviewUrl string                 `protobuf:"bytes,5,opt,name=store_review_url,json=storeReviewUrl,proto3" json:"store_review_url,omitempty"`
	Revision       *Revision              `protobuf:"bytes,6,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Etc) Reset() {
	*x = Etc{}
	mi := &file_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Etc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Etc) ProtoMessage() {}

func (x *Etc) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Etc.ProtoReflect.Descriptor instead.
func (*Etc) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{7}
}

func (x *Etc) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Etc) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Etc) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Etc) GetGmt() float32 {
	if x != nil {
		return x.Gmt
	}
	return 0
}

func (x *Etc) GetStoreReviewUrl() string {
	if x != nil {
		return x.StoreReviewUrl
	}
	return ""
}

func (x *Etc) GetRevision() *Revision {
	if x != nil {
		return x.Revision
	}
	return nil
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\x12\x05Proto\x1a\rpcommon.proto\x1a\rpmaster.proto\"-\n" +
	"\x05Empty\x12$\n" +
	"\x05error\x18\x01 \x01(\v2\x0e.Pcommon.ErrorR\x05error\"\xe1\x02\n" +
	"\rPlayerSummary\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\rR\x05jobId\x12\x1b\n" +
	"\tjob_level\x18\x05 \x01(\rR\bjobLevel\x12\x14\n" +
	"\x05power\x18\x06 \x01(\rR\x05power\x12\x19\n" +
	"\bguild_id\x18\a \x01(\x04R\aguildId\x12*\n" +
	"\x11guild_member_type\x18\b \x01(\rR\x0fguildMemberType\x12-\n" +
	"\x12favorite_equipment\x18\t \x01(\rR\x11favoriteEquipment\x12\x19\n" +
	"\blogin_at\x18\n" +
	" \x01(\tR\aloginAt\x12\"\n" +
	"\rmax_job_level\x18\v \x01(\rR\vmaxJobLevel\"\x9d\x01\n" +
	"\vPlayerExist\x12$\n" +
	"\x05error\x18\x01 \x01(\v2\x0e.Pcommon.ErrorR\x05error\x12;\n" +
	"\x0eplayer_summary\x18\x02 \x01(\v2\x14.Proto.PlayerSummaryR\rplayerSummary\x12+\n" +
	"\x11world_description\x18\x03 \x01(\tR\x10worldDescription\"f\n" +
	"\x10AccountAuthorize\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bban_type\x18\x02 \x01(\rR\abanType\x12!\n" +
	"\fban_interval\x18\x03 \x01(\x04R\vbanInterval\"@\n" +
	"\x12AccountCertificate\x12*\n" +
	"\aversion\x18\x01 \x01(\v2\x10.Pmaster.VersionR\aversion\"\xab\x01\n" +
	"\x04Host\x12\x16\n" +
	"\x06photon\x18\x01 \x01(\tR\x06photon\x12\x12\n" +
	"\x04chat\x18\x02 \x01(\tR\x04chat\x12\x14\n" +
	"\x05party\x18\x03 \x01(\tR\x05party\x12\x16\n" +
	"\x06notify\x18\x04 \x01(\tR\x06notify\x12\x10\n" +
	"\x03gvg\x18\x05 \x01(\tR\x03gvg\x12\x1a\n" +
	"\brealtime\x18\x06 \x01(\tR\brealtime\x12\x1b\n" +
	"\tgvg_hosts\x18\a \x01(\x05R\bgvgHosts\"G\n" +
	"\bRevision\x12\x14\n" +
	"\x05terms\x18\x01 \x01(\x05R\x05terms\x12%\n" +
	"\x0eprivacy_policy\x18\x02 \x01(\x05R\rprivacyPolicy\"\xcd\x01\n" +
	"\x03Etc\x12\x1f\n" +
	"\x04host\x18\x01 \x01(\v2\v.Proto.HostR\x04host\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x10\n" +
	"\x03gmt\x18\x04 \x01(\x02R\x03gmt\x12(\n" +
	"\x10store_review_url\x18\x05 \x01(\tR\x0estoreReviewUrl\x12+\n" +
	"\brevision\x18\x06 \x01(\v2\x0f.Proto.RevisionR\brevisionB+Z)example.com/brave-revival/src/proto/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_proto_goTypes = []any{
	(*Empty)(nil),              // 0: Proto.Empty
	(*PlayerSummary)(nil),      // 1: Proto.PlayerSummary
	(*PlayerExist)(nil),        // 2: Proto.PlayerExist
	(*AccountAuthorize)(nil),   // 3: Proto.AccountAuthorize
	(*AccountCertificate)(nil), // 4: Proto.AccountCertificate
	(*Host)(nil),               // 5: Proto.Host
	(*Revision)(nil),           // 6: Proto.Revision
	(*Etc)(nil),                // 7: Proto.Etc
	(*pcommon.Error)(nil),      // 8: Pcommon.Error
	(*pmaster.Version)(nil),    // 9: Pmaster.Version
}
var file_proto_proto_depIdxs = []int32{
	8, // 0: Proto.Empty.error:type_name -> Pcommon.Error
	8, // 1: Proto.PlayerExist.error:type_name -> Pcommon.Error
	1, // 2: Proto.PlayerExist.player_summary:type_name -> Proto.PlayerSummary
	9, // 3: Proto.AccountCertificate.version:type_name -> Pmaster.Version
	5, // 4: Proto.Etc.host:type_name -> Proto.Host
	6, // 5: Proto.Etc.revision:type_name -> Proto.Revision
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
