// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto.proto

package proto

import (
	pcommon "example.com/brave-revival/src/proto/pcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlayerId          uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname          string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Comment           string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	JobId             uint32                 `protobuf:"varint,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobLevel          uint32                 `protobuf:"varint,5,opt,name=job_level,json=jobLevel,proto3" json:"job_level,omitempty"`
	Power             uint32                 `protobuf:"varint,6,opt,name=power,proto3" json:"power,omitempty"`
	GuildId           uint64                 `protobuf:"varint,7,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	GuildMemberType   uint32                 `protobuf:"varint,8,opt,name=guild_member_type,json=guildMemberType,proto3" json:"guild_member_type,omitempty"`
	FavoriteEquipment uint32                 `protobuf:"varint,9,opt,name=favorite_equipment,json=favoriteEquipment,proto3" json:"favorite_equipment,omitempty"`
	LoginAt           string                 `protobuf:"bytes,10,opt,name=login_at,json=loginAt,proto3" json:"login_at,omitempty"`
	MaxJobLevel       uint32                 `protobuf:"varint,11,opt,name=max_job_level,json=maxJobLevel,proto3" json:"max_job_level,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlayerSummary) Reset() {
	*x = PlayerSummary{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSummary) ProtoMessage() {}

func (x *PlayerSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSummary.ProtoReflect.Descriptor instead.
func (*PlayerSummary) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerSummary) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerSummary) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerSummary) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *PlayerSummary) GetJobId() uint32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *PlayerSummary) GetJobLevel() uint32 {
	if x != nil {
		return x.JobLevel
	}
	return 0
}

func (x *PlayerSummary) GetPower() uint32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *PlayerSummary) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *PlayerSummary) GetGuildMemberType() uint32 {
	if x != nil {
		return x.GuildMemberType
	}
	return 0
}

func (x *PlayerSummary) GetFavoriteEquipment() uint32 {
	if x != nil {
		return x.FavoriteEquipment
	}
	return 0
}

func (x *PlayerSummary) GetLoginAt() string {
	if x != nil {
		return x.LoginAt
	}
	return ""
}

func (x *PlayerSummary) GetMaxJobLevel() uint32 {
	if x != nil {
		return x.MaxJobLevel
	}
	return 0
}

type PlayerExist struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Error            *pcommon.Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	PlayerSummary    *PlayerSummary         `protobuf:"bytes,2,opt,name=player_summary,json=playerSummary,proto3" json:"player_summary,omitempty"`
	WorldDescription string                 `protobuf:"bytes,3,opt,name=world_description,json=worldDescription,proto3" json:"world_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayerExist) Reset() {
	*x = PlayerExist{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerExist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerExist) ProtoMessage() {}

func (x *PlayerExist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerExist.ProtoReflect.Descriptor instead.
func (*PlayerExist) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerExist) GetError() *pcommon.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *PlayerExist) GetPlayerSummary() *PlayerSummary {
	if x != nil {
		return x.PlayerSummary
	}
	return nil
}

func (x *PlayerExist) GetWorldDescription() string {
	if x != nil {
		return x.WorldDescription
	}
	return ""
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\x12\x05Proto\x1a\rpcommon.proto\"\xe1\x02\n" +
	"\rPlayerSummary\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\rR\x05jobId\x12\x1b\n" +
	"\tjob_level\x18\x05 \x01(\rR\bjobLevel\x12\x14\n" +
	"\x05power\x18\x06 \x01(\rR\x05power\x12\x19\n" +
	"\bguild_id\x18\a \x01(\x04R\aguildId\x12*\n" +
	"\x11guild_member_type\x18\b \x01(\rR\x0fguildMemberType\x12-\n" +
	"\x12favorite_equipment\x18\t \x01(\rR\x11favoriteEquipment\x12\x19\n" +
	"\blogin_at\x18\n" +
	" \x01(\tR\aloginAt\x12\"\n" +
	"\rmax_job_level\x18\v \x01(\rR\vmaxJobLevel\"\x9d\x01\n" +
	"\vPlayerExist\x12$\n" +
	"\x05error\x18\x01 \x01(\v2\x0e.Pcommon.ErrorR\x05error\x12;\n" +
	"\x0eplayer_summary\x18\x02 \x01(\v2\x14.Proto.PlayerSummaryR\rplayerSummary\x12+\n" +
	"\x11world_description\x18\x03 \x01(\tR\x10worldDescriptionB+Z)example.com/brave-revival/src/proto/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_proto_goTypes = []any{
	(*PlayerSummary)(nil), // 0: Proto.PlayerSummary
	(*PlayerExist)(nil),   // 1: Proto.PlayerExist
	(*pcommon.Error)(nil), // 2: Pcommon.Error
}
var file_proto_proto_depIdxs = []int32{
	2, // 0: Proto.PlayerExist.error:type_name -> Pcommon.Error
	0, // 1: Proto.PlayerExist.player_summary:type_name -> Proto.PlayerSummary
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
