// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: prealtime.proto

package prealtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []string               `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_prealtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_prealtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_prealtime_proto_rawDescGZIP(), []int{0}
}

func (x *Channel) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

type StatNumSub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nums          map[string]int32       `protobuf:"bytes,1,rep,name=nums,proto3" json:"nums,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatNumSub) Reset() {
	*x = StatNumSub{}
	mi := &file_prealtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatNumSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatNumSub) ProtoMessage() {}

func (x *StatNumSub) ProtoReflect() protoreflect.Message {
	mi := &file_prealtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatNumSub.ProtoReflect.Descriptor instead.
func (*StatNumSub) Descriptor() ([]byte, []int) {
	return file_prealtime_proto_rawDescGZIP(), []int{1}
}

func (x *StatNumSub) GetNums() map[string]int32 {
	if x != nil {
		return x.Nums
	}
	return nil
}

var File_prealtime_proto protoreflect.FileDescriptor

const file_prealtime_proto_rawDesc = "" +
	"\n" +
	"\x0fprealtime.proto\x12\tPrealtime\"%\n" +
	"\aChannel\x12\x1a\n" +
	"\bchannels\x18\x01 \x03(\tR\bchannels\"z\n" +
	"\n" +
	"StatNumSub\x123\n" +
	"\x04nums\x18\x01 \x03(\v2\x1f.Prealtime.StatNumSub.NumsEntryR\x04nums\x1a7\n" +
	"\tNumsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B/Z-example.com/brave-revival/src/proto/prealtimeb\x06proto3"

var (
	file_prealtime_proto_rawDescOnce sync.Once
	file_prealtime_proto_rawDescData []byte
)

func file_prealtime_proto_rawDescGZIP() []byte {
	file_prealtime_proto_rawDescOnce.Do(func() {
		file_prealtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prealtime_proto_rawDesc), len(file_prealtime_proto_rawDesc)))
	})
	return file_prealtime_proto_rawDescData
}

var file_prealtime_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_prealtime_proto_goTypes = []any{
	(*Channel)(nil),    // 0: Prealtime.Channel
	(*StatNumSub)(nil), // 1: Prealtime.StatNumSub
	nil,                // 2: Prealtime.StatNumSub.NumsEntry
}
var file_prealtime_proto_depIdxs = []int32{
	2, // 0: Prealtime.StatNumSub.nums:type_name -> Prealtime.StatNumSub.NumsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_prealtime_proto_init() }
func file_prealtime_proto_init() {
	if File_prealtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prealtime_proto_rawDesc), len(file_prealtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prealtime_proto_goTypes,
		DependencyIndexes: file_prealtime_proto_depIdxs,
		MessageInfos:      file_prealtime_proto_msgTypes,
	}.Build()
	File_prealtime_proto = out.File
	file_prealtime_proto_goTypes = nil
	file_prealtime_proto_depIdxs = nil
}
