// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: crownotify.proto

package crownotify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrowNotify_Notify_FullMethodName           = "/CrowNotify.CrowNotify/Notify"
	CrowNotify_CloseNotify_FullMethodName      = "/CrowNotify.CrowNotify/CloseNotify"
	CrowNotify_GetAnnounce_FullMethodName      = "/CrowNotify.CrowNotify/GetAnnounce"
	CrowNotify_GetMaintenance_FullMethodName   = "/CrowNotify.CrowNotify/GetMaintenance"
	CrowNotify_GetNotifierCount_FullMethodName = "/CrowNotify.CrowNotify/GetNotifierCount"
	CrowNotify_GetNotifierList_FullMethodName  = "/CrowNotify.CrowNotify/GetNotifierList"
	CrowNotify_SetAnnounce_FullMethodName      = "/CrowNotify.CrowNotify/SetAnnounce"
	CrowNotify_SetMaintenance_FullMethodName   = "/CrowNotify.CrowNotify/SetMaintenance"
	CrowNotify_SendNotify_FullMethodName       = "/CrowNotify.CrowNotify/SendNotify"
	CrowNotify_SendTicker_FullMethodName       = "/CrowNotify.CrowNotify/SendTicker"
)

// CrowNotifyClient is the client API for CrowNotify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrowNotifyClient interface {
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyEvent], error)
	CloseNotify(ctx context.Context, in *CloseNotifyRequest, opts ...grpc.CallOption) (*CloseNotifyResult, error)
	GetAnnounce(ctx context.Context, in *NullRequest, opts ...grpc.CallOption) (*Announce, error)
	GetMaintenance(ctx context.Context, in *NullRequest, opts ...grpc.CallOption) (*Maintenance, error)
	GetNotifierCount(ctx context.Context, in *GetNotifierCountRequest, opts ...grpc.CallOption) (*GetNotifierCountResult, error)
	GetNotifierList(ctx context.Context, in *GetNotifierListRequest, opts ...grpc.CallOption) (*GetNotifierListResult, error)
	SetAnnounce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*NullResponse, error)
	SetMaintenance(ctx context.Context, in *MaintenanceRequest, opts ...grpc.CallOption) (*NullResponse, error)
	SendNotify(ctx context.Context, in *SendNotifyRequest, opts ...grpc.CallOption) (*NullResponse, error)
	SendTicker(ctx context.Context, in *SendTickerRequest, opts ...grpc.CallOption) (*NullResponse, error)
}

type crowNotifyClient struct {
	cc grpc.ClientConnInterface
}

func NewCrowNotifyClient(cc grpc.ClientConnInterface) CrowNotifyClient {
	return &crowNotifyClient{cc}
}

func (c *crowNotifyClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CrowNotify_ServiceDesc.Streams[0], CrowNotify_Notify_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NotifyRequest, NotifyEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CrowNotify_NotifyClient = grpc.ServerStreamingClient[NotifyEvent]

func (c *crowNotifyClient) CloseNotify(ctx context.Context, in *CloseNotifyRequest, opts ...grpc.CallOption) (*CloseNotifyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseNotifyResult)
	err := c.cc.Invoke(ctx, CrowNotify_CloseNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crowNotifyClient) GetAnnounce(ctx context.Context, in *NullRequest, opts ...grpc.CallOption) (*Announce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Announce)
	err := c.cc.Invoke(ctx, CrowNotify_GetAnnounce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crowNotifyClient) GetMaintenance(ctx context.Context, in *NullRequest, opts ...grpc.CallOption) (*Maintenance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Maintenance)
	err := c.cc.Invoke(ctx, CrowNotify_GetMaintenance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crowNotifyClient) GetNotifierCount(ctx context.Context, in *GetNotifierCountRequest, opts ...grpc.CallOption) (*GetNotifierCountResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNotifierCountResult)
	err := c.cc.Invoke(ctx, CrowNotify_GetNotifierCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crowNotifyClient) GetNotifierList(ctx context.Context, in *GetNotifierListRequest, opts ...grpc.CallOption) (*GetNotifierListResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNotifierListResult)
	err := c.cc.Invoke(ctx, CrowNotify_GetNotifierList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crowNotifyClient) SetAnnounce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*NullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NullResponse)
	err := c.cc.Invoke(ctx, CrowNotify_SetAnnounce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crowNotifyClient) SetMaintenance(ctx context.Context, in *MaintenanceRequest, opts ...grpc.CallOption) (*NullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NullResponse)
	err := c.cc.Invoke(ctx, CrowNotify_SetMaintenance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crowNotifyClient) SendNotify(ctx context.Context, in *SendNotifyRequest, opts ...grpc.CallOption) (*NullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NullResponse)
	err := c.cc.Invoke(ctx, CrowNotify_SendNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crowNotifyClient) SendTicker(ctx context.Context, in *SendTickerRequest, opts ...grpc.CallOption) (*NullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NullResponse)
	err := c.cc.Invoke(ctx, CrowNotify_SendTicker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrowNotifyServer is the server API for CrowNotify service.
// All implementations must embed UnimplementedCrowNotifyServer
// for forward compatibility.
type CrowNotifyServer interface {
	Notify(*NotifyRequest, grpc.ServerStreamingServer[NotifyEvent]) error
	CloseNotify(context.Context, *CloseNotifyRequest) (*CloseNotifyResult, error)
	GetAnnounce(context.Context, *NullRequest) (*Announce, error)
	GetMaintenance(context.Context, *NullRequest) (*Maintenance, error)
	GetNotifierCount(context.Context, *GetNotifierCountRequest) (*GetNotifierCountResult, error)
	GetNotifierList(context.Context, *GetNotifierListRequest) (*GetNotifierListResult, error)
	SetAnnounce(context.Context, *AnnounceRequest) (*NullResponse, error)
	SetMaintenance(context.Context, *MaintenanceRequest) (*NullResponse, error)
	SendNotify(context.Context, *SendNotifyRequest) (*NullResponse, error)
	SendTicker(context.Context, *SendTickerRequest) (*NullResponse, error)
	mustEmbedUnimplementedCrowNotifyServer()
}

// UnimplementedCrowNotifyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrowNotifyServer struct{}

func (UnimplementedCrowNotifyServer) Notify(*NotifyRequest, grpc.ServerStreamingServer[NotifyEvent]) error {
	return status.Error(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedCrowNotifyServer) CloseNotify(context.Context, *CloseNotifyRequest) (*CloseNotifyResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseNotify not implemented")
}
func (UnimplementedCrowNotifyServer) GetAnnounce(context.Context, *NullRequest) (*Announce, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnnounce not implemented")
}
func (UnimplementedCrowNotifyServer) GetMaintenance(context.Context, *NullRequest) (*Maintenance, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMaintenance not implemented")
}
func (UnimplementedCrowNotifyServer) GetNotifierCount(context.Context, *GetNotifierCountRequest) (*GetNotifierCountResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotifierCount not implemented")
}
func (UnimplementedCrowNotifyServer) GetNotifierList(context.Context, *GetNotifierListRequest) (*GetNotifierListResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotifierList not implemented")
}
func (UnimplementedCrowNotifyServer) SetAnnounce(context.Context, *AnnounceRequest) (*NullResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAnnounce not implemented")
}
func (UnimplementedCrowNotifyServer) SetMaintenance(context.Context, *MaintenanceRequest) (*NullResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMaintenance not implemented")
}
func (UnimplementedCrowNotifyServer) SendNotify(context.Context, *SendNotifyRequest) (*NullResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendNotify not implemented")
}
func (UnimplementedCrowNotifyServer) SendTicker(context.Context, *SendTickerRequest) (*NullResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendTicker not implemented")
}
func (UnimplementedCrowNotifyServer) mustEmbedUnimplementedCrowNotifyServer() {}
func (UnimplementedCrowNotifyServer) testEmbeddedByValue()                    {}

// UnsafeCrowNotifyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrowNotifyServer will
// result in compilation errors.
type UnsafeCrowNotifyServer interface {
	mustEmbedUnimplementedCrowNotifyServer()
}

func RegisterCrowNotifyServer(s grpc.ServiceRegistrar, srv CrowNotifyServer) {
	// If the following call panics, it indicates UnimplementedCrowNotifyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrowNotify_ServiceDesc, srv)
}

func _CrowNotify_Notify_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NotifyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CrowNotifyServer).Notify(m, &grpc.GenericServerStream[NotifyRequest, NotifyEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CrowNotify_NotifyServer = grpc.ServerStreamingServer[NotifyEvent]

func _CrowNotify_CloseNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrowNotifyServer).CloseNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrowNotify_CloseNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrowNotifyServer).CloseNotify(ctx, req.(*CloseNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrowNotify_GetAnnounce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrowNotifyServer).GetAnnounce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrowNotify_GetAnnounce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrowNotifyServer).GetAnnounce(ctx, req.(*NullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrowNotify_GetMaintenance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrowNotifyServer).GetMaintenance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrowNotify_GetMaintenance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrowNotifyServer).GetMaintenance(ctx, req.(*NullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrowNotify_GetNotifierCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotifierCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrowNotifyServer).GetNotifierCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrowNotify_GetNotifierCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrowNotifyServer).GetNotifierCount(ctx, req.(*GetNotifierCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrowNotify_GetNotifierList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotifierListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrowNotifyServer).GetNotifierList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrowNotify_GetNotifierList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrowNotifyServer).GetNotifierList(ctx, req.(*GetNotifierListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrowNotify_SetAnnounce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrowNotifyServer).SetAnnounce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrowNotify_SetAnnounce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrowNotifyServer).SetAnnounce(ctx, req.(*AnnounceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrowNotify_SetMaintenance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaintenanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrowNotifyServer).SetMaintenance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrowNotify_SetMaintenance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrowNotifyServer).SetMaintenance(ctx, req.(*MaintenanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrowNotify_SendNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrowNotifyServer).SendNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrowNotify_SendNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrowNotifyServer).SendNotify(ctx, req.(*SendNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrowNotify_SendTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrowNotifyServer).SendTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrowNotify_SendTicker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrowNotifyServer).SendTicker(ctx, req.(*SendTickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrowNotify_ServiceDesc is the grpc.ServiceDesc for CrowNotify service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrowNotify_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CrowNotify.CrowNotify",
	HandlerType: (*CrowNotifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CloseNotify",
			Handler:    _CrowNotify_CloseNotify_Handler,
		},
		{
			MethodName: "GetAnnounce",
			Handler:    _CrowNotify_GetAnnounce_Handler,
		},
		{
			MethodName: "GetMaintenance",
			Handler:    _CrowNotify_GetMaintenance_Handler,
		},
		{
			MethodName: "GetNotifierCount",
			Handler:    _CrowNotify_GetNotifierCount_Handler,
		},
		{
			MethodName: "GetNotifierList",
			Handler:    _CrowNotify_GetNotifierList_Handler,
		},
		{
			MethodName: "SetAnnounce",
			Handler:    _CrowNotify_SetAnnounce_Handler,
		},
		{
			MethodName: "SetMaintenance",
			Handler:    _CrowNotify_SetMaintenance_Handler,
		},
		{
			MethodName: "SendNotify",
			Handler:    _CrowNotify_SendNotify_Handler,
		},
		{
			MethodName: "SendTicker",
			Handler:    _CrowNotify_SendTicker_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Notify",
			Handler:       _CrowNotify_Notify_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "crownotify.proto",
}
