// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: crownotify.proto

package crownotify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Store int32

const (
	Store_STORE_UNKNOWN     Store = 0
	Store_STORE_ITUNES      Store = 1
	Store_STORE_GOOGLE_PLAY Store = 2
)

// Enum value maps for Store.
var (
	Store_name = map[int32]string{
		0: "STORE_UNKNOWN",
		1: "STORE_ITUNES",
		2: "STORE_GOOGLE_PLAY",
	}
	Store_value = map[string]int32{
		"STORE_UNKNOWN":     0,
		"STORE_ITUNES":      1,
		"STORE_GOOGLE_PLAY": 2,
	}
)

func (x Store) Enum() *Store {
	p := new(Store)
	*p = x
	return p
}

func (x Store) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Store) Descriptor() protoreflect.EnumDescriptor {
	return file_crownotify_proto_enumTypes[0].Descriptor()
}

func (Store) Type() protoreflect.EnumType {
	return &file_crownotify_proto_enumTypes[0]
}

func (x Store) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Store.Descriptor instead.
func (Store) EnumDescriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{0}
}

type AnnounceType int32

const (
	AnnounceType_ANNOUNCE_TYPE_UNKNOWN    AnnounceType = 0
	AnnounceType_ANNOUNCE_TYPE_ANNOUNCE_1 AnnounceType = 1
	AnnounceType_ANNOUNCE_TYPE_ANNOUNCE_2 AnnounceType = 2
	AnnounceType_ANNOUNCE_TYPE_ANNOUNCE_3 AnnounceType = 3
)

// Enum value maps for AnnounceType.
var (
	AnnounceType_name = map[int32]string{
		0: "ANNOUNCE_TYPE_UNKNOWN",
		1: "ANNOUNCE_TYPE_ANNOUNCE_1",
		2: "ANNOUNCE_TYPE_ANNOUNCE_2",
		3: "ANNOUNCE_TYPE_ANNOUNCE_3",
	}
	AnnounceType_value = map[string]int32{
		"ANNOUNCE_TYPE_UNKNOWN":    0,
		"ANNOUNCE_TYPE_ANNOUNCE_1": 1,
		"ANNOUNCE_TYPE_ANNOUNCE_2": 2,
		"ANNOUNCE_TYPE_ANNOUNCE_3": 3,
	}
)

func (x AnnounceType) Enum() *AnnounceType {
	p := new(AnnounceType)
	*p = x
	return p
}

func (x AnnounceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnounceType) Descriptor() protoreflect.EnumDescriptor {
	return file_crownotify_proto_enumTypes[1].Descriptor()
}

func (AnnounceType) Type() protoreflect.EnumType {
	return &file_crownotify_proto_enumTypes[1]
}

func (x AnnounceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnounceType.Descriptor instead.
func (AnnounceType) EnumDescriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{1}
}

type BattleStatus int32

const (
	BattleStatus_BATTLE_STATUS_BEFORE_BATTLE   BattleStatus = 0
	BattleStatus_BATTLE_STATUS_ENTERING_BATTLE BattleStatus = 1
	BattleStatus_BATTLE_STATUS_IN_BATTLE       BattleStatus = 2
)

// Enum value maps for BattleStatus.
var (
	BattleStatus_name = map[int32]string{
		0: "BATTLE_STATUS_BEFORE_BATTLE",
		1: "BATTLE_STATUS_ENTERING_BATTLE",
		2: "BATTLE_STATUS_IN_BATTLE",
	}
	BattleStatus_value = map[string]int32{
		"BATTLE_STATUS_BEFORE_BATTLE":   0,
		"BATTLE_STATUS_ENTERING_BATTLE": 1,
		"BATTLE_STATUS_IN_BATTLE":       2,
	}
)

func (x BattleStatus) Enum() *BattleStatus {
	p := new(BattleStatus)
	*p = x
	return p
}

func (x BattleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_crownotify_proto_enumTypes[2].Descriptor()
}

func (BattleStatus) Type() protoreflect.EnumType {
	return &file_crownotify_proto_enumTypes[2]
}

func (x BattleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleStatus.Descriptor instead.
func (BattleStatus) EnumDescriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{2}
}

type PlayerActivity int32

const (
	PlayerActivity_PLAYER_ACTIVITY_ACTIVITY_UNKNOWN   PlayerActivity = 0
	PlayerActivity_PLAYER_ACTIVITY_ACTIVITY_OK        PlayerActivity = 1
	PlayerActivity_PLAYER_ACTIVITY_ACTIVITY_PREPARING PlayerActivity = 2
)

// Enum value maps for PlayerActivity.
var (
	PlayerActivity_name = map[int32]string{
		0: "PLAYER_ACTIVITY_ACTIVITY_UNKNOWN",
		1: "PLAYER_ACTIVITY_ACTIVITY_OK",
		2: "PLAYER_ACTIVITY_ACTIVITY_PREPARING",
	}
	PlayerActivity_value = map[string]int32{
		"PLAYER_ACTIVITY_ACTIVITY_UNKNOWN":   0,
		"PLAYER_ACTIVITY_ACTIVITY_OK":        1,
		"PLAYER_ACTIVITY_ACTIVITY_PREPARING": 2,
	}
)

func (x PlayerActivity) Enum() *PlayerActivity {
	p := new(PlayerActivity)
	*p = x
	return p
}

func (x PlayerActivity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerActivity) Descriptor() protoreflect.EnumDescriptor {
	return file_crownotify_proto_enumTypes[3].Descriptor()
}

func (PlayerActivity) Type() protoreflect.EnumType {
	return &file_crownotify_proto_enumTypes[3]
}

func (x PlayerActivity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerActivity.Descriptor instead.
func (PlayerActivity) EnumDescriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{3}
}

type NotifyRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Store             Store                  `protobuf:"varint,2,opt,name=store,proto3,enum=CrowNotify.Store" json:"store,omitempty"`
	RegistrationToken string                 `protobuf:"bytes,3,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_crownotify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotifyRequest) GetStore() Store {
	if x != nil {
		return x.Store
	}
	return Store_STORE_UNKNOWN
}

func (x *NotifyRequest) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

type NotifyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*NotifyEvent_Invited
	//	*NotifyEvent_Generic
	//	*NotifyEvent_InviteGroup
	//	*NotifyEvent_AddedGroup
	//	*NotifyEvent_Ticker
	//	*NotifyEvent_Announce
	//	*NotifyEvent_Maintenance
	Event         isNotifyEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyEvent) Reset() {
	*x = NotifyEvent{}
	mi := &file_crownotify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyEvent) ProtoMessage() {}

func (x *NotifyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyEvent.ProtoReflect.Descriptor instead.
func (*NotifyEvent) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyEvent) GetEvent() isNotifyEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *NotifyEvent) GetInvited() *JoinRequest {
	if x != nil {
		if x, ok := x.Event.(*NotifyEvent_Invited); ok {
			return x.Invited
		}
	}
	return nil
}

func (x *NotifyEvent) GetGeneric() string {
	if x != nil {
		if x, ok := x.Event.(*NotifyEvent_Generic); ok {
			return x.Generic
		}
	}
	return ""
}

func (x *NotifyEvent) GetInviteGroup() *InviteGroup {
	if x != nil {
		if x, ok := x.Event.(*NotifyEvent_InviteGroup); ok {
			return x.InviteGroup
		}
	}
	return nil
}

func (x *NotifyEvent) GetAddedGroup() *AddedGroup {
	if x != nil {
		if x, ok := x.Event.(*NotifyEvent_AddedGroup); ok {
			return x.AddedGroup
		}
	}
	return nil
}

func (x *NotifyEvent) GetTicker() string {
	if x != nil {
		if x, ok := x.Event.(*NotifyEvent_Ticker); ok {
			return x.Ticker
		}
	}
	return ""
}

func (x *NotifyEvent) GetAnnounce() *Announce {
	if x != nil {
		if x, ok := x.Event.(*NotifyEvent_Announce); ok {
			return x.Announce
		}
	}
	return nil
}

func (x *NotifyEvent) GetMaintenance() string {
	if x != nil {
		if x, ok := x.Event.(*NotifyEvent_Maintenance); ok {
			return x.Maintenance
		}
	}
	return ""
}

type isNotifyEvent_Event interface {
	isNotifyEvent_Event()
}

type NotifyEvent_Invited struct {
	Invited *JoinRequest `protobuf:"bytes,1,opt,name=invited,proto3,oneof"`
}

type NotifyEvent_Generic struct {
	Generic string `protobuf:"bytes,2,opt,name=generic,proto3,oneof"`
}

type NotifyEvent_InviteGroup struct {
	InviteGroup *InviteGroup `protobuf:"bytes,3,opt,name=invite_group,json=inviteGroup,proto3,oneof"`
}

type NotifyEvent_AddedGroup struct {
	AddedGroup *AddedGroup `protobuf:"bytes,4,opt,name=added_group,json=addedGroup,proto3,oneof"`
}

type NotifyEvent_Ticker struct {
	Ticker string `protobuf:"bytes,5,opt,name=ticker,proto3,oneof"`
}

type NotifyEvent_Announce struct {
	Announce *Announce `protobuf:"bytes,6,opt,name=announce,proto3,oneof"`
}

type NotifyEvent_Maintenance struct {
	Maintenance string `protobuf:"bytes,7,opt,name=maintenance,proto3,oneof"`
}

func (*NotifyEvent_Invited) isNotifyEvent_Event() {}

func (*NotifyEvent_Generic) isNotifyEvent_Event() {}

func (*NotifyEvent_InviteGroup) isNotifyEvent_Event() {}

func (*NotifyEvent_AddedGroup) isNotifyEvent_Event() {}

func (*NotifyEvent_Ticker) isNotifyEvent_Event() {}

func (*NotifyEvent_Announce) isNotifyEvent_Event() {}

func (*NotifyEvent_Maintenance) isNotifyEvent_Event() {}

type CloseNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseNotifyRequest) Reset() {
	*x = CloseNotifyRequest{}
	mi := &file_crownotify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseNotifyRequest) ProtoMessage() {}

func (x *CloseNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseNotifyRequest.ProtoReflect.Descriptor instead.
func (*CloseNotifyRequest) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{2}
}

func (x *CloseNotifyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CloseNotifyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseNotifyResult) Reset() {
	*x = CloseNotifyResult{}
	mi := &file_crownotify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseNotifyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseNotifyResult) ProtoMessage() {}

func (x *CloseNotifyResult) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseNotifyResult.ProtoReflect.Descriptor instead.
func (*CloseNotifyResult) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{3}
}

type NullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullRequest) Reset() {
	*x = NullRequest{}
	mi := &file_crownotify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullRequest) ProtoMessage() {}

func (x *NullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullRequest.ProtoReflect.Descriptor instead.
func (*NullRequest) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{4}
}

type NullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullResponse) Reset() {
	*x = NullResponse{}
	mi := &file_crownotify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullResponse) ProtoMessage() {}

func (x *NullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullResponse.ProtoReflect.Descriptor instead.
func (*NullResponse) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{5}
}

type AnnounceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	AnnounceType  AnnounceType           `protobuf:"varint,5,opt,name=announce_type,json=announceType,proto3,enum=CrowNotify.AnnounceType" json:"announce_type,omitempty"`
	StartAt       int64                  `protobuf:"varint,6,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         int64                  `protobuf:"varint,7,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceRequest) Reset() {
	*x = AnnounceRequest{}
	mi := &file_crownotify_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceRequest) ProtoMessage() {}

func (x *AnnounceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceRequest.ProtoReflect.Descriptor instead.
func (*AnnounceRequest) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{6}
}

func (x *AnnounceRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AnnounceRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnnounceRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AnnounceRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AnnounceRequest) GetAnnounceType() AnnounceType {
	if x != nil {
		return x.AnnounceType
	}
	return AnnounceType_ANNOUNCE_TYPE_UNKNOWN
}

func (x *AnnounceRequest) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *AnnounceRequest) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

type Announce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	AnnounceType  AnnounceType           `protobuf:"varint,4,opt,name=announce_type,json=announceType,proto3,enum=CrowNotify.AnnounceType" json:"announce_type,omitempty"`
	StartAt       int64                  `protobuf:"varint,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         int64                  `protobuf:"varint,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Announce) Reset() {
	*x = Announce{}
	mi := &file_crownotify_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Announce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announce) ProtoMessage() {}

func (x *Announce) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announce.ProtoReflect.Descriptor instead.
func (*Announce) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{7}
}

func (x *Announce) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Announce) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Announce) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Announce) GetAnnounceType() AnnounceType {
	if x != nil {
		return x.AnnounceType
	}
	return AnnounceType_ANNOUNCE_TYPE_UNKNOWN
}

func (x *Announce) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *Announce) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

type MaintenanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	StartAt       int64                  `protobuf:"varint,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         int64                  `protobuf:"varint,3,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceRequest) Reset() {
	*x = MaintenanceRequest{}
	mi := &file_crownotify_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceRequest) ProtoMessage() {}

func (x *MaintenanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceRequest.ProtoReflect.Descriptor instead.
func (*MaintenanceRequest) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{8}
}

func (x *MaintenanceRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MaintenanceRequest) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *MaintenanceRequest) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

type Maintenance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartAt       int64                  `protobuf:"varint,1,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         int64                  `protobuf:"varint,2,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Maintenance) Reset() {
	*x = Maintenance{}
	mi := &file_crownotify_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Maintenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maintenance) ProtoMessage() {}

func (x *Maintenance) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maintenance.ProtoReflect.Descriptor instead.
func (*Maintenance) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{9}
}

func (x *Maintenance) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *Maintenance) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

type GetNotifierCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotifierCountRequest) Reset() {
	*x = GetNotifierCountRequest{}
	mi := &file_crownotify_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotifierCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotifierCountRequest) ProtoMessage() {}

func (x *GetNotifierCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotifierCountRequest.ProtoReflect.Descriptor instead.
func (*GetNotifierCountRequest) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{10}
}

func (x *GetNotifierCountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetNotifierCountResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifierCount uint64                 `protobuf:"varint,1,opt,name=notifier_count,json=notifierCount,proto3" json:"notifier_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotifierCountResult) Reset() {
	*x = GetNotifierCountResult{}
	mi := &file_crownotify_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotifierCountResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotifierCountResult) ProtoMessage() {}

func (x *GetNotifierCountResult) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotifierCountResult.ProtoReflect.Descriptor instead.
func (*GetNotifierCountResult) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{11}
}

func (x *GetNotifierCountResult) GetNotifierCount() uint64 {
	if x != nil {
		return x.NotifierCount
	}
	return 0
}

type GetNotifierListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotifierListRequest) Reset() {
	*x = GetNotifierListRequest{}
	mi := &file_crownotify_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotifierListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotifierListRequest) ProtoMessage() {}

func (x *GetNotifierListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotifierListRequest.ProtoReflect.Descriptor instead.
func (*GetNotifierListRequest) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{12}
}

type GetNotifierListResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifiers     string                 `protobuf:"bytes,1,opt,name=notifiers,proto3" json:"notifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotifierListResult) Reset() {
	*x = GetNotifierListResult{}
	mi := &file_crownotify_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotifierListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotifierListResult) ProtoMessage() {}

func (x *GetNotifierListResult) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotifierListResult.ProtoReflect.Descriptor instead.
func (*GetNotifierListResult) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{13}
}

func (x *GetNotifierListResult) GetNotifiers() string {
	if x != nil {
		return x.Notifiers
	}
	return ""
}

type SendNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToUserIDs     []string               `protobuf:"bytes,1,rep,name=toUserIDs,proto3" json:"toUserIDs,omitempty"`
	Event         *NotifyEvent           `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	All           bool                   `protobuf:"varint,4,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotifyRequest) Reset() {
	*x = SendNotifyRequest{}
	mi := &file_crownotify_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotifyRequest) ProtoMessage() {}

func (x *SendNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotifyRequest.ProtoReflect.Descriptor instead.
func (*SendNotifyRequest) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{14}
}

func (x *SendNotifyRequest) GetToUserIDs() []string {
	if x != nil {
		return x.ToUserIDs
	}
	return nil
}

func (x *SendNotifyRequest) GetEvent() *NotifyEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SendNotifyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SendNotifyRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type SendTickerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Score         uint32                 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTickerRequest) Reset() {
	*x = SendTickerRequest{}
	mi := &file_crownotify_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTickerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTickerRequest) ProtoMessage() {}

func (x *SendTickerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTickerRequest.ProtoReflect.Descriptor instead.
func (*SendTickerRequest) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{15}
}

func (x *SendTickerRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *SendTickerRequest) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SendTickerRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PartyId       string                 `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	StageId       string                 `protobuf:"bytes,3,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_crownotify_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{16}
}

func (x *JoinRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *JoinRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

type InviteGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	InvitedBy     string                 `protobuf:"bytes,3,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteGroup) Reset() {
	*x = InviteGroup{}
	mi := &file_crownotify_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteGroup) ProtoMessage() {}

func (x *InviteGroup) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteGroup.ProtoReflect.Descriptor instead.
func (*InviteGroup) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{17}
}

func (x *InviteGroup) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *InviteGroup) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *InviteGroup) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

type AddedGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	AddUserId     string                 `protobuf:"bytes,3,opt,name=addUser_id,json=addUserId,proto3" json:"addUser_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddedGroup) Reset() {
	*x = AddedGroup{}
	mi := &file_crownotify_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddedGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddedGroup) ProtoMessage() {}

func (x *AddedGroup) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddedGroup.ProtoReflect.Descriptor instead.
func (*AddedGroup) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{18}
}

func (x *AddedGroup) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AddedGroup) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *AddedGroup) GetAddUserId() string {
	if x != nil {
		return x.AddUserId
	}
	return ""
}

type Matching struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	StageId       string                 `protobuf:"bytes,2,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matching) Reset() {
	*x = Matching{}
	mi := &file_crownotify_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matching) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matching) ProtoMessage() {}

func (x *Matching) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matching.ProtoReflect.Descriptor instead.
func (*Matching) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{19}
}

func (x *Matching) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *Matching) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

type Online struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsOnline      bool                   `protobuf:"varint,2,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Online) Reset() {
	*x = Online{}
	mi := &file_crownotify_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Online) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Online) ProtoMessage() {}

func (x *Online) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Online.ProtoReflect.Descriptor instead.
func (*Online) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{20}
}

func (x *Online) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Online) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

type UpdateMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  string                 `protobuf:"bytes,1,opt,name=targetUser_id,json=targetUserId,proto3" json:"targetUser_id,omitempty"`
	Party         *Party                 `protobuf:"bytes,2,opt,name=party,proto3" json:"party,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMember) Reset() {
	*x = UpdateMember{}
	mi := &file_crownotify_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMember) ProtoMessage() {}

func (x *UpdateMember) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMember.ProtoReflect.Descriptor instead.
func (*UpdateMember) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateMember) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *UpdateMember) GetParty() *Party {
	if x != nil {
		return x.Party
	}
	return nil
}

type NewBattleId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	BattleId      string                 `protobuf:"bytes,2,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewBattleId) Reset() {
	*x = NewBattleId{}
	mi := &file_crownotify_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewBattleId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBattleId) ProtoMessage() {}

func (x *NewBattleId) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBattleId.ProtoReflect.Descriptor instead.
func (*NewBattleId) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{22}
}

func (x *NewBattleId) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *NewBattleId) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type Party struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PartyId             string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsInBattle          BattleStatus           `protobuf:"varint,3,opt,name=is_in_battle,json=isInBattle,proto3,enum=CrowNotify.BattleStatus" json:"is_in_battle,omitempty"`
	LeaderUserId        string                 `protobuf:"bytes,4,opt,name=leaderUser_id,json=leaderUserId,proto3" json:"leaderUser_id,omitempty"`
	Approval            bool                   `protobuf:"varint,5,opt,name=approval,proto3" json:"approval,omitempty"`
	StageId             string                 `protobuf:"bytes,6,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	JobLV               uint32                 `protobuf:"varint,7,opt,name=jobLV,proto3" json:"jobLV,omitempty"`
	Power               uint64                 `protobuf:"varint,8,opt,name=power,proto3" json:"power,omitempty"`
	BattleId            string                 `protobuf:"bytes,9,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	RaidId              uint32                 `protobuf:"varint,10,opt,name=raid_id,json=raidId,proto3" json:"raid_id,omitempty"`
	GuildId             uint32                 `protobuf:"varint,11,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	IsCreatedByMatching bool                   `protobuf:"varint,12,opt,name=is_created_by_matching,json=isCreatedByMatching,proto3" json:"is_created_by_matching,omitempty"`
	Members             []*PartyMember         `protobuf:"bytes,13,rep,name=members,proto3" json:"members,omitempty"`
	Private             bool                   `protobuf:"varint,14,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Party) Reset() {
	*x = Party{}
	mi := &file_crownotify_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Party) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Party) ProtoMessage() {}

func (x *Party) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Party.ProtoReflect.Descriptor instead.
func (*Party) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{23}
}

func (x *Party) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *Party) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Party) GetIsInBattle() BattleStatus {
	if x != nil {
		return x.IsInBattle
	}
	return BattleStatus_BATTLE_STATUS_BEFORE_BATTLE
}

func (x *Party) GetLeaderUserId() string {
	if x != nil {
		return x.LeaderUserId
	}
	return ""
}

func (x *Party) GetApproval() bool {
	if x != nil {
		return x.Approval
	}
	return false
}

func (x *Party) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *Party) GetJobLV() uint32 {
	if x != nil {
		return x.JobLV
	}
	return 0
}

func (x *Party) GetPower() uint64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *Party) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *Party) GetRaidId() uint32 {
	if x != nil {
		return x.RaidId
	}
	return 0
}

func (x *Party) GetGuildId() uint32 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *Party) GetIsCreatedByMatching() bool {
	if x != nil {
		return x.IsCreatedByMatching
	}
	return false
}

func (x *Party) GetMembers() []*PartyMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Party) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

type PartyMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Activity      PlayerActivity         `protobuf:"varint,2,opt,name=activity,proto3,enum=CrowNotify.PlayerActivity" json:"activity,omitempty"`
	Power         uint64                 `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`
	JobLV         uint32                 `protobuf:"varint,4,opt,name=jobLV,proto3" json:"jobLV,omitempty"`
	InLobby       bool                   `protobuf:"varint,5,opt,name=in_lobby,json=inLobby,proto3" json:"in_lobby,omitempty"`
	CanPlay       bool                   `protobuf:"varint,6,opt,name=can_play,json=canPlay,proto3" json:"can_play,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyMember) Reset() {
	*x = PartyMember{}
	mi := &file_crownotify_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyMember) ProtoMessage() {}

func (x *PartyMember) ProtoReflect() protoreflect.Message {
	mi := &file_crownotify_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyMember.ProtoReflect.Descriptor instead.
func (*PartyMember) Descriptor() ([]byte, []int) {
	return file_crownotify_proto_rawDescGZIP(), []int{24}
}

func (x *PartyMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PartyMember) GetActivity() PlayerActivity {
	if x != nil {
		return x.Activity
	}
	return PlayerActivity_PLAYER_ACTIVITY_ACTIVITY_UNKNOWN
}

func (x *PartyMember) GetPower() uint64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *PartyMember) GetJobLV() uint32 {
	if x != nil {
		return x.JobLV
	}
	return 0
}

func (x *PartyMember) GetInLobby() bool {
	if x != nil {
		return x.InLobby
	}
	return false
}

func (x *PartyMember) GetCanPlay() bool {
	if x != nil {
		return x.CanPlay
	}
	return false
}

var File_crownotify_proto protoreflect.FileDescriptor

const file_crownotify_proto_rawDesc = "" +
	"\n" +
	"\x10crownotify.proto\x12\n" +
	"CrowNotify\"\x80\x01\n" +
	"\rNotifyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x05store\x18\x02 \x01(\x0e2\x11.CrowNotify.StoreR\x05store\x12-\n" +
	"\x12registration_token\x18\x03 \x01(\tR\x11registrationToken\"\xd2\x02\n" +
	"\vNotifyEvent\x123\n" +
	"\ainvited\x18\x01 \x01(\v2\x17.CrowNotify.JoinRequestH\x00R\ainvited\x12\x1a\n" +
	"\ageneric\x18\x02 \x01(\tH\x00R\ageneric\x12<\n" +
	"\finvite_group\x18\x03 \x01(\v2\x17.CrowNotify.InviteGroupH\x00R\vinviteGroup\x129\n" +
	"\vadded_group\x18\x04 \x01(\v2\x16.CrowNotify.AddedGroupH\x00R\n" +
	"addedGroup\x12\x18\n" +
	"\x06ticker\x18\x05 \x01(\tH\x00R\x06ticker\x122\n" +
	"\bannounce\x18\x06 \x01(\v2\x14.CrowNotify.AnnounceH\x00R\bannounce\x12\"\n" +
	"\vmaintenance\x18\a \x01(\tH\x00R\vmaintenanceB\a\n" +
	"\x05event\"-\n" +
	"\x12CloseNotifyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x13\n" +
	"\x11CloseNotifyResult\"\r\n" +
	"\vNullRequest\"\x0e\n" +
	"\fNullResponse\"\xe0\x01\n" +
	"\x0fAnnounceRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12=\n" +
	"\rannounce_type\x18\x05 \x01(\x0e2\x18.CrowNotify.AnnounceTypeR\fannounceType\x12\x19\n" +
	"\bstart_at\x18\x06 \x01(\x03R\astartAt\x12\x15\n" +
	"\x06end_at\x18\a \x01(\x03R\x05endAt\"\xbd\x01\n" +
	"\bAnnounce\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12=\n" +
	"\rannounce_type\x18\x04 \x01(\x0e2\x18.CrowNotify.AnnounceTypeR\fannounceType\x12\x19\n" +
	"\bstart_at\x18\x05 \x01(\x03R\astartAt\x12\x15\n" +
	"\x06end_at\x18\x06 \x01(\x03R\x05endAt\"b\n" +
	"\x12MaintenanceRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x19\n" +
	"\bstart_at\x18\x02 \x01(\x03R\astartAt\x12\x15\n" +
	"\x06end_at\x18\x03 \x01(\x03R\x05endAt\"?\n" +
	"\vMaintenance\x12\x19\n" +
	"\bstart_at\x18\x01 \x01(\x03R\astartAt\x12\x15\n" +
	"\x06end_at\x18\x02 \x01(\x03R\x05endAt\"5\n" +
	"\x17GetNotifierCountRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"?\n" +
	"\x16GetNotifierCountResult\x12%\n" +
	"\x0enotifier_count\x18\x01 \x01(\x04R\rnotifierCount\"\x18\n" +
	"\x16GetNotifierListRequest\"5\n" +
	"\x15GetNotifierListResult\x12\x1c\n" +
	"\tnotifiers\x18\x01 \x01(\tR\tnotifiers\"\x8e\x01\n" +
	"\x11SendNotifyRequest\x12\x1c\n" +
	"\ttoUserIDs\x18\x01 \x03(\tR\ttoUserIDs\x12-\n" +
	"\x05event\x18\x02 \x01(\v2\x17.CrowNotify.NotifyEventR\x05event\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x10\n" +
	"\x03all\x18\x04 \x01(\bR\x03all\"]\n" +
	"\x11SendTickerRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x14\n" +
	"\x05score\x18\x02 \x01(\rR\x05score\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\\\n" +
	"\vJoinRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bparty_id\x18\x02 \x01(\tR\apartyId\x12\x19\n" +
	"\bstage_id\x18\x03 \x01(\tR\astageId\"b\n" +
	"\vInviteGroup\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x03 \x01(\tR\tinvitedBy\"a\n" +
	"\n" +
	"AddedGroup\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x1d\n" +
	"\n" +
	"addUser_id\x18\x03 \x01(\tR\taddUserId\"@\n" +
	"\bMatching\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x19\n" +
	"\bstage_id\x18\x02 \x01(\tR\astageId\">\n" +
	"\x06Online\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_online\x18\x02 \x01(\bR\bisOnline\"\\\n" +
	"\fUpdateMember\x12#\n" +
	"\rtargetUser_id\x18\x01 \x01(\tR\ftargetUserId\x12'\n" +
	"\x05party\x18\x02 \x01(\v2\x11.CrowNotify.PartyR\x05party\"F\n" +
	"\fNewBattle_id\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1b\n" +
	"\tbattle_id\x18\x02 \x01(\tR\bbattleId\"\xcd\x03\n" +
	"\x05Party\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12:\n" +
	"\fis_in_battle\x18\x03 \x01(\x0e2\x18.CrowNotify.BattleStatusR\n" +
	"isInBattle\x12#\n" +
	"\rleaderUser_id\x18\x04 \x01(\tR\fleaderUserId\x12\x1a\n" +
	"\bapproval\x18\x05 \x01(\bR\bapproval\x12\x19\n" +
	"\bstage_id\x18\x06 \x01(\tR\astageId\x12\x14\n" +
	"\x05jobLV\x18\a \x01(\rR\x05jobLV\x12\x14\n" +
	"\x05power\x18\b \x01(\x04R\x05power\x12\x1b\n" +
	"\tbattle_id\x18\t \x01(\tR\bbattleId\x12\x17\n" +
	"\araid_id\x18\n" +
	" \x01(\rR\x06raidId\x12\x19\n" +
	"\bguild_id\x18\v \x01(\rR\aguildId\x123\n" +
	"\x16is_created_by_matching\x18\f \x01(\bR\x13isCreatedByMatching\x121\n" +
	"\amembers\x18\r \x03(\v2\x17.CrowNotify.PartyMemberR\amembers\x12\x18\n" +
	"\aprivate\x18\x0e \x01(\bR\aprivate\"\xc0\x01\n" +
	"\vPartyMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x126\n" +
	"\bactivity\x18\x02 \x01(\x0e2\x1a.CrowNotify.PlayerActivityR\bactivity\x12\x14\n" +
	"\x05power\x18\x03 \x01(\x04R\x05power\x12\x14\n" +
	"\x05jobLV\x18\x04 \x01(\rR\x05jobLV\x12\x19\n" +
	"\bin_lobby\x18\x05 \x01(\bR\ainLobby\x12\x19\n" +
	"\bcan_play\x18\x06 \x01(\bR\acanPlay*C\n" +
	"\x05Store\x12\x11\n" +
	"\rSTORE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fSTORE_ITUNES\x10\x01\x12\x15\n" +
	"\x11STORE_GOOGLE_PLAY\x10\x02*\x83\x01\n" +
	"\fAnnounceType\x12\x19\n" +
	"\x15ANNOUNCE_TYPE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18ANNOUNCE_TYPE_ANNOUNCE_1\x10\x01\x12\x1c\n" +
	"\x18ANNOUNCE_TYPE_ANNOUNCE_2\x10\x02\x12\x1c\n" +
	"\x18ANNOUNCE_TYPE_ANNOUNCE_3\x10\x03*o\n" +
	"\fBattleStatus\x12\x1f\n" +
	"\x1bBATTLE_STATUS_BEFORE_BATTLE\x10\x00\x12!\n" +
	"\x1dBATTLE_STATUS_ENTERING_BATTLE\x10\x01\x12\x1b\n" +
	"\x17BATTLE_STATUS_IN_BATTLE\x10\x02*\x7f\n" +
	"\x0ePlayerActivity\x12$\n" +
	" PLAYER_ACTIVITY_ACTIVITY_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bPLAYER_ACTIVITY_ACTIVITY_OK\x10\x01\x12&\n" +
	"\"PLAYER_ACTIVITY_ACTIVITY_PREPARING\x10\x022\xf3\x05\n" +
	"\n" +
	"CrowNotify\x12>\n" +
	"\x06Notify\x12\x19.CrowNotify.NotifyRequest\x1a\x17.CrowNotify.NotifyEvent0\x01\x12L\n" +
	"\vCloseNotify\x12\x1e.CrowNotify.CloseNotifyRequest\x1a\x1d.CrowNotify.CloseNotifyResult\x12<\n" +
	"\vGetAnnounce\x12\x17.CrowNotify.NullRequest\x1a\x14.CrowNotify.Announce\x12B\n" +
	"\x0eGetMaintenance\x12\x17.CrowNotify.NullRequest\x1a\x17.CrowNotify.Maintenance\x12[\n" +
	"\x10GetNotifierCount\x12#.CrowNotify.GetNotifierCountRequest\x1a\".CrowNotify.GetNotifierCountResult\x12X\n" +
	"\x0fGetNotifierList\x12\".CrowNotify.GetNotifierListRequest\x1a!.CrowNotify.GetNotifierListResult\x12D\n" +
	"\vSetAnnounce\x12\x1b.CrowNotify.AnnounceRequest\x1a\x18.CrowNotify.NullResponse\x12J\n" +
	"\x0eSetMaintenance\x12\x1e.CrowNotify.MaintenanceRequest\x1a\x18.CrowNotify.NullResponse\x12E\n" +
	"\n" +
	"SendNotify\x12\x1d.CrowNotify.SendNotifyRequest\x1a\x18.CrowNotify.NullResponse\x12E\n" +
	"\n" +
	"SendTicker\x12\x1d.CrowNotify.SendTickerRequest\x1a\x18.CrowNotify.NullResponseB0Z.example.com/brave-revival/src/proto/crownotifyb\x06proto3"

var (
	file_crownotify_proto_rawDescOnce sync.Once
	file_crownotify_proto_rawDescData []byte
)

func file_crownotify_proto_rawDescGZIP() []byte {
	file_crownotify_proto_rawDescOnce.Do(func() {
		file_crownotify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crownotify_proto_rawDesc), len(file_crownotify_proto_rawDesc)))
	})
	return file_crownotify_proto_rawDescData
}

var file_crownotify_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_crownotify_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_crownotify_proto_goTypes = []any{
	(Store)(0),                      // 0: CrowNotify.Store
	(AnnounceType)(0),               // 1: CrowNotify.AnnounceType
	(BattleStatus)(0),               // 2: CrowNotify.BattleStatus
	(PlayerActivity)(0),             // 3: CrowNotify.PlayerActivity
	(*NotifyRequest)(nil),           // 4: CrowNotify.NotifyRequest
	(*NotifyEvent)(nil),             // 5: CrowNotify.NotifyEvent
	(*CloseNotifyRequest)(nil),      // 6: CrowNotify.CloseNotifyRequest
	(*CloseNotifyResult)(nil),       // 7: CrowNotify.CloseNotifyResult
	(*NullRequest)(nil),             // 8: CrowNotify.NullRequest
	(*NullResponse)(nil),            // 9: CrowNotify.NullResponse
	(*AnnounceRequest)(nil),         // 10: CrowNotify.AnnounceRequest
	(*Announce)(nil),                // 11: CrowNotify.Announce
	(*MaintenanceRequest)(nil),      // 12: CrowNotify.MaintenanceRequest
	(*Maintenance)(nil),             // 13: CrowNotify.Maintenance
	(*GetNotifierCountRequest)(nil), // 14: CrowNotify.GetNotifierCountRequest
	(*GetNotifierCountResult)(nil),  // 15: CrowNotify.GetNotifierCountResult
	(*GetNotifierListRequest)(nil),  // 16: CrowNotify.GetNotifierListRequest
	(*GetNotifierListResult)(nil),   // 17: CrowNotify.GetNotifierListResult
	(*SendNotifyRequest)(nil),       // 18: CrowNotify.SendNotifyRequest
	(*SendTickerRequest)(nil),       // 19: CrowNotify.SendTickerRequest
	(*JoinRequest)(nil),             // 20: CrowNotify.JoinRequest
	(*InviteGroup)(nil),             // 21: CrowNotify.InviteGroup
	(*AddedGroup)(nil),              // 22: CrowNotify.AddedGroup
	(*Matching)(nil),                // 23: CrowNotify.Matching
	(*Online)(nil),                  // 24: CrowNotify.Online
	(*UpdateMember)(nil),            // 25: CrowNotify.UpdateMember
	(*NewBattleId)(nil),             // 26: CrowNotify.NewBattle_id
	(*Party)(nil),                   // 27: CrowNotify.Party
	(*PartyMember)(nil),             // 28: CrowNotify.PartyMember
}
var file_crownotify_proto_depIdxs = []int32{
	0,  // 0: CrowNotify.NotifyRequest.store:type_name -> CrowNotify.Store
	20, // 1: CrowNotify.NotifyEvent.invited:type_name -> CrowNotify.JoinRequest
	21, // 2: CrowNotify.NotifyEvent.invite_group:type_name -> CrowNotify.InviteGroup
	22, // 3: CrowNotify.NotifyEvent.added_group:type_name -> CrowNotify.AddedGroup
	11, // 4: CrowNotify.NotifyEvent.announce:type_name -> CrowNotify.Announce
	1,  // 5: CrowNotify.AnnounceRequest.announce_type:type_name -> CrowNotify.AnnounceType
	1,  // 6: CrowNotify.Announce.announce_type:type_name -> CrowNotify.AnnounceType
	5,  // 7: CrowNotify.SendNotifyRequest.event:type_name -> CrowNotify.NotifyEvent
	27, // 8: CrowNotify.UpdateMember.party:type_name -> CrowNotify.Party
	2,  // 9: CrowNotify.Party.is_in_battle:type_name -> CrowNotify.BattleStatus
	28, // 10: CrowNotify.Party.members:type_name -> CrowNotify.PartyMember
	3,  // 11: CrowNotify.PartyMember.activity:type_name -> CrowNotify.PlayerActivity
	4,  // 12: CrowNotify.CrowNotify.Notify:input_type -> CrowNotify.NotifyRequest
	6,  // 13: CrowNotify.CrowNotify.CloseNotify:input_type -> CrowNotify.CloseNotifyRequest
	8,  // 14: CrowNotify.CrowNotify.GetAnnounce:input_type -> CrowNotify.NullRequest
	8,  // 15: CrowNotify.CrowNotify.GetMaintenance:input_type -> CrowNotify.NullRequest
	14, // 16: CrowNotify.CrowNotify.GetNotifierCount:input_type -> CrowNotify.GetNotifierCountRequest
	16, // 17: CrowNotify.CrowNotify.GetNotifierList:input_type -> CrowNotify.GetNotifierListRequest
	10, // 18: CrowNotify.CrowNotify.SetAnnounce:input_type -> CrowNotify.AnnounceRequest
	12, // 19: CrowNotify.CrowNotify.SetMaintenance:input_type -> CrowNotify.MaintenanceRequest
	18, // 20: CrowNotify.CrowNotify.SendNotify:input_type -> CrowNotify.SendNotifyRequest
	19, // 21: CrowNotify.CrowNotify.SendTicker:input_type -> CrowNotify.SendTickerRequest
	5,  // 22: CrowNotify.CrowNotify.Notify:output_type -> CrowNotify.NotifyEvent
	7,  // 23: CrowNotify.CrowNotify.CloseNotify:output_type -> CrowNotify.CloseNotifyResult
	11, // 24: CrowNotify.CrowNotify.GetAnnounce:output_type -> CrowNotify.Announce
	13, // 25: CrowNotify.CrowNotify.GetMaintenance:output_type -> CrowNotify.Maintenance
	15, // 26: CrowNotify.CrowNotify.GetNotifierCount:output_type -> CrowNotify.GetNotifierCountResult
	17, // 27: CrowNotify.CrowNotify.GetNotifierList:output_type -> CrowNotify.GetNotifierListResult
	9,  // 28: CrowNotify.CrowNotify.SetAnnounce:output_type -> CrowNotify.NullResponse
	9,  // 29: CrowNotify.CrowNotify.SetMaintenance:output_type -> CrowNotify.NullResponse
	9,  // 30: CrowNotify.CrowNotify.SendNotify:output_type -> CrowNotify.NullResponse
	9,  // 31: CrowNotify.CrowNotify.SendTicker:output_type -> CrowNotify.NullResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_crownotify_proto_init() }
func file_crownotify_proto_init() {
	if File_crownotify_proto != nil {
		return
	}
	file_crownotify_proto_msgTypes[1].OneofWrappers = []any{
		(*NotifyEvent_Invited)(nil),
		(*NotifyEvent_Generic)(nil),
		(*NotifyEvent_InviteGroup)(nil),
		(*NotifyEvent_AddedGroup)(nil),
		(*NotifyEvent_Ticker)(nil),
		(*NotifyEvent_Announce)(nil),
		(*NotifyEvent_Maintenance)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crownotify_proto_rawDesc), len(file_crownotify_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crownotify_proto_goTypes,
		DependencyIndexes: file_crownotify_proto_depIdxs,
		EnumInfos:         file_crownotify_proto_enumTypes,
		MessageInfos:      file_crownotify_proto_msgTypes,
	}.Build()
	File_crownotify_proto = out.File
	file_crownotify_proto_goTypes = nil
	file_crownotify_proto_depIdxs = nil
}
