syntax = "proto3";
package Puser;

import "options.proto";

option go_package = "example.com/brave-revival/src/proto/puser";

message Player {
    uint64 id = 1;
    string wallet_id = 2;
    uint64 account_id = 3;
    string status = 4;
    uint32 tutorial_step = 5;
    string nickname = 6;
    string comment = 7;
    uint32 job_id = 8;
    uint32 title_id = 9;
    uint32 inventory_slots = 10;
    uint32 character_slots = 11;
    uint32 accessory_slots = 12;
    uint64 lupi = 13;
    uint64 topaz = 14;
    uint64 mileage = 15;
    uint64 guild_coin = 16;
    uint64 yell = 17;
    uint64 agito_coin = 18;
    uint64 interior_coin = 19;
    uint32 blue_skill_point = 20;
    uint32 red_skill_point = 21;
    uint32 achievement_rank = 22;
    uint32 achievement_point = 23;
    uint64 favorite_equipment_id_1 = 24;
    uint64 favorite_equipment_id_1_costume = 25;
    uint64 favorite_equipment_id_1_stylish_head = 26;
    uint64 favorite_equipment_id_1_stylish_body = 27;
    uint64 favorite_equipment_id_2 = 28;
    uint64 favorite_equipment_id_2_costume = 29;
    uint64 favorite_equipment_id_2_stylish_head = 30;
    uint64 favorite_equipment_id_2_stylish_body = 31;
    uint64 favorite_equipment_id_3 = 32;
    uint64 favorite_equipment_id_3_costume = 33;
    uint64 favorite_equipment_id_3_stylish_head = 34;
    uint64 favorite_equipment_id_3_stylish_body = 35;
    uint64 max_damage = 36;
    uint64 total_yell = 37;
    uint64 total_login = 38;
    string last_login_at = 39 [(options.datetime) = true];
    string name_changed_at = 40 [(options.datetime) = true];
    string newbie_shop_opened_at = 41 [(options.datetime) = true];
    string come_back_expired_at = 42 [(options.datetime) = true];
    string opened_at = 43 [(options.datetime) = true];
}

message Job {
    uint64 player_id = 1;
    uint32 job_id = 2;
    uint32 level = 3;
    uint64 exp = 4;
    uint32 job_deck_idx = 5;
    uint32 job_equipment_idx = 6;
    uint32 is_new = 7;
}

message JobDeck {
    uint64 id = 1;
    uint32 idx = 2;
    uint64 player_id = 3;
    uint32 job_id = 4;
    string label = 5;
    uint64 line1_main_front = 6;
    uint64 line1_main_rear = 7;
    uint64 line1_main_costume = 8;
    uint64 line1_main_stylish_head = 9;
    uint64 line1_main_stylish_body = 10;
    uint64 line1_main_stylish_weapon = 11;
    uint64 line1_main_stylish_device = 12;
    uint32 line1_stylish_flag = 13;
    uint64 line1_main_accessory1 = 14;
    uint64 line1_main_accessory2 = 15;
    uint64 line1_sub1_front = 16;
    uint64 line1_sub1_rear = 17;
    uint64 line1_sub1_accessory1 = 18;
    uint64 line1_sub1_accessory2 = 19;
    uint64 line1_sub2_front = 20;
    uint64 line1_sub2_rear = 21;
    uint64 line1_sub2_accessory1 = 22;
    uint64 line1_sub2_accessory2 = 23;
    uint64 line1_sub3_front = 24;
    uint64 line1_sub3_rear = 25;
    uint64 line1_sub3_accessory1 = 26;
    uint64 line1_sub3_accessory2 = 27;
    uint64 line1_sub4_front = 28;
    uint64 line1_sub4_rear = 29;
    uint64 line1_sub4_accessory1 = 30;
    uint64 line1_sub4_accessory2 = 31;
    uint64 line1_sub5_front = 32;
    uint64 line1_sub5_rear = 33;
    uint64 line1_sub5_accessory1 = 34;
    uint64 line1_sub5_accessory2 = 35;
    uint64 line1_sub6_front = 36;
    uint64 line1_sub6_rear = 37;
    uint64 line1_sub6_accessory1 = 38;
    uint64 line1_sub6_accessory2 = 39;
    uint64 line1_sub7_front = 40;
    uint64 line1_sub7_rear = 41;
    uint64 line1_sub7_accessory1 = 42;
    uint64 line1_sub7_accessory2 = 43;
    uint64 line1_sub8_front = 44;
    uint64 line1_sub8_rear = 45;
    uint64 line1_sub8_accessory1 = 46;
    uint64 line1_sub8_accessory2 = 47;
    uint64 line1_sub9_front = 48;
    uint64 line1_sub9_rear = 49;
    uint64 line1_sub9_accessory1 = 50;
    uint64 line1_sub9_accessory2 = 51;
    uint64 line1_sub10_front = 52;
    uint64 line1_sub10_rear = 53;
    uint64 line1_sub10_accessory1 = 54;
    uint64 line1_sub10_accessory2 = 55;
    uint64 line1_sub11_front = 56;
    uint64 line1_sub11_rear = 57;
    uint64 line1_sub11_accessory1 = 58;
    uint64 line1_sub11_accessory2 = 59;
    uint64 line1_sub12_front = 60;
    uint64 line1_sub12_rear = 61;
    uint64 line1_sub12_accessory1 = 62;
    uint64 line1_sub12_accessory2 = 63;
    uint64 line1_sub13_front = 64;
    uint64 line1_sub13_rear = 65;
    uint64 line1_sub13_accessory1 = 66;
    uint64 line1_sub13_accessory2 = 67;
    uint64 line1_sub14_front = 68;
    uint64 line1_sub14_rear = 69;
    uint64 line1_sub14_accessory1 = 70;
    uint64 line1_sub14_accessory2 = 71;
    uint64 line1_sub15_front = 72;
    uint64 line1_sub15_rear = 73;
    uint64 line1_sub15_accessory1 = 74;
    uint64 line1_sub15_accessory2 = 75;
    uint64 line1_sub16_front = 76;
    uint64 line1_sub16_rear = 77;
    uint64 line1_sub16_accessory1 = 78;
    uint64 line1_sub16_accessory2 = 79;
    uint64 line1_sub17_front = 80;
    uint64 line1_sub17_rear = 81;
    uint64 line1_sub17_accessory1 = 82;
    uint64 line1_sub17_accessory2 = 83;
    uint64 line1_sub18_front = 84;
    uint64 line1_sub18_rear = 85;
    uint64 line1_sub18_accessory1 = 86;
    uint64 line1_sub18_accessory2 = 87;
    uint64 line1_sub19_front = 88;
    uint64 line1_sub19_rear = 89;
    uint64 line1_sub19_accessory1 = 90;
    uint64 line1_sub19_accessory2 = 91;
    uint64 line1_sub20_front = 92;
    uint64 line1_sub20_rear = 93;
    uint64 line1_sub20_accessory1 = 94;
    uint64 line1_sub20_accessory2 = 95;
    uint64 line1_sub21_front = 96;
    uint64 line1_sub21_rear = 97;
    uint64 line1_sub21_accessory1 = 98;
    uint64 line1_sub21_accessory2 = 99;
    uint64 line1_sub22_front = 100;
    uint64 line1_sub22_rear = 101;
    uint64 line1_sub22_accessory1 = 102;
    uint64 line1_sub22_accessory2 = 103;
    uint64 line1_sub23_front = 104;
    uint64 line1_sub23_rear = 105;
    uint64 line1_sub23_accessory1 = 106;
    uint64 line1_sub23_accessory2 = 107;
    uint64 line1_sub24_front = 108;
    uint64 line1_sub24_rear = 109;
    uint64 line1_sub24_accessory1 = 110;
    uint64 line1_sub24_accessory2 = 111;
    uint64 line1_sub25_front = 112;
    uint64 line1_sub25_rear = 113;
    uint64 line1_sub25_accessory1 = 114;
    uint64 line1_sub25_accessory2 = 115;
    uint64 line1_sub26_front = 116;
    uint64 line1_sub26_rear = 117;
    uint64 line1_sub26_accessory1 = 118;
    uint64 line1_sub26_accessory2 = 119;
    uint64 line1_sub27_front = 120;
    uint64 line1_sub27_rear = 121;
    uint64 line1_sub27_accessory1 = 122;
    uint64 line1_sub27_accessory2 = 123;
    uint64 line1_sub28_front = 124;
    uint64 line1_sub28_rear = 125;
    uint64 line1_sub28_accessory1 = 126;
    uint64 line1_sub28_accessory2 = 127;
    uint64 line1_sub29_front = 128;
    uint64 line1_sub29_rear = 129;
    uint64 line1_sub29_accessory1 = 130;
    uint64 line1_sub29_accessory2 = 131;
    uint64 line1_sub30_front = 132;
    uint64 line1_sub30_rear = 133;
    uint64 line1_sub30_accessory1 = 134;
    uint64 line1_sub30_accessory2 = 135;
    uint64 line1_sub31_front = 136;
    uint64 line1_sub31_rear = 137;
    uint64 line1_sub31_accessory1 = 138;
    uint64 line1_sub31_accessory2 = 139;
    uint64 line1_sub32_front = 140;
    uint64 line1_sub32_rear = 141;
    uint64 line1_sub32_accessory1 = 142;
    uint64 line1_sub32_accessory2 = 143;
    uint64 line1_sub33_front = 144;
    uint64 line1_sub33_rear = 145;
    uint64 line1_sub33_accessory1 = 146;
    uint64 line1_sub33_accessory2 = 147;
    uint64 line1_sub34_front = 148;
    uint64 line1_sub34_rear = 149;
    uint64 line1_sub34_accessory1 = 150;
    uint64 line1_sub34_accessory2 = 151;
    uint64 line1_sub35_front = 152;
    uint64 line1_sub35_rear = 153;
    uint64 line1_sub35_accessory1 = 154;
    uint64 line1_sub35_accessory2 = 155;
    uint64 line1_sub36_front = 156;
    uint64 line1_sub36_rear = 157;
    uint64 line1_sub36_accessory1 = 158;
    uint64 line1_sub36_accessory2 = 159;
    uint64 line1_sub37_front = 160;
    uint64 line1_sub37_rear = 161;
    uint64 line1_sub37_accessory1 = 162;
    uint64 line1_sub37_accessory2 = 163;
    uint64 line1_sub38_front = 164;
    uint64 line1_sub38_rear = 165;
    uint64 line1_sub38_accessory1 = 166;
    uint64 line1_sub38_accessory2 = 167;
    uint64 line1_sub39_front = 168;
    uint64 line1_sub39_rear = 169;
    uint64 line1_sub39_accessory1 = 170;
    uint64 line1_sub39_accessory2 = 171;
    uint64 line1_sub40_front = 172;
    uint64 line1_sub40_rear = 173;
    uint64 line1_sub40_accessory1 = 174;
    uint64 line1_sub40_accessory2 = 175;
    uint64 line1_sub41_front = 176;
    uint64 line1_sub41_rear = 177;
    uint64 line1_sub41_accessory1 = 178;
    uint64 line1_sub41_accessory2 = 179;
    uint64 line1_sub42_front = 180;
    uint64 line1_sub42_rear = 181;
    uint64 line1_sub42_accessory1 = 182;
    uint64 line1_sub42_accessory2 = 183;
    uint64 line2_main_front = 184;
    uint64 line2_main_rear = 185;
    uint64 line2_main_costume = 186;
    uint64 line2_main_stylish_head = 187;
    uint64 line2_main_stylish_body = 188;
    uint64 line2_main_stylish_weapon = 189;
    uint64 line2_main_stylish_device = 190;
    uint32 line2_stylish_flag = 191;
    uint64 line2_main_accessory1 = 192;
    uint64 line2_main_accessory2 = 193;
    uint64 line2_sub1_front = 194;
    uint64 line2_sub1_rear = 195;
    uint64 line2_sub1_accessory1 = 196;
    uint64 line2_sub1_accessory2 = 197;
    uint64 line2_sub2_front = 198;
    uint64 line2_sub2_rear = 199;
    uint64 line2_sub2_accessory1 = 200;
    uint64 line2_sub2_accessory2 = 201;
    uint64 line2_sub3_front = 202;
    uint64 line2_sub3_rear = 203;
    uint64 line2_sub3_accessory1 = 204;
    uint64 line2_sub3_accessory2 = 205;
    uint64 line2_sub4_front = 206;
    uint64 line2_sub4_rear = 207;
    uint64 line2_sub4_accessory1 = 208;
    uint64 line2_sub4_accessory2 = 209;
    uint64 line2_sub5_front = 210;
    uint64 line2_sub5_rear = 211;
    uint64 line2_sub5_accessory1 = 212;
    uint64 line2_sub5_accessory2 = 213;
    uint64 line2_sub6_front = 214;
    uint64 line2_sub6_rear = 215;
    uint64 line2_sub6_accessory1 = 216;
    uint64 line2_sub6_accessory2 = 217;
    uint64 line2_sub7_front = 218;
    uint64 line2_sub7_rear = 219;
    uint64 line2_sub7_accessory1 = 220;
    uint64 line2_sub7_accessory2 = 221;
    uint64 line2_sub8_front = 222;
    uint64 line2_sub8_rear = 223;
    uint64 line2_sub8_accessory1 = 224;
    uint64 line2_sub8_accessory2 = 225;
    uint64 line2_sub9_front = 226;
    uint64 line2_sub9_rear = 227;
    uint64 line2_sub9_accessory1 = 228;
    uint64 line2_sub9_accessory2 = 229;
    uint64 line2_sub10_front = 230;
    uint64 line2_sub10_rear = 231;
    uint64 line2_sub10_accessory1 = 232;
    uint64 line2_sub10_accessory2 = 233;
    uint64 line2_sub11_front = 234;
    uint64 line2_sub11_rear = 235;
    uint64 line2_sub11_accessory1 = 236;
    uint64 line2_sub11_accessory2 = 237;
    uint64 line2_sub12_front = 238;
    uint64 line2_sub12_rear = 239;
    uint64 line2_sub12_accessory1 = 240;
    uint64 line2_sub12_accessory2 = 241;
    uint64 line2_sub13_front = 242;
    uint64 line2_sub13_rear = 243;
    uint64 line2_sub13_accessory1 = 244;
    uint64 line2_sub13_accessory2 = 245;
    uint64 line2_sub14_front = 246;
    uint64 line2_sub14_rear = 247;
    uint64 line2_sub14_accessory1 = 248;
    uint64 line2_sub14_accessory2 = 249;
    uint64 line2_sub15_front = 250;
    uint64 line2_sub15_rear = 251;
    uint64 line2_sub15_accessory1 = 252;
    uint64 line2_sub15_accessory2 = 253;
    uint64 line2_sub16_front = 254;
    uint64 line2_sub16_rear = 255;
    uint64 line2_sub16_accessory1 = 256;
    uint64 line2_sub16_accessory2 = 257;
    uint64 line2_sub17_front = 258;
    uint64 line2_sub17_rear = 259;
    uint64 line2_sub17_accessory1 = 260;
    uint64 line2_sub17_accessory2 = 261;
    uint64 line2_sub18_front = 262;
    uint64 line2_sub18_rear = 263;
    uint64 line2_sub18_accessory1 = 264;
    uint64 line2_sub18_accessory2 = 265;
    uint64 line2_sub19_front = 266;
    uint64 line2_sub19_rear = 267;
    uint64 line2_sub19_accessory1 = 268;
    uint64 line2_sub19_accessory2 = 269;
    uint64 line2_sub20_front = 270;
    uint64 line2_sub20_rear = 271;
    uint64 line2_sub20_accessory1 = 272;
    uint64 line2_sub20_accessory2 = 273;
    uint64 line2_sub21_front = 274;
    uint64 line2_sub21_rear = 275;
    uint64 line2_sub21_accessory1 = 276;
    uint64 line2_sub21_accessory2 = 277;
    uint64 line2_sub22_front = 278;
    uint64 line2_sub22_rear = 279;
    uint64 line2_sub22_accessory1 = 280;
    uint64 line2_sub22_accessory2 = 281;
    uint64 line2_sub23_front = 282;
    uint64 line2_sub23_rear = 283;
    uint64 line2_sub23_accessory1 = 284;
    uint64 line2_sub23_accessory2 = 285;
    uint64 line2_sub24_front = 286;
    uint64 line2_sub24_rear = 287;
    uint64 line2_sub24_accessory1 = 288;
    uint64 line2_sub24_accessory2 = 289;
    uint64 line2_sub25_front = 290;
    uint64 line2_sub25_rear = 291;
    uint64 line2_sub25_accessory1 = 292;
    uint64 line2_sub25_accessory2 = 293;
    uint64 line2_sub26_front = 294;
    uint64 line2_sub26_rear = 295;
    uint64 line2_sub26_accessory1 = 296;
    uint64 line2_sub26_accessory2 = 297;
    uint64 line2_sub27_front = 298;
    uint64 line2_sub27_rear = 299;
    uint64 line2_sub27_accessory1 = 300;
    uint64 line2_sub27_accessory2 = 301;
    uint64 line2_sub28_front = 302;
    uint64 line2_sub28_rear = 303;
    uint64 line2_sub28_accessory1 = 304;
    uint64 line2_sub28_accessory2 = 305;
    uint64 line2_sub29_front = 306;
    uint64 line2_sub29_rear = 307;
    uint64 line2_sub29_accessory1 = 308;
    uint64 line2_sub29_accessory2 = 309;
    uint64 line2_sub30_front = 310;
    uint64 line2_sub30_rear = 311;
    uint64 line2_sub30_accessory1 = 312;
    uint64 line2_sub30_accessory2 = 313;
    uint64 line2_sub31_front = 314;
    uint64 line2_sub31_rear = 315;
    uint64 line2_sub31_accessory1 = 316;
    uint64 line2_sub31_accessory2 = 317;
    uint64 line2_sub32_front = 318;
    uint64 line2_sub32_rear = 319;
    uint64 line2_sub32_accessory1 = 320;
    uint64 line2_sub32_accessory2 = 321;
    uint64 line2_sub33_front = 322;
    uint64 line2_sub33_rear = 323;
    uint64 line2_sub33_accessory1 = 324;
    uint64 line2_sub33_accessory2 = 325;
    uint64 line2_sub34_front = 326;
    uint64 line2_sub34_rear = 327;
    uint64 line2_sub34_accessory1 = 328;
    uint64 line2_sub34_accessory2 = 329;
    uint64 line2_sub35_front = 330;
    uint64 line2_sub35_rear = 331;
    uint64 line2_sub35_accessory1 = 332;
    uint64 line2_sub35_accessory2 = 333;
    uint64 line2_sub36_front = 334;
    uint64 line2_sub36_rear = 335;
    uint64 line2_sub36_accessory1 = 336;
    uint64 line2_sub36_accessory2 = 337;
    uint64 line2_sub37_front = 338;
    uint64 line2_sub37_rear = 339;
    uint64 line2_sub37_accessory1 = 340;
    uint64 line2_sub37_accessory2 = 341;
    uint64 line2_sub38_front = 342;
    uint64 line2_sub38_rear = 343;
    uint64 line2_sub38_accessory1 = 344;
    uint64 line2_sub38_accessory2 = 345;
    uint64 line2_sub41_front = 346;
    uint64 line2_sub41_rear = 347;
    uint64 line2_sub41_accessory1 = 348;
    uint64 line2_sub41_accessory2 = 349;
    uint64 line2_sub42_front = 350;
    uint64 line2_sub42_rear = 351;
    uint64 line2_sub42_accessory1 = 352;
    uint64 line2_sub42_accessory2 = 353;
    uint64 line2_sub39_front = 354;
    uint64 line2_sub39_rear = 355;
    uint64 line2_sub39_accessory1 = 356;
    uint64 line2_sub39_accessory2 = 357;
    uint64 line2_sub40_front = 358;
    uint64 line2_sub40_rear = 359;
    uint64 line2_sub40_accessory1 = 360;
    uint64 line2_sub40_accessory2 = 361;
    uint64 line3_main_front = 362;
    uint64 line3_main_rear = 363;
    uint64 line3_main_costume = 364;
    uint64 line3_main_stylish_head = 365;
    uint64 line3_main_stylish_body = 366;
    uint64 line3_main_stylish_weapon = 367;
    uint64 line3_main_stylish_device = 368;
    uint32 line3_stylish_flag = 369;
    uint64 line3_main_accessory1 = 370;
    uint64 line3_main_accessory2 = 371;
    uint64 line3_sub1_front = 372;
    uint64 line3_sub1_rear = 373;
    uint64 line3_sub1_accessory1 = 374;
    uint64 line3_sub1_accessory2 = 375;
    uint64 line3_sub2_front = 376;
    uint64 line3_sub2_rear = 377;
    uint64 line3_sub2_accessory1 = 378;
    uint64 line3_sub2_accessory2 = 379;
    uint64 line3_sub3_front = 380;
    uint64 line3_sub3_rear = 381;
    uint64 line3_sub3_accessory1 = 382;
    uint64 line3_sub3_accessory2 = 383;
    uint64 line3_sub4_front = 384;
    uint64 line3_sub4_rear = 385;
    uint64 line3_sub4_accessory1 = 386;
    uint64 line3_sub4_accessory2 = 387;
    uint64 line3_sub5_front = 388;
    uint64 line3_sub5_rear = 389;
    uint64 line3_sub5_accessory1 = 390;
    uint64 line3_sub5_accessory2 = 391;
    uint64 line3_sub6_front = 392;
    uint64 line3_sub6_rear = 393;
    uint64 line3_sub6_accessory1 = 394;
    uint64 line3_sub6_accessory2 = 395;
    uint64 line3_sub7_front = 396;
    uint64 line3_sub7_rear = 397;
    uint64 line3_sub7_accessory1 = 398;
    uint64 line3_sub7_accessory2 = 399;
    uint64 line3_sub8_front = 400;
    uint64 line3_sub8_rear = 401;
    uint64 line3_sub8_accessory1 = 402;
    uint64 line3_sub8_accessory2 = 403;
    uint64 line3_sub9_front = 404;
    uint64 line3_sub9_rear = 405;
    uint64 line3_sub9_accessory1 = 406;
    uint64 line3_sub9_accessory2 = 407;
    uint64 line3_sub10_front = 408;
    uint64 line3_sub10_rear = 409;
    uint64 line3_sub10_accessory1 = 410;
    uint64 line3_sub10_accessory2 = 411;
    uint64 line3_sub11_front = 412;
    uint64 line3_sub11_rear = 413;
    uint64 line3_sub11_accessory1 = 414;
    uint64 line3_sub11_accessory2 = 415;
    uint64 line3_sub12_front = 416;
    uint64 line3_sub12_rear = 417;
    uint64 line3_sub12_accessory1 = 418;
    uint64 line3_sub12_accessory2 = 419;
    uint64 line3_sub13_front = 420;
    uint64 line3_sub13_rear = 421;
    uint64 line3_sub13_accessory1 = 422;
    uint64 line3_sub13_accessory2 = 423;
    uint64 line3_sub14_front = 424;
    uint64 line3_sub14_rear = 425;
    uint64 line3_sub14_accessory1 = 426;
    uint64 line3_sub14_accessory2 = 427;
    uint64 line3_sub15_front = 428;
    uint64 line3_sub15_rear = 429;
    uint64 line3_sub15_accessory1 = 430;
    uint64 line3_sub15_accessory2 = 431;
    uint64 line3_sub16_front = 432;
    uint64 line3_sub16_rear = 433;
    uint64 line3_sub16_accessory1 = 434;
    uint64 line3_sub16_accessory2 = 435;
    uint64 line3_sub17_front = 436;
    uint64 line3_sub17_rear = 437;
    uint64 line3_sub17_accessory1 = 438;
    uint64 line3_sub17_accessory2 = 439;
    uint64 line3_sub18_front = 440;
    uint64 line3_sub18_rear = 441;
    uint64 line3_sub18_accessory1 = 442;
    uint64 line3_sub18_accessory2 = 443;
    uint64 line3_sub19_front = 444;
    uint64 line3_sub19_rear = 445;
    uint64 line3_sub19_accessory1 = 446;
    uint64 line3_sub19_accessory2 = 447;
    uint64 line3_sub20_front = 448;
    uint64 line3_sub20_rear = 449;
    uint64 line3_sub20_accessory1 = 450;
    uint64 line3_sub20_accessory2 = 451;
    uint64 line3_sub21_front = 452;
    uint64 line3_sub21_rear = 453;
    uint64 line3_sub21_accessory1 = 454;
    uint64 line3_sub21_accessory2 = 455;
    uint64 line3_sub22_front = 456;
    uint64 line3_sub22_rear = 457;
    uint64 line3_sub22_accessory1 = 458;
    uint64 line3_sub22_accessory2 = 459;
    uint64 line3_sub23_front = 460;
    uint64 line3_sub23_rear = 461;
    uint64 line3_sub23_accessory1 = 462;
    uint64 line3_sub23_accessory2 = 463;
    uint64 line3_sub24_front = 464;
    uint64 line3_sub24_rear = 465;
    uint64 line3_sub24_accessory1 = 466;
    uint64 line3_sub24_accessory2 = 467;
    uint64 line3_sub25_front = 468;
    uint64 line3_sub25_rear = 469;
    uint64 line3_sub25_accessory1 = 470;
    uint64 line3_sub25_accessory2 = 471;
    uint64 line3_sub26_front = 472;
    uint64 line3_sub26_rear = 473;
    uint64 line3_sub26_accessory1 = 474;
    uint64 line3_sub26_accessory2 = 475;
    uint64 line3_sub27_front = 476;
    uint64 line3_sub27_rear = 477;
    uint64 line3_sub27_accessory1 = 478;
    uint64 line3_sub27_accessory2 = 479;
    uint64 line3_sub28_front = 480;
    uint64 line3_sub28_rear = 481;
    uint64 line3_sub28_accessory1 = 482;
    uint64 line3_sub28_accessory2 = 483;
    uint64 line3_sub29_front = 484;
    uint64 line3_sub29_rear = 485;
    uint64 line3_sub29_accessory1 = 486;
    uint64 line3_sub29_accessory2 = 487;
    uint64 line3_sub30_front = 488;
    uint64 line3_sub30_rear = 489;
    uint64 line3_sub30_accessory1 = 490;
    uint64 line3_sub30_accessory2 = 491;
    uint64 line3_sub31_front = 492;
    uint64 line3_sub31_rear = 493;
    uint64 line3_sub31_accessory1 = 494;
    uint64 line3_sub31_accessory2 = 495;
    uint64 line3_sub32_front = 496;
    uint64 line3_sub32_rear = 497;
    uint64 line3_sub32_accessory1 = 498;
    uint64 line3_sub32_accessory2 = 499;
    uint64 line3_sub33_front = 500;
    uint64 line3_sub33_rear = 501;
    uint64 line3_sub33_accessory1 = 502;
    uint64 line3_sub33_accessory2 = 503;
    uint64 line3_sub34_front = 504;
    uint64 line3_sub34_rear = 505;
    uint64 line3_sub34_accessory1 = 506;
    uint64 line3_sub34_accessory2 = 507;
    uint64 line3_sub35_front = 508;
    uint64 line3_sub35_rear = 509;
    uint64 line3_sub35_accessory1 = 510;
    uint64 line3_sub35_accessory2 = 511;
    uint64 line3_sub36_front = 512;
    uint64 line3_sub36_rear = 513;
    uint64 line3_sub36_accessory1 = 514;
    uint64 line3_sub36_accessory2 = 515;
    uint64 line3_sub37_front = 516;
    uint64 line3_sub37_rear = 517;
    uint64 line3_sub37_accessory1 = 518;
    uint64 line3_sub37_accessory2 = 519;
    uint64 line3_sub38_front = 520;
    uint64 line3_sub38_rear = 521;
    uint64 line3_sub38_accessory1 = 522;
    uint64 line3_sub38_accessory2 = 523;
    uint64 line3_sub41_front = 524;
    uint64 line3_sub41_rear = 525;
    uint64 line3_sub41_accessory1 = 526;
    uint64 line3_sub41_accessory2 = 527;
    uint64 line3_sub42_front = 528;
    uint64 line3_sub42_rear = 529;
    uint64 line3_sub42_accessory1 = 530;
    uint64 line3_sub42_accessory2 = 531;
    uint64 line3_sub39_front = 532;
    uint64 line3_sub39_rear = 533;
    uint64 line3_sub39_accessory1 = 534;
    uint64 line3_sub39_accessory2 = 535;
    uint64 line3_sub40_front = 536;
    uint64 line3_sub40_rear = 537;
    uint64 line3_sub40_accessory1 = 538;
    uint64 line3_sub40_accessory2 = 539;
    uint32 hp_use_at = 540;
    uint32 hp_use_order = 541;
}

message Equipment {
    uint64 id = 1;
    uint64 player_id = 2;
    uint32 equipment_id = 3;
    uint32 equipment_variation_color_id = 4;
    uint32 rarity = 5;
    uint32 level = 6;
    uint32 exp = 7;
    uint32 enhancement = 8;
    float enhancement_correction_rate = 9;
    uint32 limit_break = 10;
    float limit_break_correction_rate = 11;
    uint32 awakening = 12;
    uint64 rune1 = 13;
    uint64 rune2 = 14;
    uint64 rune3 = 15;
    uint64 rune4 = 16;
    uint64 rune5 = 17;
    uint64 rune6 = 18;
    uint64 rune7 = 19;
    uint64 rune8 = 20;
    uint64 rune9 = 21;
    uint64 rune10 = 22;
    uint64 rune11 = 23;
    uint64 rune12 = 24;
    uint64 rune_ex = 25;
    uint64 rune_ex2 = 26;
    uint32 param_option1 = 27;
    uint32 param_option2 = 28;
    uint32 param_option3 = 29;
    uint32 param_option4 = 30;
    uint32 is_param_option1_protected = 31;
    uint32 is_param_option2_protected = 32;
    uint32 is_param_option3_protected = 33;
    uint32 is_param_option4_protected = 34;
    uint32 weapon_skill_level1 = 35;
    float weapon_skill_correction_rate1 = 36;
    uint32 weapon_skill_level2 = 37;
    float weapon_skill_correction_rate2 = 38;
    uint32 weapon_skill_level3 = 39;
    float weapon_skill_correction_rate3 = 40;
    float stylish_correction_rate = 41;
    uint32 is_protected = 42;
    string acquired_at = 43 [(options.datetime) = true];
}

message Elixir {
    uint64 player_id = 1;
    uint32 elixir_id = 2;
    uint32 rank = 3;
    uint32 level = 4;
    string acquired_at = 5 [(options.datetime) = true];
}
