// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: pmisc.proto

package pmisc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuildPersonalMissionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildPersonalMissionList) Reset() {
	*x = GuildPersonalMissionList{}
	mi := &file_pmisc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildPersonalMissionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildPersonalMissionList) ProtoMessage() {}

func (x *GuildPersonalMissionList) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildPersonalMissionList.ProtoReflect.Descriptor instead.
func (*GuildPersonalMissionList) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{0}
}

type GuildSharedMissionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildSharedMissionList) Reset() {
	*x = GuildSharedMissionList{}
	mi := &file_pmisc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildSharedMissionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildSharedMissionList) ProtoMessage() {}

func (x *GuildSharedMissionList) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildSharedMissionList.ProtoReflect.Descriptor instead.
func (*GuildSharedMissionList) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{1}
}

type GuildSharedMissionRankingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildSharedMissionRankingList) Reset() {
	*x = GuildSharedMissionRankingList{}
	mi := &file_pmisc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildSharedMissionRankingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildSharedMissionRankingList) ProtoMessage() {}

func (x *GuildSharedMissionRankingList) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildSharedMissionRankingList.ProtoReflect.Descriptor instead.
func (*GuildSharedMissionRankingList) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{2}
}

type GuildWeeklyMissionRewardList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildWeeklyMissionRewardList) Reset() {
	*x = GuildWeeklyMissionRewardList{}
	mi := &file_pmisc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildWeeklyMissionRewardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildWeeklyMissionRewardList) ProtoMessage() {}

func (x *GuildWeeklyMissionRewardList) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildWeeklyMissionRewardList.ProtoReflect.Descriptor instead.
func (*GuildWeeklyMissionRewardList) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{3}
}

type Guild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guild) Reset() {
	*x = Guild{}
	mi := &file_pmisc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guild) ProtoMessage() {}

func (x *Guild) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guild.ProtoReflect.Descriptor instead.
func (*Guild) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{4}
}

var File_pmisc_proto protoreflect.FileDescriptor

const file_pmisc_proto_rawDesc = "" +
	"\n" +
	"\vpmisc.proto\x12\x05Pmisc\"\x1a\n" +
	"\x18GuildPersonalMissionList\"\x18\n" +
	"\x16GuildSharedMissionList\"\x1f\n" +
	"\x1dGuildSharedMissionRankingList\"\x1e\n" +
	"\x1cGuildWeeklyMissionRewardList\"\a\n" +
	"\x05GuildB+Z)example.com/brave-revival/src/proto/pmiscb\x06proto3"

var (
	file_pmisc_proto_rawDescOnce sync.Once
	file_pmisc_proto_rawDescData []byte
)

func file_pmisc_proto_rawDescGZIP() []byte {
	file_pmisc_proto_rawDescOnce.Do(func() {
		file_pmisc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pmisc_proto_rawDesc), len(file_pmisc_proto_rawDesc)))
	})
	return file_pmisc_proto_rawDescData
}

var file_pmisc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pmisc_proto_goTypes = []any{
	(*GuildPersonalMissionList)(nil),      // 0: Pmisc.GuildPersonalMissionList
	(*GuildSharedMissionList)(nil),        // 1: Pmisc.GuildSharedMissionList
	(*GuildSharedMissionRankingList)(nil), // 2: Pmisc.GuildSharedMissionRankingList
	(*GuildWeeklyMissionRewardList)(nil),  // 3: Pmisc.GuildWeeklyMissionRewardList
	(*Guild)(nil),                         // 4: Pmisc.Guild
}
var file_pmisc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pmisc_proto_init() }
func file_pmisc_proto_init() {
	if File_pmisc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pmisc_proto_rawDesc), len(file_pmisc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pmisc_proto_goTypes,
		DependencyIndexes: file_pmisc_proto_depIdxs,
		MessageInfos:      file_pmisc_proto_msgTypes,
	}.Build()
	File_pmisc_proto = out.File
	file_pmisc_proto_goTypes = nil
	file_pmisc_proto_depIdxs = nil
}
