// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: pmisc.proto

package pmisc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuildPersonalMissionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildPersonalMissionList) Reset() {
	*x = GuildPersonalMissionList{}
	mi := &file_pmisc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildPersonalMissionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildPersonalMissionList) ProtoMessage() {}

func (x *GuildPersonalMissionList) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildPersonalMissionList.ProtoReflect.Descriptor instead.
func (*GuildPersonalMissionList) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{0}
}

type GuildSharedMissionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildSharedMissionList) Reset() {
	*x = GuildSharedMissionList{}
	mi := &file_pmisc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildSharedMissionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildSharedMissionList) ProtoMessage() {}

func (x *GuildSharedMissionList) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildSharedMissionList.ProtoReflect.Descriptor instead.
func (*GuildSharedMissionList) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{1}
}

type GuildSharedMissionRankingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildSharedMissionRankingList) Reset() {
	*x = GuildSharedMissionRankingList{}
	mi := &file_pmisc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildSharedMissionRankingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildSharedMissionRankingList) ProtoMessage() {}

func (x *GuildSharedMissionRankingList) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildSharedMissionRankingList.ProtoReflect.Descriptor instead.
func (*GuildSharedMissionRankingList) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{2}
}

type GuildDonation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       uint64                 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	PlayerId      uint64                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Lupi          uint32                 `protobuf:"varint,3,opt,name=lupi,proto3" json:"lupi,omitempty"`
	Star          uint32                 `protobuf:"varint,4,opt,name=star,proto3" json:"star,omitempty"`
	Moon          uint32                 `protobuf:"varint,5,opt,name=moon,proto3" json:"moon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildDonation) Reset() {
	*x = GuildDonation{}
	mi := &file_pmisc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildDonation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildDonation) ProtoMessage() {}

func (x *GuildDonation) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildDonation.ProtoReflect.Descriptor instead.
func (*GuildDonation) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{3}
}

func (x *GuildDonation) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildDonation) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GuildDonation) GetLupi() uint32 {
	if x != nil {
		return x.Lupi
	}
	return 0
}

func (x *GuildDonation) GetStar() uint32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *GuildDonation) GetMoon() uint32 {
	if x != nil {
		return x.Moon
	}
	return 0
}

type GvgBattleField struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BattleFieldId          uint32                 `protobuf:"varint,1,opt,name=battle_field_id,json=battleFieldId,proto3" json:"battle_field_id,omitempty"`
	StartBattleDate        string                 `protobuf:"bytes,2,opt,name=start_battle_date,json=startBattleDate,proto3" json:"start_battle_date,omitempty"`
	Guild1Id               uint64                 `protobuf:"varint,3,opt,name=guild1_id,json=guild1Id,proto3" json:"guild1_id,omitempty"`
	Guild1IsDummy          uint32                 `protobuf:"varint,4,opt,name=guild1_is_dummy,json=guild1IsDummy,proto3" json:"guild1_is_dummy,omitempty"`
	Guild1Score            uint64                 `protobuf:"varint,5,opt,name=guild1_score,json=guild1Score,proto3" json:"guild1_score,omitempty"`
	Guild1Symbol           uint32                 `protobuf:"varint,6,opt,name=guild1_symbol,json=guild1Symbol,proto3" json:"guild1_symbol,omitempty"`
	Guild1SymbolFrame      uint32                 `protobuf:"varint,7,opt,name=guild1_symbol_frame,json=guild1SymbolFrame,proto3" json:"guild1_symbol_frame,omitempty"`
	Guild1SymbolFrameColor uint32                 `protobuf:"varint,8,opt,name=guild1_symbol_frame_color,json=guild1SymbolFrameColor,proto3" json:"guild1_symbol_frame_color,omitempty"`
	Guild2Id               uint64                 `protobuf:"varint,9,opt,name=guild2_id,json=guild2Id,proto3" json:"guild2_id,omitempty"`
	Guild2IsDummy          uint32                 `protobuf:"varint,10,opt,name=guild2_is_dummy,json=guild2IsDummy,proto3" json:"guild2_is_dummy,omitempty"`
	Guild2Score            uint64                 `protobuf:"varint,11,opt,name=guild2_score,json=guild2Score,proto3" json:"guild2_score,omitempty"`
	Guild2Symbol           uint32                 `protobuf:"varint,12,opt,name=guild2_symbol,json=guild2Symbol,proto3" json:"guild2_symbol,omitempty"`
	Guild2SymbolFrame      uint32                 `protobuf:"varint,13,opt,name=guild2_symbol_frame,json=guild2SymbolFrame,proto3" json:"guild2_symbol_frame,omitempty"`
	Guild2SymbolFrameColor uint32                 `protobuf:"varint,14,opt,name=guild2_symbol_frame_color,json=guild2SymbolFrameColor,proto3" json:"guild2_symbol_frame_color,omitempty"`
	PreLeaderGuildId       uint64                 `protobuf:"varint,15,opt,name=pre_leader_guild_id,json=preLeaderGuildId,proto3" json:"pre_leader_guild_id,omitempty"`
	WinnerGuildId          uint64                 `protobuf:"varint,16,opt,name=winner_guild_id,json=winnerGuildId,proto3" json:"winner_guild_id,omitempty"`
	IsFinished             uint32                 `protobuf:"varint,17,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	Reason                 uint32                 `protobuf:"varint,18,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GvgBattleField) Reset() {
	*x = GvgBattleField{}
	mi := &file_pmisc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GvgBattleField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GvgBattleField) ProtoMessage() {}

func (x *GvgBattleField) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GvgBattleField.ProtoReflect.Descriptor instead.
func (*GvgBattleField) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{4}
}

func (x *GvgBattleField) GetBattleFieldId() uint32 {
	if x != nil {
		return x.BattleFieldId
	}
	return 0
}

func (x *GvgBattleField) GetStartBattleDate() string {
	if x != nil {
		return x.StartBattleDate
	}
	return ""
}

func (x *GvgBattleField) GetGuild1Id() uint64 {
	if x != nil {
		return x.Guild1Id
	}
	return 0
}

func (x *GvgBattleField) GetGuild1IsDummy() uint32 {
	if x != nil {
		return x.Guild1IsDummy
	}
	return 0
}

func (x *GvgBattleField) GetGuild1Score() uint64 {
	if x != nil {
		return x.Guild1Score
	}
	return 0
}

func (x *GvgBattleField) GetGuild1Symbol() uint32 {
	if x != nil {
		return x.Guild1Symbol
	}
	return 0
}

func (x *GvgBattleField) GetGuild1SymbolFrame() uint32 {
	if x != nil {
		return x.Guild1SymbolFrame
	}
	return 0
}

func (x *GvgBattleField) GetGuild1SymbolFrameColor() uint32 {
	if x != nil {
		return x.Guild1SymbolFrameColor
	}
	return 0
}

func (x *GvgBattleField) GetGuild2Id() uint64 {
	if x != nil {
		return x.Guild2Id
	}
	return 0
}

func (x *GvgBattleField) GetGuild2IsDummy() uint32 {
	if x != nil {
		return x.Guild2IsDummy
	}
	return 0
}

func (x *GvgBattleField) GetGuild2Score() uint64 {
	if x != nil {
		return x.Guild2Score
	}
	return 0
}

func (x *GvgBattleField) GetGuild2Symbol() uint32 {
	if x != nil {
		return x.Guild2Symbol
	}
	return 0
}

func (x *GvgBattleField) GetGuild2SymbolFrame() uint32 {
	if x != nil {
		return x.Guild2SymbolFrame
	}
	return 0
}

func (x *GvgBattleField) GetGuild2SymbolFrameColor() uint32 {
	if x != nil {
		return x.Guild2SymbolFrameColor
	}
	return 0
}

func (x *GvgBattleField) GetPreLeaderGuildId() uint64 {
	if x != nil {
		return x.PreLeaderGuildId
	}
	return 0
}

func (x *GvgBattleField) GetWinnerGuildId() uint64 {
	if x != nil {
		return x.WinnerGuildId
	}
	return 0
}

func (x *GvgBattleField) GetIsFinished() uint32 {
	if x != nil {
		return x.IsFinished
	}
	return 0
}

func (x *GvgBattleField) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type GuildItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       uint64                 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	ItemId        uint32                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildItem) Reset() {
	*x = GuildItem{}
	mi := &file_pmisc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildItem) ProtoMessage() {}

func (x *GuildItem) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildItem.ProtoReflect.Descriptor instead.
func (*GuildItem) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{5}
}

func (x *GuildItem) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildItem) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GuildItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GvgPracticeMatching struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	GuildId             uint64                 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	GvgId               uint32                 `protobuf:"varint,2,opt,name=gvg_id,json=gvgId,proto3" json:"gvg_id,omitempty"`
	Status              uint32                 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	EntryAt             string                 `protobuf:"bytes,4,opt,name=entry_at,json=entryAt,proto3" json:"entry_at,omitempty"`
	Lv                  uint32                 `protobuf:"varint,5,opt,name=lv,proto3" json:"lv,omitempty"`
	MatchingAt          string                 `protobuf:"bytes,6,opt,name=matching_at,json=matchingAt,proto3" json:"matching_at,omitempty"`
	Power               uint32                 `protobuf:"varint,7,opt,name=power,proto3" json:"power,omitempty"`
	MemberLimit         uint32                 `protobuf:"varint,8,opt,name=member_limit,json=memberLimit,proto3" json:"member_limit,omitempty"`
	MatchTime           uint32                 `protobuf:"varint,9,opt,name=match_time,json=matchTime,proto3" json:"match_time,omitempty"`
	Password            string                 `protobuf:"bytes,10,opt,name=password,proto3" json:"password,omitempty"`
	Description         string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	IsRoomOwner         uint32                 `protobuf:"varint,12,opt,name=is_room_owner,json=isRoomOwner,proto3" json:"is_room_owner,omitempty"`
	GvgPracticeBattleId uint64                 `protobuf:"varint,13,opt,name=gvg_practice_battle_id,json=gvgPracticeBattleId,proto3" json:"gvg_practice_battle_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GvgPracticeMatching) Reset() {
	*x = GvgPracticeMatching{}
	mi := &file_pmisc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GvgPracticeMatching) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GvgPracticeMatching) ProtoMessage() {}

func (x *GvgPracticeMatching) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GvgPracticeMatching.ProtoReflect.Descriptor instead.
func (*GvgPracticeMatching) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{6}
}

func (x *GvgPracticeMatching) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GvgPracticeMatching) GetGvgId() uint32 {
	if x != nil {
		return x.GvgId
	}
	return 0
}

func (x *GvgPracticeMatching) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GvgPracticeMatching) GetEntryAt() string {
	if x != nil {
		return x.EntryAt
	}
	return ""
}

func (x *GvgPracticeMatching) GetLv() uint32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

func (x *GvgPracticeMatching) GetMatchingAt() string {
	if x != nil {
		return x.MatchingAt
	}
	return ""
}

func (x *GvgPracticeMatching) GetPower() uint32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *GvgPracticeMatching) GetMemberLimit() uint32 {
	if x != nil {
		return x.MemberLimit
	}
	return 0
}

func (x *GvgPracticeMatching) GetMatchTime() uint32 {
	if x != nil {
		return x.MatchTime
	}
	return 0
}

func (x *GvgPracticeMatching) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GvgPracticeMatching) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GvgPracticeMatching) GetIsRoomOwner() uint32 {
	if x != nil {
		return x.IsRoomOwner
	}
	return 0
}

func (x *GvgPracticeMatching) GetGvgPracticeBattleId() uint64 {
	if x != nil {
		return x.GvgPracticeBattleId
	}
	return 0
}

type GvgPracticeBattle struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GvgId                  uint32                 `protobuf:"varint,2,opt,name=gvg_id,json=gvgId,proto3" json:"gvg_id,omitempty"`
	Status                 uint32                 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	BattleFieldId          uint32                 `protobuf:"varint,4,opt,name=battle_field_id,json=battleFieldId,proto3" json:"battle_field_id,omitempty"`
	StartBattleDate        string                 `protobuf:"bytes,5,opt,name=start_battle_date,json=startBattleDate,proto3" json:"start_battle_date,omitempty"`
	RoomType               uint32                 `protobuf:"varint,6,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	Power                  uint32                 `protobuf:"varint,7,opt,name=power,proto3" json:"power,omitempty"`
	MemberLimit            uint32                 `protobuf:"varint,8,opt,name=member_limit,json=memberLimit,proto3" json:"member_limit,omitempty"`
	MatchTime              uint32                 `protobuf:"varint,9,opt,name=match_time,json=matchTime,proto3" json:"match_time,omitempty"`
	Guild1Id               uint64                 `protobuf:"varint,10,opt,name=guild1_id,json=guild1Id,proto3" json:"guild1_id,omitempty"`
	Guild1Score            uint64                 `protobuf:"varint,11,opt,name=guild1_score,json=guild1Score,proto3" json:"guild1_score,omitempty"`
	Guild1Symbol           uint32                 `protobuf:"varint,12,opt,name=guild1_symbol,json=guild1Symbol,proto3" json:"guild1_symbol,omitempty"`
	Guild1SymbolFrame      uint32                 `protobuf:"varint,13,opt,name=guild1_symbol_frame,json=guild1SymbolFrame,proto3" json:"guild1_symbol_frame,omitempty"`
	Guild1SymbolFrameColor uint32                 `protobuf:"varint,14,opt,name=guild1_symbol_frame_color,json=guild1SymbolFrameColor,proto3" json:"guild1_symbol_frame_color,omitempty"`
	Guild2Id               uint64                 `protobuf:"varint,15,opt,name=guild2_id,json=guild2Id,proto3" json:"guild2_id,omitempty"`
	Guild2Score            uint64                 `protobuf:"varint,16,opt,name=guild2_score,json=guild2Score,proto3" json:"guild2_score,omitempty"`
	Guild2Symbol           uint32                 `protobuf:"varint,17,opt,name=guild2_symbol,json=guild2Symbol,proto3" json:"guild2_symbol,omitempty"`
	Guild2SymbolFrame      uint32                 `protobuf:"varint,18,opt,name=guild2_symbol_frame,json=guild2SymbolFrame,proto3" json:"guild2_symbol_frame,omitempty"`
	Guild2SymbolFrameColor uint32                 `protobuf:"varint,19,opt,name=guild2_symbol_frame_color,json=guild2SymbolFrameColor,proto3" json:"guild2_symbol_frame_color,omitempty"`
	WinnerGuildId          uint64                 `protobuf:"varint,20,opt,name=winner_guild_id,json=winnerGuildId,proto3" json:"winner_guild_id,omitempty"`
	Reason                 uint32                 `protobuf:"varint,21,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GvgPracticeBattle) Reset() {
	*x = GvgPracticeBattle{}
	mi := &file_pmisc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GvgPracticeBattle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GvgPracticeBattle) ProtoMessage() {}

func (x *GvgPracticeBattle) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GvgPracticeBattle.ProtoReflect.Descriptor instead.
func (*GvgPracticeBattle) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{7}
}

func (x *GvgPracticeBattle) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GvgPracticeBattle) GetGvgId() uint32 {
	if x != nil {
		return x.GvgId
	}
	return 0
}

func (x *GvgPracticeBattle) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GvgPracticeBattle) GetBattleFieldId() uint32 {
	if x != nil {
		return x.BattleFieldId
	}
	return 0
}

func (x *GvgPracticeBattle) GetStartBattleDate() string {
	if x != nil {
		return x.StartBattleDate
	}
	return ""
}

func (x *GvgPracticeBattle) GetRoomType() uint32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

func (x *GvgPracticeBattle) GetPower() uint32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *GvgPracticeBattle) GetMemberLimit() uint32 {
	if x != nil {
		return x.MemberLimit
	}
	return 0
}

func (x *GvgPracticeBattle) GetMatchTime() uint32 {
	if x != nil {
		return x.MatchTime
	}
	return 0
}

func (x *GvgPracticeBattle) GetGuild1Id() uint64 {
	if x != nil {
		return x.Guild1Id
	}
	return 0
}

func (x *GvgPracticeBattle) GetGuild1Score() uint64 {
	if x != nil {
		return x.Guild1Score
	}
	return 0
}

func (x *GvgPracticeBattle) GetGuild1Symbol() uint32 {
	if x != nil {
		return x.Guild1Symbol
	}
	return 0
}

func (x *GvgPracticeBattle) GetGuild1SymbolFrame() uint32 {
	if x != nil {
		return x.Guild1SymbolFrame
	}
	return 0
}

func (x *GvgPracticeBattle) GetGuild1SymbolFrameColor() uint32 {
	if x != nil {
		return x.Guild1SymbolFrameColor
	}
	return 0
}

func (x *GvgPracticeBattle) GetGuild2Id() uint64 {
	if x != nil {
		return x.Guild2Id
	}
	return 0
}

func (x *GvgPracticeBattle) GetGuild2Score() uint64 {
	if x != nil {
		return x.Guild2Score
	}
	return 0
}

func (x *GvgPracticeBattle) GetGuild2Symbol() uint32 {
	if x != nil {
		return x.Guild2Symbol
	}
	return 0
}

func (x *GvgPracticeBattle) GetGuild2SymbolFrame() uint32 {
	if x != nil {
		return x.Guild2SymbolFrame
	}
	return 0
}

func (x *GvgPracticeBattle) GetGuild2SymbolFrameColor() uint32 {
	if x != nil {
		return x.Guild2SymbolFrameColor
	}
	return 0
}

func (x *GvgPracticeBattle) GetWinnerGuildId() uint64 {
	if x != nil {
		return x.WinnerGuildId
	}
	return 0
}

func (x *GvgPracticeBattle) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type GvgPracticeStopSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromDate      string                 `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GvgPracticeStopSchedule) Reset() {
	*x = GvgPracticeStopSchedule{}
	mi := &file_pmisc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GvgPracticeStopSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GvgPracticeStopSchedule) ProtoMessage() {}

func (x *GvgPracticeStopSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GvgPracticeStopSchedule.ProtoReflect.Descriptor instead.
func (*GvgPracticeStopSchedule) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{8}
}

func (x *GvgPracticeStopSchedule) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GvgPracticeStopSchedule) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *GvgPracticeStopSchedule) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type GuildFacility struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       uint64                 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	MasterId      uint32                 `protobuf:"varint,2,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	Level         uint32                 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	BuildupAt     string                 `protobuf:"bytes,5,opt,name=buildup_at,json=buildupAt,proto3" json:"buildup_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildFacility) Reset() {
	*x = GuildFacility{}
	mi := &file_pmisc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildFacility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildFacility) ProtoMessage() {}

func (x *GuildFacility) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildFacility.ProtoReflect.Descriptor instead.
func (*GuildFacility) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{9}
}

func (x *GuildFacility) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildFacility) GetMasterId() uint32 {
	if x != nil {
		return x.MasterId
	}
	return 0
}

func (x *GuildFacility) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GuildFacility) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GuildFacility) GetBuildupAt() string {
	if x != nil {
		return x.BuildupAt
	}
	return ""
}

type GuildFacilityList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GuildFacility       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildFacilityList) Reset() {
	*x = GuildFacilityList{}
	mi := &file_pmisc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildFacilityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildFacilityList) ProtoMessage() {}

func (x *GuildFacilityList) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildFacilityList.ProtoReflect.Descriptor instead.
func (*GuildFacilityList) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{10}
}

func (x *GuildFacilityList) GetList() []*GuildFacility {
	if x != nil {
		return x.List
	}
	return nil
}

type Guild struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Exp                     uint64                 `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Lupi                    uint64                 `protobuf:"varint,4,opt,name=lupi,proto3" json:"lupi,omitempty"`
	Wood                    uint64                 `protobuf:"varint,5,opt,name=wood,proto3" json:"wood,omitempty"`
	Stone                   uint64                 `protobuf:"varint,6,opt,name=stone,proto3" json:"stone,omitempty"`
	Iron                    uint64                 `protobuf:"varint,7,opt,name=iron,proto3" json:"iron,omitempty"`
	Crystal                 uint64                 `protobuf:"varint,8,opt,name=crystal,proto3" json:"crystal,omitempty"`
	FacilityItemCount       uint32                 `protobuf:"varint,9,opt,name=facility_item_count,json=facilityItemCount,proto3" json:"facility_item_count,omitempty"`
	Star                    uint64                 `protobuf:"varint,10,opt,name=star,proto3" json:"star,omitempty"`
	Moon                    uint64                 `protobuf:"varint,11,opt,name=moon,proto3" json:"moon,omitempty"`
	Description             string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	Message                 string                 `protobuf:"bytes,13,opt,name=message,proto3" json:"message,omitempty"`
	WorkingTimeType         uint32                 `protobuf:"varint,14,opt,name=working_time_type,json=workingTimeType,proto3" json:"working_time_type,omitempty"`
	JoinType                uint32                 `protobuf:"varint,15,opt,name=join_type,json=joinType,proto3" json:"join_type,omitempty"`
	PlayStyle               uint32                 `protobuf:"varint,16,opt,name=play_style,json=playStyle,proto3" json:"play_style,omitempty"`
	RecruitmentTarget       uint32                 `protobuf:"varint,17,opt,name=recruitment_target,json=recruitmentTarget,proto3" json:"recruitment_target,omitempty"`
	DungeonType             uint32                 `protobuf:"varint,18,opt,name=dungeon_type,json=dungeonType,proto3" json:"dungeon_type,omitempty"`
	DungeonResetType        uint32                 `protobuf:"varint,19,opt,name=dungeon_reset_type,json=dungeonResetType,proto3" json:"dungeon_reset_type,omitempty"`
	Symbol                  uint32                 `protobuf:"varint,20,opt,name=symbol,proto3" json:"symbol,omitempty"`
	SymbolFrame             uint32                 `protobuf:"varint,21,opt,name=symbol_frame,json=symbolFrame,proto3" json:"symbol_frame,omitempty"`
	SymbolFrameColor        uint32                 `protobuf:"varint,22,opt,name=symbol_frame_color,json=symbolFrameColor,proto3" json:"symbol_frame_color,omitempty"`
	RewardLv                uint32                 `protobuf:"varint,23,opt,name=reward_lv,json=rewardLv,proto3" json:"reward_lv,omitempty"`
	UpdateRewardLvDate      string                 `protobuf:"bytes,24,opt,name=update_reward_lv_date,json=updateRewardLvDate,proto3" json:"update_reward_lv_date,omitempty"`
	WarehouseGiftCount      uint32                 `protobuf:"varint,25,opt,name=warehouse_gift_count,json=warehouseGiftCount,proto3" json:"warehouse_gift_count,omitempty"`
	WarehouseGiftReceivedAt string                 `protobuf:"bytes,26,opt,name=warehouse_gift_received_at,json=warehouseGiftReceivedAt,proto3" json:"warehouse_gift_received_at,omitempty"`
	NameChangedAt           string                 `protobuf:"bytes,27,opt,name=name_changed_at,json=nameChangedAt,proto3" json:"name_changed_at,omitempty"`
	GvgPracticePenaltyType  uint32                 `protobuf:"varint,28,opt,name=gvg_practice_penalty_type,json=gvgPracticePenaltyType,proto3" json:"gvg_practice_penalty_type,omitempty"`
	GvgPracticeLimitAt      string                 `protobuf:"bytes,29,opt,name=gvg_practice_limit_at,json=gvgPracticeLimitAt,proto3" json:"gvg_practice_limit_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Guild) Reset() {
	*x = Guild{}
	mi := &file_pmisc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guild) ProtoMessage() {}

func (x *Guild) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guild.ProtoReflect.Descriptor instead.
func (*Guild) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{11}
}

func (x *Guild) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Guild) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Guild) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Guild) GetLupi() uint64 {
	if x != nil {
		return x.Lupi
	}
	return 0
}

func (x *Guild) GetWood() uint64 {
	if x != nil {
		return x.Wood
	}
	return 0
}

func (x *Guild) GetStone() uint64 {
	if x != nil {
		return x.Stone
	}
	return 0
}

func (x *Guild) GetIron() uint64 {
	if x != nil {
		return x.Iron
	}
	return 0
}

func (x *Guild) GetCrystal() uint64 {
	if x != nil {
		return x.Crystal
	}
	return 0
}

func (x *Guild) GetFacilityItemCount() uint32 {
	if x != nil {
		return x.FacilityItemCount
	}
	return 0
}

func (x *Guild) GetStar() uint64 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *Guild) GetMoon() uint64 {
	if x != nil {
		return x.Moon
	}
	return 0
}

func (x *Guild) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Guild) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Guild) GetWorkingTimeType() uint32 {
	if x != nil {
		return x.WorkingTimeType
	}
	return 0
}

func (x *Guild) GetJoinType() uint32 {
	if x != nil {
		return x.JoinType
	}
	return 0
}

func (x *Guild) GetPlayStyle() uint32 {
	if x != nil {
		return x.PlayStyle
	}
	return 0
}

func (x *Guild) GetRecruitmentTarget() uint32 {
	if x != nil {
		return x.RecruitmentTarget
	}
	return 0
}

func (x *Guild) GetDungeonType() uint32 {
	if x != nil {
		return x.DungeonType
	}
	return 0
}

func (x *Guild) GetDungeonResetType() uint32 {
	if x != nil {
		return x.DungeonResetType
	}
	return 0
}

func (x *Guild) GetSymbol() uint32 {
	if x != nil {
		return x.Symbol
	}
	return 0
}

func (x *Guild) GetSymbolFrame() uint32 {
	if x != nil {
		return x.SymbolFrame
	}
	return 0
}

func (x *Guild) GetSymbolFrameColor() uint32 {
	if x != nil {
		return x.SymbolFrameColor
	}
	return 0
}

func (x *Guild) GetRewardLv() uint32 {
	if x != nil {
		return x.RewardLv
	}
	return 0
}

func (x *Guild) GetUpdateRewardLvDate() string {
	if x != nil {
		return x.UpdateRewardLvDate
	}
	return ""
}

func (x *Guild) GetWarehouseGiftCount() uint32 {
	if x != nil {
		return x.WarehouseGiftCount
	}
	return 0
}

func (x *Guild) GetWarehouseGiftReceivedAt() string {
	if x != nil {
		return x.WarehouseGiftReceivedAt
	}
	return ""
}

func (x *Guild) GetNameChangedAt() string {
	if x != nil {
		return x.NameChangedAt
	}
	return ""
}

func (x *Guild) GetGvgPracticePenaltyType() uint32 {
	if x != nil {
		return x.GvgPracticePenaltyType
	}
	return 0
}

func (x *Guild) GetGvgPracticeLimitAt() string {
	if x != nil {
		return x.GvgPracticeLimitAt
	}
	return ""
}

type BattleMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Fever         uint32                 `protobuf:"varint,4,opt,name=fever,proto3" json:"fever,omitempty"`
	MercenaryId_1 uint64                 `protobuf:"varint,5,opt,name=mercenary_id_1,json=mercenaryId1,proto3" json:"mercenary_id_1,omitempty"`
	MercenaryId_2 uint64                 `protobuf:"varint,6,opt,name=mercenary_id_2,json=mercenaryId2,proto3" json:"mercenary_id_2,omitempty"`
	MercenaryId_3 uint64                 `protobuf:"varint,7,opt,name=mercenary_id_3,json=mercenaryId3,proto3" json:"mercenary_id_3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleMember) Reset() {
	*x = BattleMember{}
	mi := &file_pmisc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleMember) ProtoMessage() {}

func (x *BattleMember) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleMember.ProtoReflect.Descriptor instead.
func (*BattleMember) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{12}
}

func (x *BattleMember) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *BattleMember) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *BattleMember) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BattleMember) GetFever() uint32 {
	if x != nil {
		return x.Fever
	}
	return 0
}

func (x *BattleMember) GetMercenaryId_1() uint64 {
	if x != nil {
		return x.MercenaryId_1
	}
	return 0
}

func (x *BattleMember) GetMercenaryId_2() uint64 {
	if x != nil {
		return x.MercenaryId_2
	}
	return 0
}

func (x *BattleMember) GetMercenaryId_3() uint64 {
	if x != nil {
		return x.MercenaryId_3
	}
	return 0
}

type Block struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderPlayerId uint64                 `protobuf:"varint,1,opt,name=sender_player_id,json=senderPlayerId,proto3" json:"sender_player_id,omitempty"`
	TargetPlayerId uint64                 `protobuf:"varint,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_pmisc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{13}
}

func (x *Block) GetSenderPlayerId() uint64 {
	if x != nil {
		return x.SenderPlayerId
	}
	return 0
}

func (x *Block) GetTargetPlayerId() uint64 {
	if x != nil {
		return x.TargetPlayerId
	}
	return 0
}

type ConditionProgress struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlayerId         uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ConditionTypeId  uint32                 `protobuf:"varint,2,opt,name=condition_type_id,json=conditionTypeId,proto3" json:"condition_type_id,omitempty"`
	ConditionGroupId uint32                 `protobuf:"varint,3,opt,name=condition_group_id,json=conditionGroupId,proto3" json:"condition_group_id,omitempty"`
	Progress         uint64                 `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`
	DailyProgress    uint64                 `protobuf:"varint,5,opt,name=daily_progress,json=dailyProgress,proto3" json:"daily_progress,omitempty"`
	WeeklyProgress   uint64                 `protobuf:"varint,6,opt,name=weekly_progress,json=weeklyProgress,proto3" json:"weekly_progress,omitempty"`
	LastUpdate       string                 `protobuf:"bytes,7,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConditionProgress) Reset() {
	*x = ConditionProgress{}
	mi := &file_pmisc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionProgress) ProtoMessage() {}

func (x *ConditionProgress) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionProgress.ProtoReflect.Descriptor instead.
func (*ConditionProgress) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{14}
}

func (x *ConditionProgress) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ConditionProgress) GetConditionTypeId() uint32 {
	if x != nil {
		return x.ConditionTypeId
	}
	return 0
}

func (x *ConditionProgress) GetConditionGroupId() uint32 {
	if x != nil {
		return x.ConditionGroupId
	}
	return 0
}

func (x *ConditionProgress) GetProgress() uint64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ConditionProgress) GetDailyProgress() uint64 {
	if x != nil {
		return x.DailyProgress
	}
	return 0
}

func (x *ConditionProgress) GetWeeklyProgress() uint64 {
	if x != nil {
		return x.WeeklyProgress
	}
	return 0
}

func (x *ConditionProgress) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

type GuildBoard struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	GuildId             uint64                 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Seq                 uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Title               string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message             string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	IsGuildTop          uint32                 `protobuf:"varint,5,opt,name=is_guild_top,json=isGuildTop,proto3" json:"is_guild_top,omitempty"`
	IsGveTop            uint32                 `protobuf:"varint,6,opt,name=is_gve_top,json=isGveTop,proto3" json:"is_gve_top,omitempty"`
	IsGuildAnnouncement uint32                 `protobuf:"varint,7,opt,name=is_guild_announcement,json=isGuildAnnouncement,proto3" json:"is_guild_announcement,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GuildBoard) Reset() {
	*x = GuildBoard{}
	mi := &file_pmisc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildBoard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildBoard) ProtoMessage() {}

func (x *GuildBoard) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildBoard.ProtoReflect.Descriptor instead.
func (*GuildBoard) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{15}
}

func (x *GuildBoard) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildBoard) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GuildBoard) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GuildBoard) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GuildBoard) GetIsGuildTop() uint32 {
	if x != nil {
		return x.IsGuildTop
	}
	return 0
}

func (x *GuildBoard) GetIsGveTop() uint32 {
	if x != nil {
		return x.IsGveTop
	}
	return 0
}

func (x *GuildBoard) GetIsGuildAnnouncement() uint32 {
	if x != nil {
		return x.IsGuildAnnouncement
	}
	return 0
}

type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlayerId      uint64                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_pmisc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{16}
}

func (x *Sample) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sample) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Sample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ArenaSeason struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OpenDate      string                 `protobuf:"bytes,2,opt,name=open_date,json=openDate,proto3" json:"open_date,omitempty"`
	CloseDate     string                 `protobuf:"bytes,3,opt,name=close_date,json=closeDate,proto3" json:"close_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArenaSeason) Reset() {
	*x = ArenaSeason{}
	mi := &file_pmisc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArenaSeason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaSeason) ProtoMessage() {}

func (x *ArenaSeason) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaSeason.ProtoReflect.Descriptor instead.
func (*ArenaSeason) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{17}
}

func (x *ArenaSeason) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArenaSeason) GetOpenDate() string {
	if x != nil {
		return x.OpenDate
	}
	return ""
}

func (x *ArenaSeason) GetCloseDate() string {
	if x != nil {
		return x.CloseDate
	}
	return ""
}

type GuildDungeon struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GuildId          uint64                 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	GuildDungeonId   uint32                 `protobuf:"varint,2,opt,name=guild_dungeon_id,json=guildDungeonId,proto3" json:"guild_dungeon_id,omitempty"`
	RaidId           uint32                 `protobuf:"varint,3,opt,name=raid_id,json=raidId,proto3" json:"raid_id,omitempty"`
	ResetCount       uint32                 `protobuf:"varint,4,opt,name=reset_count,json=resetCount,proto3" json:"reset_count,omitempty"`
	LastClearStageId uint32                 `protobuf:"varint,5,opt,name=last_clear_stage_id,json=lastClearStageId,proto3" json:"last_clear_stage_id,omitempty"`
	StageStatus      uint32                 `protobuf:"varint,6,opt,name=stage_status,json=stageStatus,proto3" json:"stage_status,omitempty"`
	IsOnceCleared    uint32                 `protobuf:"varint,7,opt,name=is_once_cleared,json=isOnceCleared,proto3" json:"is_once_cleared,omitempty"`
	LastOpenAt       string                 `protobuf:"bytes,8,opt,name=last_open_at,json=lastOpenAt,proto3" json:"last_open_at,omitempty"`
	LastResetAt      string                 `protobuf:"bytes,9,opt,name=last_reset_at,json=lastResetAt,proto3" json:"last_reset_at,omitempty"`
	LastClearAt      string                 `protobuf:"bytes,10,opt,name=last_clear_at,json=lastClearAt,proto3" json:"last_clear_at,omitempty"`
	LastUpdateAt     string                 `protobuf:"bytes,11,opt,name=last_update_at,json=lastUpdateAt,proto3" json:"last_update_at,omitempty"`
	RaidEndAt        string                 `protobuf:"bytes,12,opt,name=raid_end_at,json=raidEndAt,proto3" json:"raid_end_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GuildDungeon) Reset() {
	*x = GuildDungeon{}
	mi := &file_pmisc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildDungeon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildDungeon) ProtoMessage() {}

func (x *GuildDungeon) ProtoReflect() protoreflect.Message {
	mi := &file_pmisc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildDungeon.ProtoReflect.Descriptor instead.
func (*GuildDungeon) Descriptor() ([]byte, []int) {
	return file_pmisc_proto_rawDescGZIP(), []int{18}
}

func (x *GuildDungeon) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildDungeon) GetGuildDungeonId() uint32 {
	if x != nil {
		return x.GuildDungeonId
	}
	return 0
}

func (x *GuildDungeon) GetRaidId() uint32 {
	if x != nil {
		return x.RaidId
	}
	return 0
}

func (x *GuildDungeon) GetResetCount() uint32 {
	if x != nil {
		return x.ResetCount
	}
	return 0
}

func (x *GuildDungeon) GetLastClearStageId() uint32 {
	if x != nil {
		return x.LastClearStageId
	}
	return 0
}

func (x *GuildDungeon) GetStageStatus() uint32 {
	if x != nil {
		return x.StageStatus
	}
	return 0
}

func (x *GuildDungeon) GetIsOnceCleared() uint32 {
	if x != nil {
		return x.IsOnceCleared
	}
	return 0
}

func (x *GuildDungeon) GetLastOpenAt() string {
	if x != nil {
		return x.LastOpenAt
	}
	return ""
}

func (x *GuildDungeon) GetLastResetAt() string {
	if x != nil {
		return x.LastResetAt
	}
	return ""
}

func (x *GuildDungeon) GetLastClearAt() string {
	if x != nil {
		return x.LastClearAt
	}
	return ""
}

func (x *GuildDungeon) GetLastUpdateAt() string {
	if x != nil {
		return x.LastUpdateAt
	}
	return ""
}

func (x *GuildDungeon) GetRaidEndAt() string {
	if x != nil {
		return x.RaidEndAt
	}
	return ""
}

var File_pmisc_proto protoreflect.FileDescriptor

const file_pmisc_proto_rawDesc = "" +
	"\n" +
	"\vpmisc.proto\x12\x05Pmisc\"\x1a\n" +
	"\x18GuildPersonalMissionList\"\x18\n" +
	"\x16GuildSharedMissionList\"\x1f\n" +
	"\x1dGuildSharedMissionRankingList\"\x83\x01\n" +
	"\rGuildDonation\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x04R\aguildId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x04R\bplayerId\x12\x12\n" +
	"\x04lupi\x18\x03 \x01(\rR\x04lupi\x12\x12\n" +
	"\x04star\x18\x04 \x01(\rR\x04star\x12\x12\n" +
	"\x04moon\x18\x05 \x01(\rR\x04moon\"\xe4\x05\n" +
	"\x0eGvgBattleField\x12&\n" +
	"\x0fbattle_field_id\x18\x01 \x01(\rR\rbattleFieldId\x12*\n" +
	"\x11start_battle_date\x18\x02 \x01(\tR\x0fstartBattleDate\x12\x1b\n" +
	"\tguild1_id\x18\x03 \x01(\x04R\bguild1Id\x12&\n" +
	"\x0fguild1_is_dummy\x18\x04 \x01(\rR\rguild1IsDummy\x12!\n" +
	"\fguild1_score\x18\x05 \x01(\x04R\vguild1Score\x12#\n" +
	"\rguild1_symbol\x18\x06 \x01(\rR\fguild1Symbol\x12.\n" +
	"\x13guild1_symbol_frame\x18\a \x01(\rR\x11guild1SymbolFrame\x129\n" +
	"\x19guild1_symbol_frame_color\x18\b \x01(\rR\x16guild1SymbolFrameColor\x12\x1b\n" +
	"\tguild2_id\x18\t \x01(\x04R\bguild2Id\x12&\n" +
	"\x0fguild2_is_dummy\x18\n" +
	" \x01(\rR\rguild2IsDummy\x12!\n" +
	"\fguild2_score\x18\v \x01(\x04R\vguild2Score\x12#\n" +
	"\rguild2_symbol\x18\f \x01(\rR\fguild2Symbol\x12.\n" +
	"\x13guild2_symbol_frame\x18\r \x01(\rR\x11guild2SymbolFrame\x129\n" +
	"\x19guild2_symbol_frame_color\x18\x0e \x01(\rR\x16guild2SymbolFrameColor\x12-\n" +
	"\x13pre_leader_guild_id\x18\x0f \x01(\x04R\x10preLeaderGuildId\x12&\n" +
	"\x0fwinner_guild_id\x18\x10 \x01(\x04R\rwinnerGuildId\x12\x1f\n" +
	"\vis_finished\x18\x11 \x01(\rR\n" +
	"isFinished\x12\x16\n" +
	"\x06reason\x18\x12 \x01(\rR\x06reason\"[\n" +
	"\tGuildItem\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x04R\aguildId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\"\x9a\x03\n" +
	"\x13GvgPracticeMatching\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x04R\aguildId\x12\x15\n" +
	"\x06gvg_id\x18\x02 \x01(\rR\x05gvgId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\rR\x06status\x12\x19\n" +
	"\bentry_at\x18\x04 \x01(\tR\aentryAt\x12\x0e\n" +
	"\x02lv\x18\x05 \x01(\rR\x02lv\x12\x1f\n" +
	"\vmatching_at\x18\x06 \x01(\tR\n" +
	"matchingAt\x12\x14\n" +
	"\x05power\x18\a \x01(\rR\x05power\x12!\n" +
	"\fmember_limit\x18\b \x01(\rR\vmemberLimit\x12\x1d\n" +
	"\n" +
	"match_time\x18\t \x01(\rR\tmatchTime\x12\x1a\n" +
	"\bpassword\x18\n" +
	" \x01(\tR\bpassword\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12\"\n" +
	"\ris_room_owner\x18\f \x01(\rR\visRoomOwner\x123\n" +
	"\x16gvg_practice_battle_id\x18\r \x01(\x04R\x13gvgPracticeBattleId\"\xfb\x05\n" +
	"\x11GvgPracticeBattle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x15\n" +
	"\x06gvg_id\x18\x02 \x01(\rR\x05gvgId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\rR\x06status\x12&\n" +
	"\x0fbattle_field_id\x18\x04 \x01(\rR\rbattleFieldId\x12*\n" +
	"\x11start_battle_date\x18\x05 \x01(\tR\x0fstartBattleDate\x12\x1b\n" +
	"\troom_type\x18\x06 \x01(\rR\broomType\x12\x14\n" +
	"\x05power\x18\a \x01(\rR\x05power\x12!\n" +
	"\fmember_limit\x18\b \x01(\rR\vmemberLimit\x12\x1d\n" +
	"\n" +
	"match_time\x18\t \x01(\rR\tmatchTime\x12\x1b\n" +
	"\tguild1_id\x18\n" +
	" \x01(\x04R\bguild1Id\x12!\n" +
	"\fguild1_score\x18\v \x01(\x04R\vguild1Score\x12#\n" +
	"\rguild1_symbol\x18\f \x01(\rR\fguild1Symbol\x12.\n" +
	"\x13guild1_symbol_frame\x18\r \x01(\rR\x11guild1SymbolFrame\x129\n" +
	"\x19guild1_symbol_frame_color\x18\x0e \x01(\rR\x16guild1SymbolFrameColor\x12\x1b\n" +
	"\tguild2_id\x18\x0f \x01(\x04R\bguild2Id\x12!\n" +
	"\fguild2_score\x18\x10 \x01(\x04R\vguild2Score\x12#\n" +
	"\rguild2_symbol\x18\x11 \x01(\rR\fguild2Symbol\x12.\n" +
	"\x13guild2_symbol_frame\x18\x12 \x01(\rR\x11guild2SymbolFrame\x129\n" +
	"\x19guild2_symbol_frame_color\x18\x13 \x01(\rR\x16guild2SymbolFrameColor\x12&\n" +
	"\x0fwinner_guild_id\x18\x14 \x01(\x04R\rwinnerGuildId\x12\x16\n" +
	"\x06reason\x18\x15 \x01(\rR\x06reason\"_\n" +
	"\x17GvgPracticeStopSchedule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\"\x94\x01\n" +
	"\rGuildFacility\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x04R\aguildId\x12\x1b\n" +
	"\tmaster_id\x18\x02 \x01(\rR\bmasterId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\rR\x05level\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"buildup_at\x18\x05 \x01(\tR\tbuildupAt\"=\n" +
	"\x11GuildFacilityList\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.Pmisc.GuildFacilityR\x04list\"\xe3\a\n" +
	"\x05Guild\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x04R\x03exp\x12\x12\n" +
	"\x04lupi\x18\x04 \x01(\x04R\x04lupi\x12\x12\n" +
	"\x04wood\x18\x05 \x01(\x04R\x04wood\x12\x14\n" +
	"\x05stone\x18\x06 \x01(\x04R\x05stone\x12\x12\n" +
	"\x04iron\x18\a \x01(\x04R\x04iron\x12\x18\n" +
	"\acrystal\x18\b \x01(\x04R\acrystal\x12.\n" +
	"\x13facility_item_count\x18\t \x01(\rR\x11facilityItemCount\x12\x12\n" +
	"\x04star\x18\n" +
	" \x01(\x04R\x04star\x12\x12\n" +
	"\x04moon\x18\v \x01(\x04R\x04moon\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12\x18\n" +
	"\amessage\x18\r \x01(\tR\amessage\x12*\n" +
	"\x11working_time_type\x18\x0e \x01(\rR\x0fworkingTimeType\x12\x1b\n" +
	"\tjoin_type\x18\x0f \x01(\rR\bjoinType\x12\x1d\n" +
	"\n" +
	"play_style\x18\x10 \x01(\rR\tplayStyle\x12-\n" +
	"\x12recruitment_target\x18\x11 \x01(\rR\x11recruitmentTarget\x12!\n" +
	"\fdungeon_type\x18\x12 \x01(\rR\vdungeonType\x12,\n" +
	"\x12dungeon_reset_type\x18\x13 \x01(\rR\x10dungeonResetType\x12\x16\n" +
	"\x06symbol\x18\x14 \x01(\rR\x06symbol\x12!\n" +
	"\fsymbol_frame\x18\x15 \x01(\rR\vsymbolFrame\x12,\n" +
	"\x12symbol_frame_color\x18\x16 \x01(\rR\x10symbolFrameColor\x12\x1b\n" +
	"\treward_lv\x18\x17 \x01(\rR\brewardLv\x121\n" +
	"\x15update_reward_lv_date\x18\x18 \x01(\tR\x12updateRewardLvDate\x120\n" +
	"\x14warehouse_gift_count\x18\x19 \x01(\rR\x12warehouseGiftCount\x12;\n" +
	"\x1awarehouse_gift_received_at\x18\x1a \x01(\tR\x17warehouseGiftReceivedAt\x12&\n" +
	"\x0fname_changed_at\x18\x1b \x01(\tR\rnameChangedAt\x129\n" +
	"\x19gvg_practice_penalty_type\x18\x1c \x01(\rR\x16gvgPracticePenaltyType\x121\n" +
	"\x15gvg_practice_limit_at\x18\x1d \x01(\tR\x12gvgPracticeLimitAt\"\xe4\x01\n" +
	"\fBattleMember\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05fever\x18\x04 \x01(\rR\x05fever\x12$\n" +
	"\x0emercenary_id_1\x18\x05 \x01(\x04R\fmercenaryId1\x12$\n" +
	"\x0emercenary_id_2\x18\x06 \x01(\x04R\fmercenaryId2\x12$\n" +
	"\x0emercenary_id_3\x18\a \x01(\x04R\fmercenaryId3\"[\n" +
	"\x05Block\x12(\n" +
	"\x10sender_player_id\x18\x01 \x01(\x04R\x0esenderPlayerId\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\x04R\x0etargetPlayerId\"\x97\x02\n" +
	"\x11ConditionProgress\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12*\n" +
	"\x11condition_type_id\x18\x02 \x01(\rR\x0fconditionTypeId\x12,\n" +
	"\x12condition_group_id\x18\x03 \x01(\rR\x10conditionGroupId\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x04R\bprogress\x12%\n" +
	"\x0edaily_progress\x18\x05 \x01(\x04R\rdailyProgress\x12'\n" +
	"\x0fweekly_progress\x18\x06 \x01(\x04R\x0eweeklyProgress\x12\x1f\n" +
	"\vlast_update\x18\a \x01(\tR\n" +
	"lastUpdate\"\xdd\x01\n" +
	"\n" +
	"GuildBoard\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x04R\aguildId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12 \n" +
	"\fis_guild_top\x18\x05 \x01(\rR\n" +
	"isGuildTop\x12\x1c\n" +
	"\n" +
	"is_gve_top\x18\x06 \x01(\rR\bisGveTop\x122\n" +
	"\x15is_guild_announcement\x18\a \x01(\rR\x13isGuildAnnouncement\"I\n" +
	"\x06Sample\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x04R\bplayerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"Y\n" +
	"\vArenaSeason\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\topen_date\x18\x02 \x01(\tR\bopenDate\x12\x1d\n" +
	"\n" +
	"close_date\x18\x03 \x01(\tR\tcloseDate\"\xb7\x03\n" +
	"\fGuildDungeon\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x04R\aguildId\x12(\n" +
	"\x10guild_dungeon_id\x18\x02 \x01(\rR\x0eguildDungeonId\x12\x17\n" +
	"\araid_id\x18\x03 \x01(\rR\x06raidId\x12\x1f\n" +
	"\vreset_count\x18\x04 \x01(\rR\n" +
	"resetCount\x12-\n" +
	"\x13last_clear_stage_id\x18\x05 \x01(\rR\x10lastClearStageId\x12!\n" +
	"\fstage_status\x18\x06 \x01(\rR\vstageStatus\x12&\n" +
	"\x0fis_once_cleared\x18\a \x01(\rR\risOnceCleared\x12 \n" +
	"\flast_open_at\x18\b \x01(\tR\n" +
	"lastOpenAt\x12\"\n" +
	"\rlast_reset_at\x18\t \x01(\tR\vlastResetAt\x12\"\n" +
	"\rlast_clear_at\x18\n" +
	" \x01(\tR\vlastClearAt\x12$\n" +
	"\x0elast_update_at\x18\v \x01(\tR\flastUpdateAt\x12\x1e\n" +
	"\vraid_end_at\x18\f \x01(\tR\traidEndAtB+Z)example.com/brave-revival/src/proto/pmiscb\x06proto3"

var (
	file_pmisc_proto_rawDescOnce sync.Once
	file_pmisc_proto_rawDescData []byte
)

func file_pmisc_proto_rawDescGZIP() []byte {
	file_pmisc_proto_rawDescOnce.Do(func() {
		file_pmisc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pmisc_proto_rawDesc), len(file_pmisc_proto_rawDesc)))
	})
	return file_pmisc_proto_rawDescData
}

var file_pmisc_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pmisc_proto_goTypes = []any{
	(*GuildPersonalMissionList)(nil),      // 0: Pmisc.GuildPersonalMissionList
	(*GuildSharedMissionList)(nil),        // 1: Pmisc.GuildSharedMissionList
	(*GuildSharedMissionRankingList)(nil), // 2: Pmisc.GuildSharedMissionRankingList
	(*GuildDonation)(nil),                 // 3: Pmisc.GuildDonation
	(*GvgBattleField)(nil),                // 4: Pmisc.GvgBattleField
	(*GuildItem)(nil),                     // 5: Pmisc.GuildItem
	(*GvgPracticeMatching)(nil),           // 6: Pmisc.GvgPracticeMatching
	(*GvgPracticeBattle)(nil),             // 7: Pmisc.GvgPracticeBattle
	(*GvgPracticeStopSchedule)(nil),       // 8: Pmisc.GvgPracticeStopSchedule
	(*GuildFacility)(nil),                 // 9: Pmisc.GuildFacility
	(*GuildFacilityList)(nil),             // 10: Pmisc.GuildFacilityList
	(*Guild)(nil),                         // 11: Pmisc.Guild
	(*BattleMember)(nil),                  // 12: Pmisc.BattleMember
	(*Block)(nil),                         // 13: Pmisc.Block
	(*ConditionProgress)(nil),             // 14: Pmisc.ConditionProgress
	(*GuildBoard)(nil),                    // 15: Pmisc.GuildBoard
	(*Sample)(nil),                        // 16: Pmisc.Sample
	(*ArenaSeason)(nil),                   // 17: Pmisc.ArenaSeason
	(*GuildDungeon)(nil),                  // 18: Pmisc.GuildDungeon
}
var file_pmisc_proto_depIdxs = []int32{
	9, // 0: Pmisc.GuildFacilityList.list:type_name -> Pmisc.GuildFacility
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pmisc_proto_init() }
func file_pmisc_proto_init() {
	if File_pmisc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pmisc_proto_rawDesc), len(file_pmisc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pmisc_proto_goTypes,
		DependencyIndexes: file_pmisc_proto_depIdxs,
		MessageInfos:      file_pmisc_proto_msgTypes,
	}.Build()
	File_pmisc_proto = out.File
	file_pmisc_proto_goTypes = nil
	file_pmisc_proto_depIdxs = nil
}
