// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: pcommon.proto

package pcommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Level         int64                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Detail        string                 `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	Ts            int64                  `protobuf:"varint,6,opt,name=ts,proto3" json:"ts,omitempty"`
	StoreUrl      string                 `protobuf:"bytes,7,opt,name=store_url,json=storeUrl,proto3" json:"store_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_pcommon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pcommon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pcommon_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Error) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Error) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Error) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Error) GetStoreUrl() string {
	if x != nil {
		return x.StoreUrl
	}
	return ""
}

var File_pcommon_proto protoreflect.FileDescriptor

const file_pcommon_proto_rawDesc = "" +
	"\n" +
	"\rpcommon.proto\x12\aPcommon\"\xa2\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x03R\x05level\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\x12\x0e\n" +
	"\x02ts\x18\x06 \x01(\x03R\x02ts\x12\x1b\n" +
	"\tstore_url\x18\a \x01(\tR\bstoreUrlB-Z+example.com/brave-revival/src/proto/pcommonb\x06proto3"

var (
	file_pcommon_proto_rawDescOnce sync.Once
	file_pcommon_proto_rawDescData []byte
)

func file_pcommon_proto_rawDescGZIP() []byte {
	file_pcommon_proto_rawDescOnce.Do(func() {
		file_pcommon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pcommon_proto_rawDesc), len(file_pcommon_proto_rawDesc)))
	})
	return file_pcommon_proto_rawDescData
}

var file_pcommon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pcommon_proto_goTypes = []any{
	(*Error)(nil), // 0: Pcommon.Error
}
var file_pcommon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pcommon_proto_init() }
func file_pcommon_proto_init() {
	if File_pcommon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pcommon_proto_rawDesc), len(file_pcommon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pcommon_proto_goTypes,
		DependencyIndexes: file_pcommon_proto_depIdxs,
		MessageInfos:      file_pcommon_proto_msgTypes,
	}.Build()
	File_pcommon_proto = out.File
	file_pcommon_proto_goTypes = nil
	file_pcommon_proto_depIdxs = nil
}
