// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: crowparty.proto

package crowparty

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrowParty_Connect_FullMethodName       = "/CrowParty.CrowParty/Connect"
	CrowParty_IsPartyMember_FullMethodName = "/CrowParty.CrowParty/IsPartyMember"
	CrowParty_SearchRooms_FullMethodName   = "/CrowParty.CrowParty/SearchRooms"
)

// CrowPartyClient is the client API for CrowParty service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrowPartyClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PartyRequest, PartyResponse], error)
	IsPartyMember(ctx context.Context, in *IsPartyMemberRequest, opts ...grpc.CallOption) (*IsPartyMemberResponse, error)
	SearchRooms(ctx context.Context, in *PartySearchRequest, opts ...grpc.CallOption) (*PartySearchResponse, error)
}

type crowPartyClient struct {
	cc grpc.ClientConnInterface
}

func NewCrowPartyClient(cc grpc.ClientConnInterface) CrowPartyClient {
	return &crowPartyClient{cc}
}

func (c *crowPartyClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PartyRequest, PartyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CrowParty_ServiceDesc.Streams[0], CrowParty_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PartyRequest, PartyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CrowParty_ConnectClient = grpc.BidiStreamingClient[PartyRequest, PartyResponse]

func (c *crowPartyClient) IsPartyMember(ctx context.Context, in *IsPartyMemberRequest, opts ...grpc.CallOption) (*IsPartyMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsPartyMemberResponse)
	err := c.cc.Invoke(ctx, CrowParty_IsPartyMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crowPartyClient) SearchRooms(ctx context.Context, in *PartySearchRequest, opts ...grpc.CallOption) (*PartySearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartySearchResponse)
	err := c.cc.Invoke(ctx, CrowParty_SearchRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrowPartyServer is the server API for CrowParty service.
// All implementations must embed UnimplementedCrowPartyServer
// for forward compatibility.
type CrowPartyServer interface {
	Connect(grpc.BidiStreamingServer[PartyRequest, PartyResponse]) error
	IsPartyMember(context.Context, *IsPartyMemberRequest) (*IsPartyMemberResponse, error)
	SearchRooms(context.Context, *PartySearchRequest) (*PartySearchResponse, error)
	mustEmbedUnimplementedCrowPartyServer()
}

// UnimplementedCrowPartyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrowPartyServer struct{}

func (UnimplementedCrowPartyServer) Connect(grpc.BidiStreamingServer[PartyRequest, PartyResponse]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedCrowPartyServer) IsPartyMember(context.Context, *IsPartyMemberRequest) (*IsPartyMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsPartyMember not implemented")
}
func (UnimplementedCrowPartyServer) SearchRooms(context.Context, *PartySearchRequest) (*PartySearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchRooms not implemented")
}
func (UnimplementedCrowPartyServer) mustEmbedUnimplementedCrowPartyServer() {}
func (UnimplementedCrowPartyServer) testEmbeddedByValue()                   {}

// UnsafeCrowPartyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrowPartyServer will
// result in compilation errors.
type UnsafeCrowPartyServer interface {
	mustEmbedUnimplementedCrowPartyServer()
}

func RegisterCrowPartyServer(s grpc.ServiceRegistrar, srv CrowPartyServer) {
	// If the following call panics, it indicates UnimplementedCrowPartyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrowParty_ServiceDesc, srv)
}

func _CrowParty_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CrowPartyServer).Connect(&grpc.GenericServerStream[PartyRequest, PartyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CrowParty_ConnectServer = grpc.BidiStreamingServer[PartyRequest, PartyResponse]

func _CrowParty_IsPartyMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsPartyMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrowPartyServer).IsPartyMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrowParty_IsPartyMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrowPartyServer).IsPartyMember(ctx, req.(*IsPartyMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrowParty_SearchRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartySearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrowPartyServer).SearchRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrowParty_SearchRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrowPartyServer).SearchRooms(ctx, req.(*PartySearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrowParty_ServiceDesc is the grpc.ServiceDesc for CrowParty service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrowParty_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CrowParty.CrowParty",
	HandlerType: (*CrowPartyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsPartyMember",
			Handler:    _CrowParty_IsPartyMember_Handler,
		},
		{
			MethodName: "SearchRooms",
			Handler:    _CrowParty_SearchRooms_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _CrowParty_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "crowparty.proto",
}
