// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: crowparty.proto

package crowparty

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinType_Enum int32

const (
	JoinType_CREATE  JoinType_Enum = 0
	JoinType_JOIN    JoinType_Enum = 1
	JoinType_ACCEPT  JoinType_Enum = 2
	JoinType_REJOIN  JoinType_Enum = 3
	JoinType_AUTO    JoinType_Enum = 4
	JoinType_INTRUDE JoinType_Enum = 5
	JoinType_RESCUE  JoinType_Enum = 6
)

// Enum value maps for JoinType_Enum.
var (
	JoinType_Enum_name = map[int32]string{
		0: "CREATE",
		1: "JOIN",
		2: "ACCEPT",
		3: "REJOIN",
		4: "AUTO",
		5: "INTRUDE",
		6: "RESCUE",
	}
	JoinType_Enum_value = map[string]int32{
		"CREATE":  0,
		"JOIN":    1,
		"ACCEPT":  2,
		"REJOIN":  3,
		"AUTO":    4,
		"INTRUDE": 5,
		"RESCUE":  6,
	}
)

func (x JoinType_Enum) Enum() *JoinType_Enum {
	p := new(JoinType_Enum)
	*p = x
	return p
}

func (x JoinType_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinType_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_crowparty_proto_enumTypes[0].Descriptor()
}

func (JoinType_Enum) Type() protoreflect.EnumType {
	return &file_crowparty_proto_enumTypes[0]
}

func (x JoinType_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinType_Enum.Descriptor instead.
func (JoinType_Enum) EnumDescriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{21, 0}
}

type RoomVisibility_Enum int32

const (
	RoomVisibility_PUBLIC  RoomVisibility_Enum = 0
	RoomVisibility_GUILD   RoomVisibility_Enum = 1
	RoomVisibility_PRIVATE RoomVisibility_Enum = 2
)

// Enum value maps for RoomVisibility_Enum.
var (
	RoomVisibility_Enum_name = map[int32]string{
		0: "PUBLIC",
		1: "GUILD",
		2: "PRIVATE",
	}
	RoomVisibility_Enum_value = map[string]int32{
		"PUBLIC":  0,
		"GUILD":   1,
		"PRIVATE": 2,
	}
)

func (x RoomVisibility_Enum) Enum() *RoomVisibility_Enum {
	p := new(RoomVisibility_Enum)
	*p = x
	return p
}

func (x RoomVisibility_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomVisibility_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_crowparty_proto_enumTypes[1].Descriptor()
}

func (RoomVisibility_Enum) Type() protoreflect.EnumType {
	return &file_crowparty_proto_enumTypes[1]
}

func (x RoomVisibility_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomVisibility_Enum.Descriptor instead.
func (RoomVisibility_Enum) EnumDescriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{22, 0}
}

type ReceiverGroup_Enum int32

const (
	ReceiverGroup_OTHERS ReceiverGroup_Enum = 0
	ReceiverGroup_ALL    ReceiverGroup_Enum = 1
	ReceiverGroup_LEADER ReceiverGroup_Enum = 2
)

// Enum value maps for ReceiverGroup_Enum.
var (
	ReceiverGroup_Enum_name = map[int32]string{
		0: "OTHERS",
		1: "ALL",
		2: "LEADER",
	}
	ReceiverGroup_Enum_value = map[string]int32{
		"OTHERS": 0,
		"ALL":    1,
		"LEADER": 2,
	}
)

func (x ReceiverGroup_Enum) Enum() *ReceiverGroup_Enum {
	p := new(ReceiverGroup_Enum)
	*p = x
	return p
}

func (x ReceiverGroup_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReceiverGroup_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_crowparty_proto_enumTypes[2].Descriptor()
}

func (ReceiverGroup_Enum) Type() protoreflect.EnumType {
	return &file_crowparty_proto_enumTypes[2]
}

func (x ReceiverGroup_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReceiverGroup_Enum.Descriptor instead.
func (ReceiverGroup_Enum) EnumDescriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{23, 0}
}

type ErrorCode_Enum int32

const (
	ErrorCode_UNKNOWN                       ErrorCode_Enum = 0
	ErrorCode_ROOM_ALREADY_EXISTS           ErrorCode_Enum = 1
	ErrorCode_ALREADY_IN_ROOM               ErrorCode_Enum = 2
	ErrorCode_NOT_IN_ROOM                   ErrorCode_Enum = 3
	ErrorCode_ROOM_NOT_FOUND                ErrorCode_Enum = 4
	ErrorCode_ROOM_CONDITION                ErrorCode_Enum = 5
	ErrorCode_ROOM_IS_FULL                  ErrorCode_Enum = 6
	ErrorCode_ROOM_REQUEST_NOT_FOUND        ErrorCode_Enum = 7
	ErrorCode_ROOM_IDMISMATCH               ErrorCode_Enum = 8
	ErrorCode_NOT_LEADER                    ErrorCode_Enum = 9
	ErrorCode_PLAYER_NOT_FOUND              ErrorCode_Enum = 10
	ErrorCode_PLAYER_IS_INACTIVE            ErrorCode_Enum = 11
	ErrorCode_AUTO_MATCHING_ALREADY_STARTED ErrorCode_Enum = 12
	ErrorCode_AUTO_MATCHING_NOT_STARTED     ErrorCode_Enum = 13
	ErrorCode_AUTO_MATCHING_RUNNNING        ErrorCode_Enum = 14
	ErrorCode_AUTO_MATCHING_ROOM            ErrorCode_Enum = 15
	ErrorCode_NOT_AUTO_MATCHING_ROOM        ErrorCode_Enum = 16
	ErrorCode_IN_BATTLE                     ErrorCode_Enum = 17
)

// Enum value maps for ErrorCode_Enum.
var (
	ErrorCode_Enum_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "ROOM_ALREADY_EXISTS",
		2:  "ALREADY_IN_ROOM",
		3:  "NOT_IN_ROOM",
		4:  "ROOM_NOT_FOUND",
		5:  "ROOM_CONDITION",
		6:  "ROOM_IS_FULL",
		7:  "ROOM_REQUEST_NOT_FOUND",
		8:  "ROOM_IDMISMATCH",
		9:  "NOT_LEADER",
		10: "PLAYER_NOT_FOUND",
		11: "PLAYER_IS_INACTIVE",
		12: "AUTO_MATCHING_ALREADY_STARTED",
		13: "AUTO_MATCHING_NOT_STARTED",
		14: "AUTO_MATCHING_RUNNNING",
		15: "AUTO_MATCHING_ROOM",
		16: "NOT_AUTO_MATCHING_ROOM",
		17: "IN_BATTLE",
	}
	ErrorCode_Enum_value = map[string]int32{
		"UNKNOWN":                       0,
		"ROOM_ALREADY_EXISTS":           1,
		"ALREADY_IN_ROOM":               2,
		"NOT_IN_ROOM":                   3,
		"ROOM_NOT_FOUND":                4,
		"ROOM_CONDITION":                5,
		"ROOM_IS_FULL":                  6,
		"ROOM_REQUEST_NOT_FOUND":        7,
		"ROOM_IDMISMATCH":               8,
		"NOT_LEADER":                    9,
		"PLAYER_NOT_FOUND":              10,
		"PLAYER_IS_INACTIVE":            11,
		"AUTO_MATCHING_ALREADY_STARTED": 12,
		"AUTO_MATCHING_NOT_STARTED":     13,
		"AUTO_MATCHING_RUNNNING":        14,
		"AUTO_MATCHING_ROOM":            15,
		"NOT_AUTO_MATCHING_ROOM":        16,
		"IN_BATTLE":                     17,
	}
)

func (x ErrorCode_Enum) Enum() *ErrorCode_Enum {
	p := new(ErrorCode_Enum)
	*p = x
	return p
}

func (x ErrorCode_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_crowparty_proto_enumTypes[3].Descriptor()
}

func (ErrorCode_Enum) Type() protoreflect.EnumType {
	return &file_crowparty_proto_enumTypes[3]
}

func (x ErrorCode_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode_Enum.Descriptor instead.
func (ErrorCode_Enum) EnumDescriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{24, 0}
}

type ErrorLevel_Enum int32

const (
	ErrorLevel_ERROR ErrorLevel_Enum = 0
	ErrorLevel_WARN  ErrorLevel_Enum = 1
)

// Enum value maps for ErrorLevel_Enum.
var (
	ErrorLevel_Enum_name = map[int32]string{
		0: "ERROR",
		1: "WARN",
	}
	ErrorLevel_Enum_value = map[string]int32{
		"ERROR": 0,
		"WARN":  1,
	}
)

func (x ErrorLevel_Enum) Enum() *ErrorLevel_Enum {
	p := new(ErrorLevel_Enum)
	*p = x
	return p
}

func (x ErrorLevel_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorLevel_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_crowparty_proto_enumTypes[4].Descriptor()
}

func (ErrorLevel_Enum) Type() protoreflect.EnumType {
	return &file_crowparty_proto_enumTypes[4]
}

func (x ErrorLevel_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorLevel_Enum.Descriptor instead.
func (ErrorLevel_Enum) EnumDescriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{25, 0}
}

type PartyRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId int32                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*PartyRequest_ResumeRoom
	//	*PartyRequest_ApplyRoomRequest
	//	*PartyRequest_CancelRoomRequest
	//	*PartyRequest_AcceptRoomRequest
	//	*PartyRequest_RejectRoomRequest
	//	*PartyRequest_JoinRoom
	//	*PartyRequest_LeaveRoom
	//	*PartyRequest_KickRoom
	//	*PartyRequest_DisbandRoom
	//	*PartyRequest_ChangeLeader
	//	*PartyRequest_ChangeRoomProperty
	//	*PartyRequest_ChangePlayerProperty
	//	*PartyRequest_AutoMatchingStart
	//	*PartyRequest_AutoMatchingStartStage
	//	*PartyRequest_AutoMatchingCancelStage
	//	*PartyRequest_AutoMatchingCancelAll
	//	*PartyRequest_AutoMatchingRoomBreak
	//	*PartyRequest_InviteRoom
	//	*PartyRequest_RaiseEvent
	Request       isPartyRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyRequest) Reset() {
	*x = PartyRequest{}
	mi := &file_crowparty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyRequest) ProtoMessage() {}

func (x *PartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyRequest.ProtoReflect.Descriptor instead.
func (*PartyRequest) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{0}
}

func (x *PartyRequest) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *PartyRequest) GetRequest() isPartyRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *PartyRequest) GetResumeRoom() *ResumeRoom {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_ResumeRoom); ok {
			return x.ResumeRoom
		}
	}
	return nil
}

func (x *PartyRequest) GetApplyRoomRequest() *JoinRoom {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_ApplyRoomRequest); ok {
			return x.ApplyRoomRequest
		}
	}
	return nil
}

func (x *PartyRequest) GetCancelRoomRequest() *RoomRequest {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_CancelRoomRequest); ok {
			return x.CancelRoomRequest
		}
	}
	return nil
}

func (x *PartyRequest) GetAcceptRoomRequest() uint64 {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_AcceptRoomRequest); ok {
			return x.AcceptRoomRequest
		}
	}
	return 0
}

func (x *PartyRequest) GetRejectRoomRequest() uint64 {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_RejectRoomRequest); ok {
			return x.RejectRoomRequest
		}
	}
	return 0
}

func (x *PartyRequest) GetJoinRoom() *JoinRoom {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *PartyRequest) GetLeaveRoom() bool {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_LeaveRoom); ok {
			return x.LeaveRoom
		}
	}
	return false
}

func (x *PartyRequest) GetKickRoom() uint64 {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_KickRoom); ok {
			return x.KickRoom
		}
	}
	return 0
}

func (x *PartyRequest) GetDisbandRoom() bool {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_DisbandRoom); ok {
			return x.DisbandRoom
		}
	}
	return false
}

func (x *PartyRequest) GetChangeLeader() uint64 {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_ChangeLeader); ok {
			return x.ChangeLeader
		}
	}
	return 0
}

func (x *PartyRequest) GetChangeRoomProperty() *CustomProperty {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_ChangeRoomProperty); ok {
			return x.ChangeRoomProperty
		}
	}
	return nil
}

func (x *PartyRequest) GetChangePlayerProperty() *CustomProperty {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_ChangePlayerProperty); ok {
			return x.ChangePlayerProperty
		}
	}
	return nil
}

func (x *PartyRequest) GetAutoMatchingStart() *AutoMatchingStart {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_AutoMatchingStart); ok {
			return x.AutoMatchingStart
		}
	}
	return nil
}

func (x *PartyRequest) GetAutoMatchingStartStage() *AutoMatchingStage {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_AutoMatchingStartStage); ok {
			return x.AutoMatchingStartStage
		}
	}
	return nil
}

func (x *PartyRequest) GetAutoMatchingCancelStage() *AutoMatchingStage {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_AutoMatchingCancelStage); ok {
			return x.AutoMatchingCancelStage
		}
	}
	return nil
}

func (x *PartyRequest) GetAutoMatchingCancelAll() uint64 {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_AutoMatchingCancelAll); ok {
			return x.AutoMatchingCancelAll
		}
	}
	return 0
}

func (x *PartyRequest) GetAutoMatchingRoomBreak() bool {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_AutoMatchingRoomBreak); ok {
			return x.AutoMatchingRoomBreak
		}
	}
	return false
}

func (x *PartyRequest) GetInviteRoom() *InviteRoom {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_InviteRoom); ok {
			return x.InviteRoom
		}
	}
	return nil
}

func (x *PartyRequest) GetRaiseEvent() *RaiseEvent {
	if x != nil {
		if x, ok := x.Request.(*PartyRequest_RaiseEvent); ok {
			return x.RaiseEvent
		}
	}
	return nil
}

type isPartyRequest_Request interface {
	isPartyRequest_Request()
}

type PartyRequest_ResumeRoom struct {
	ResumeRoom *ResumeRoom `protobuf:"bytes,2,opt,name=resume_room,json=resumeRoom,proto3,oneof"`
}

type PartyRequest_ApplyRoomRequest struct {
	ApplyRoomRequest *JoinRoom `protobuf:"bytes,3,opt,name=apply_room_request,json=applyRoomRequest,proto3,oneof"`
}

type PartyRequest_CancelRoomRequest struct {
	CancelRoomRequest *RoomRequest `protobuf:"bytes,4,opt,name=cancel_room_request,json=cancelRoomRequest,proto3,oneof"`
}

type PartyRequest_AcceptRoomRequest struct {
	AcceptRoomRequest uint64 `protobuf:"varint,5,opt,name=accept_room_request,json=acceptRoomRequest,proto3,oneof"`
}

type PartyRequest_RejectRoomRequest struct {
	RejectRoomRequest uint64 `protobuf:"varint,6,opt,name=reject_room_request,json=rejectRoomRequest,proto3,oneof"`
}

type PartyRequest_JoinRoom struct {
	JoinRoom *JoinRoom `protobuf:"bytes,7,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type PartyRequest_LeaveRoom struct {
	LeaveRoom bool `protobuf:"varint,8,opt,name=leave_room,json=leaveRoom,proto3,oneof"`
}

type PartyRequest_KickRoom struct {
	KickRoom uint64 `protobuf:"varint,9,opt,name=kick_room,json=kickRoom,proto3,oneof"`
}

type PartyRequest_DisbandRoom struct {
	DisbandRoom bool `protobuf:"varint,10,opt,name=disband_room,json=disbandRoom,proto3,oneof"`
}

type PartyRequest_ChangeLeader struct {
	ChangeLeader uint64 `protobuf:"varint,11,opt,name=change_leader,json=changeLeader,proto3,oneof"`
}

type PartyRequest_ChangeRoomProperty struct {
	ChangeRoomProperty *CustomProperty `protobuf:"bytes,12,opt,name=change_room_property,json=changeRoomProperty,proto3,oneof"`
}

type PartyRequest_ChangePlayerProperty struct {
	ChangePlayerProperty *CustomProperty `protobuf:"bytes,13,opt,name=change_player_property,json=changePlayerProperty,proto3,oneof"`
}

type PartyRequest_AutoMatchingStart struct {
	AutoMatchingStart *AutoMatchingStart `protobuf:"bytes,14,opt,name=auto_matching_start,json=autoMatchingStart,proto3,oneof"`
}

type PartyRequest_AutoMatchingStartStage struct {
	AutoMatchingStartStage *AutoMatchingStage `protobuf:"bytes,15,opt,name=auto_matching_start_stage,json=autoMatchingStartStage,proto3,oneof"`
}

type PartyRequest_AutoMatchingCancelStage struct {
	AutoMatchingCancelStage *AutoMatchingStage `protobuf:"bytes,16,opt,name=auto_matching_cancel_stage,json=autoMatchingCancelStage,proto3,oneof"`
}

type PartyRequest_AutoMatchingCancelAll struct {
	AutoMatchingCancelAll uint64 `protobuf:"varint,17,opt,name=auto_matching_cancel_all,json=autoMatchingCancelAll,proto3,oneof"`
}

type PartyRequest_AutoMatchingRoomBreak struct {
	AutoMatchingRoomBreak bool `protobuf:"varint,18,opt,name=auto_matching_room_break,json=autoMatchingRoomBreak,proto3,oneof"`
}

type PartyRequest_InviteRoom struct {
	InviteRoom *InviteRoom `protobuf:"bytes,19,opt,name=invite_room,json=inviteRoom,proto3,oneof"`
}

type PartyRequest_RaiseEvent struct {
	RaiseEvent *RaiseEvent `protobuf:"bytes,20,opt,name=raise_event,json=raiseEvent,proto3,oneof"`
}

func (*PartyRequest_ResumeRoom) isPartyRequest_Request() {}

func (*PartyRequest_ApplyRoomRequest) isPartyRequest_Request() {}

func (*PartyRequest_CancelRoomRequest) isPartyRequest_Request() {}

func (*PartyRequest_AcceptRoomRequest) isPartyRequest_Request() {}

func (*PartyRequest_RejectRoomRequest) isPartyRequest_Request() {}

func (*PartyRequest_JoinRoom) isPartyRequest_Request() {}

func (*PartyRequest_LeaveRoom) isPartyRequest_Request() {}

func (*PartyRequest_KickRoom) isPartyRequest_Request() {}

func (*PartyRequest_DisbandRoom) isPartyRequest_Request() {}

func (*PartyRequest_ChangeLeader) isPartyRequest_Request() {}

func (*PartyRequest_ChangeRoomProperty) isPartyRequest_Request() {}

func (*PartyRequest_ChangePlayerProperty) isPartyRequest_Request() {}

func (*PartyRequest_AutoMatchingStart) isPartyRequest_Request() {}

func (*PartyRequest_AutoMatchingStartStage) isPartyRequest_Request() {}

func (*PartyRequest_AutoMatchingCancelStage) isPartyRequest_Request() {}

func (*PartyRequest_AutoMatchingCancelAll) isPartyRequest_Request() {}

func (*PartyRequest_AutoMatchingRoomBreak) isPartyRequest_Request() {}

func (*PartyRequest_InviteRoom) isPartyRequest_Request() {}

func (*PartyRequest_RaiseEvent) isPartyRequest_Request() {}

type PartyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      int32                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderPlayerId uint64                 `protobuf:"varint,2,opt,name=sender_player_id,json=senderPlayerId,proto3" json:"sender_player_id,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*PartyResponse_Error
	//	*PartyResponse_JoinRoom
	//	*PartyResponse_DisbandRoom
	//	*PartyResponse_ChangeLeader
	//	*PartyResponse_ChangeRoomProperty
	//	*PartyResponse_ApplyRoomRequest
	//	*PartyResponse_CancelRoomRequest
	//	*PartyResponse_AcceptRoomRequest
	//	*PartyResponse_RejectRoomRequest
	//	*PartyResponse_JoinPlayer
	//	*PartyResponse_LeavePlayer
	//	*PartyResponse_KickPlayer
	//	*PartyResponse_ChangePlayerProperty
	//	*PartyResponse_Kill
	//	*PartyResponse_AutoMatchingStartStage
	//	*PartyResponse_AutoMatchingCancelStage
	//	*PartyResponse_AutoMatchingCancelAll
	//	*PartyResponse_AutoMatchingSuccess
	//	*PartyResponse_InviteRoom
	//	*PartyResponse_RaiseEvent
	Response      isPartyResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyResponse) Reset() {
	*x = PartyResponse{}
	mi := &file_crowparty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyResponse) ProtoMessage() {}

func (x *PartyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyResponse.ProtoReflect.Descriptor instead.
func (*PartyResponse) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{1}
}

func (x *PartyResponse) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *PartyResponse) GetSenderPlayerId() uint64 {
	if x != nil {
		return x.SenderPlayerId
	}
	return 0
}

func (x *PartyResponse) GetResponse() isPartyResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *PartyResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *PartyResponse) GetJoinRoom() *Room {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *PartyResponse) GetDisbandRoom() bool {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_DisbandRoom); ok {
			return x.DisbandRoom
		}
	}
	return false
}

func (x *PartyResponse) GetChangeLeader() uint64 {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_ChangeLeader); ok {
			return x.ChangeLeader
		}
	}
	return 0
}

func (x *PartyResponse) GetChangeRoomProperty() *CustomProperty {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_ChangeRoomProperty); ok {
			return x.ChangeRoomProperty
		}
	}
	return nil
}

func (x *PartyResponse) GetApplyRoomRequest() string {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_ApplyRoomRequest); ok {
			return x.ApplyRoomRequest
		}
	}
	return ""
}

func (x *PartyResponse) GetCancelRoomRequest() bool {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_CancelRoomRequest); ok {
			return x.CancelRoomRequest
		}
	}
	return false
}

func (x *PartyResponse) GetAcceptRoomRequest() string {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_AcceptRoomRequest); ok {
			return x.AcceptRoomRequest
		}
	}
	return ""
}

func (x *PartyResponse) GetRejectRoomRequest() string {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_RejectRoomRequest); ok {
			return x.RejectRoomRequest
		}
	}
	return ""
}

func (x *PartyResponse) GetJoinPlayer() *Player {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_JoinPlayer); ok {
			return x.JoinPlayer
		}
	}
	return nil
}

func (x *PartyResponse) GetLeavePlayer() *Player {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_LeavePlayer); ok {
			return x.LeavePlayer
		}
	}
	return nil
}

func (x *PartyResponse) GetKickPlayer() bool {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_KickPlayer); ok {
			return x.KickPlayer
		}
	}
	return false
}

func (x *PartyResponse) GetChangePlayerProperty() *CustomProperty {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_ChangePlayerProperty); ok {
			return x.ChangePlayerProperty
		}
	}
	return nil
}

func (x *PartyResponse) GetKill() int32 {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_Kill); ok {
			return x.Kill
		}
	}
	return 0
}

func (x *PartyResponse) GetAutoMatchingStartStage() *AutoMatchingInfo {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_AutoMatchingStartStage); ok {
			return x.AutoMatchingStartStage
		}
	}
	return nil
}

func (x *PartyResponse) GetAutoMatchingCancelStage() uint32 {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_AutoMatchingCancelStage); ok {
			return x.AutoMatchingCancelStage
		}
	}
	return 0
}

func (x *PartyResponse) GetAutoMatchingCancelAll() bool {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_AutoMatchingCancelAll); ok {
			return x.AutoMatchingCancelAll
		}
	}
	return false
}

func (x *PartyResponse) GetAutoMatchingSuccess() *AutoMatchingSuccess {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_AutoMatchingSuccess); ok {
			return x.AutoMatchingSuccess
		}
	}
	return nil
}

func (x *PartyResponse) GetInviteRoom() int32 {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_InviteRoom); ok {
			return x.InviteRoom
		}
	}
	return 0
}

func (x *PartyResponse) GetRaiseEvent() *RaiseEvent {
	if x != nil {
		if x, ok := x.Response.(*PartyResponse_RaiseEvent); ok {
			return x.RaiseEvent
		}
	}
	return nil
}

type isPartyResponse_Response interface {
	isPartyResponse_Response()
}

type PartyResponse_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type PartyResponse_JoinRoom struct {
	JoinRoom *Room `protobuf:"bytes,4,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type PartyResponse_DisbandRoom struct {
	DisbandRoom bool `protobuf:"varint,5,opt,name=disband_room,json=disbandRoom,proto3,oneof"`
}

type PartyResponse_ChangeLeader struct {
	ChangeLeader uint64 `protobuf:"varint,6,opt,name=change_leader,json=changeLeader,proto3,oneof"`
}

type PartyResponse_ChangeRoomProperty struct {
	ChangeRoomProperty *CustomProperty `protobuf:"bytes,7,opt,name=change_room_property,json=changeRoomProperty,proto3,oneof"`
}

type PartyResponse_ApplyRoomRequest struct {
	ApplyRoomRequest string `protobuf:"bytes,8,opt,name=apply_room_request,json=applyRoomRequest,proto3,oneof"`
}

type PartyResponse_CancelRoomRequest struct {
	CancelRoomRequest bool `protobuf:"varint,9,opt,name=cancel_room_request,json=cancelRoomRequest,proto3,oneof"`
}

type PartyResponse_AcceptRoomRequest struct {
	AcceptRoomRequest string `protobuf:"bytes,10,opt,name=accept_room_request,json=acceptRoomRequest,proto3,oneof"`
}

type PartyResponse_RejectRoomRequest struct {
	RejectRoomRequest string `protobuf:"bytes,11,opt,name=reject_room_request,json=rejectRoomRequest,proto3,oneof"`
}

type PartyResponse_JoinPlayer struct {
	JoinPlayer *Player `protobuf:"bytes,12,opt,name=join_player,json=joinPlayer,proto3,oneof"`
}

type PartyResponse_LeavePlayer struct {
	LeavePlayer *Player `protobuf:"bytes,13,opt,name=leave_player,json=leavePlayer,proto3,oneof"`
}

type PartyResponse_KickPlayer struct {
	KickPlayer bool `protobuf:"varint,14,opt,name=kick_player,json=kickPlayer,proto3,oneof"`
}

type PartyResponse_ChangePlayerProperty struct {
	ChangePlayerProperty *CustomProperty `protobuf:"bytes,15,opt,name=change_player_property,json=changePlayerProperty,proto3,oneof"`
}

type PartyResponse_Kill struct {
	Kill int32 `protobuf:"varint,16,opt,name=kill,proto3,oneof"`
}

type PartyResponse_AutoMatchingStartStage struct {
	AutoMatchingStartStage *AutoMatchingInfo `protobuf:"bytes,17,opt,name=auto_matching_start_stage,json=autoMatchingStartStage,proto3,oneof"`
}

type PartyResponse_AutoMatchingCancelStage struct {
	AutoMatchingCancelStage uint32 `protobuf:"varint,18,opt,name=auto_matching_cancel_stage,json=autoMatchingCancelStage,proto3,oneof"`
}

type PartyResponse_AutoMatchingCancelAll struct {
	AutoMatchingCancelAll bool `protobuf:"varint,19,opt,name=auto_matching_cancel_all,json=autoMatchingCancelAll,proto3,oneof"`
}

type PartyResponse_AutoMatchingSuccess struct {
	AutoMatchingSuccess *AutoMatchingSuccess `protobuf:"bytes,20,opt,name=auto_matching_success,json=autoMatchingSuccess,proto3,oneof"`
}

type PartyResponse_InviteRoom struct {
	InviteRoom int32 `protobuf:"varint,21,opt,name=invite_room,json=inviteRoom,proto3,oneof"`
}

type PartyResponse_RaiseEvent struct {
	RaiseEvent *RaiseEvent `protobuf:"bytes,22,opt,name=raise_event,json=raiseEvent,proto3,oneof"`
}

func (*PartyResponse_Error) isPartyResponse_Response() {}

func (*PartyResponse_JoinRoom) isPartyResponse_Response() {}

func (*PartyResponse_DisbandRoom) isPartyResponse_Response() {}

func (*PartyResponse_ChangeLeader) isPartyResponse_Response() {}

func (*PartyResponse_ChangeRoomProperty) isPartyResponse_Response() {}

func (*PartyResponse_ApplyRoomRequest) isPartyResponse_Response() {}

func (*PartyResponse_CancelRoomRequest) isPartyResponse_Response() {}

func (*PartyResponse_AcceptRoomRequest) isPartyResponse_Response() {}

func (*PartyResponse_RejectRoomRequest) isPartyResponse_Response() {}

func (*PartyResponse_JoinPlayer) isPartyResponse_Response() {}

func (*PartyResponse_LeavePlayer) isPartyResponse_Response() {}

func (*PartyResponse_KickPlayer) isPartyResponse_Response() {}

func (*PartyResponse_ChangePlayerProperty) isPartyResponse_Response() {}

func (*PartyResponse_Kill) isPartyResponse_Response() {}

func (*PartyResponse_AutoMatchingStartStage) isPartyResponse_Response() {}

func (*PartyResponse_AutoMatchingCancelStage) isPartyResponse_Response() {}

func (*PartyResponse_AutoMatchingCancelAll) isPartyResponse_Response() {}

func (*PartyResponse_AutoMatchingSuccess) isPartyResponse_Response() {}

func (*PartyResponse_InviteRoom) isPartyResponse_Response() {}

func (*PartyResponse_RaiseEvent) isPartyResponse_Response() {}

type IsPartyMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsPartyMemberRequest) Reset() {
	*x = IsPartyMemberRequest{}
	mi := &file_crowparty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsPartyMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPartyMemberRequest) ProtoMessage() {}

func (x *IsPartyMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPartyMemberRequest.ProtoReflect.Descriptor instead.
func (*IsPartyMemberRequest) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{2}
}

func (x *IsPartyMemberRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *IsPartyMemberRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type IsPartyMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsPartyMemberResponse) Reset() {
	*x = IsPartyMemberResponse{}
	mi := &file_crowparty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsPartyMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPartyMemberResponse) ProtoMessage() {}

func (x *IsPartyMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPartyMemberResponse.ProtoReflect.Descriptor instead.
func (*IsPartyMemberResponse) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{3}
}

func (x *IsPartyMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

type PartySearchRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Player            *PlayerInfo            `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	StageId           uint32                 `protobuf:"varint,2,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	GuildId           uint64                 `protobuf:"varint,3,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	IsGuildMemberOnly bool                   `protobuf:"varint,4,opt,name=is_guild_member_only,json=isGuildMemberOnly,proto3" json:"is_guild_member_only,omitempty"`
	MaxPlayerCount    int32                  `protobuf:"varint,5,opt,name=max_player_count,json=maxPlayerCount,proto3" json:"max_player_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PartySearchRequest) Reset() {
	*x = PartySearchRequest{}
	mi := &file_crowparty_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartySearchRequest) ProtoMessage() {}

func (x *PartySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartySearchRequest.ProtoReflect.Descriptor instead.
func (*PartySearchRequest) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{4}
}

func (x *PartySearchRequest) GetPlayer() *PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PartySearchRequest) GetStageId() uint32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *PartySearchRequest) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *PartySearchRequest) GetIsGuildMemberOnly() bool {
	if x != nil {
		return x.IsGuildMemberOnly
	}
	return false
}

func (x *PartySearchRequest) GetMaxPlayerCount() int32 {
	if x != nil {
		return x.MaxPlayerCount
	}
	return 0
}

type PartySearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartySearchResponse) Reset() {
	*x = PartySearchResponse{}
	mi := &file_crowparty_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartySearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartySearchResponse) ProtoMessage() {}

func (x *PartySearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartySearchResponse.ProtoReflect.Descriptor instead.
func (*PartySearchResponse) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{5}
}

func (x *PartySearchResponse) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type CustomProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           map[string]string      `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomProperty) Reset() {
	*x = CustomProperty{}
	mi := &file_crowparty_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomProperty) ProtoMessage() {}

func (x *CustomProperty) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomProperty.ProtoReflect.Descriptor instead.
func (*CustomProperty) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{6}
}

func (x *CustomProperty) GetMap() map[string]string {
	if x != nil {
		return x.Map
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Property      *CustomProperty        `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	IsInactive    bool                   `protobuf:"varint,3,opt,name=is_inactive,json=isInactive,proto3" json:"is_inactive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_crowparty_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{7}
}

func (x *Player) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetProperty() *CustomProperty {
	if x != nil {
		return x.Property
	}
	return nil
}

func (x *Player) GetIsInactive() bool {
	if x != nil {
		return x.IsInactive
	}
	return false
}

type Room struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Property       *CustomProperty        `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	LeaderPlayerId uint64                 `protobuf:"varint,3,opt,name=leader_player_id,json=leaderPlayerId,proto3" json:"leader_player_id,omitempty"`
	Players        []*Player              `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_crowparty_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{8}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetProperty() *CustomProperty {
	if x != nil {
		return x.Property
	}
	return nil
}

func (x *Room) GetLeaderPlayerId() uint64 {
	if x != nil {
		return x.LeaderPlayerId
	}
	return 0
}

func (x *Room) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type ResumeRoom struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerProperty *CustomProperty        `protobuf:"bytes,2,opt,name=player_property,json=playerProperty,proto3" json:"player_property,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResumeRoom) Reset() {
	*x = ResumeRoom{}
	mi := &file_crowparty_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRoom) ProtoMessage() {}

func (x *ResumeRoom) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRoom.ProtoReflect.Descriptor instead.
func (*ResumeRoom) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{9}
}

func (x *ResumeRoom) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ResumeRoom) GetPlayerProperty() *CustomProperty {
	if x != nil {
		return x.PlayerProperty
	}
	return nil
}

type RoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomRequest) Reset() {
	*x = RoomRequest{}
	mi := &file_crowparty_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomRequest) ProtoMessage() {}

func (x *RoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomRequest.ProtoReflect.Descriptor instead.
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{10}
}

func (x *RoomRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinRoom struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           JoinType_Enum          `protobuf:"varint,1,opt,name=type,proto3,enum=CrowParty.JoinType_Enum" json:"type,omitempty"`
	RoomId         string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomProperty   *CustomProperty        `protobuf:"bytes,3,opt,name=room_property,json=roomProperty,proto3" json:"room_property,omitempty"`
	PlayerId       uint64                 `protobuf:"varint,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerProperty *CustomProperty        `protobuf:"bytes,5,opt,name=player_property,json=playerProperty,proto3" json:"player_property,omitempty"`
	RaidId         uint32                 `protobuf:"varint,6,opt,name=raid_id,json=raidId,proto3" json:"raid_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	mi := &file_crowparty_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom.ProtoReflect.Descriptor instead.
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{11}
}

func (x *JoinRoom) GetType() JoinType_Enum {
	if x != nil {
		return x.Type
	}
	return JoinType_CREATE
}

func (x *JoinRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoom) GetRoomProperty() *CustomProperty {
	if x != nil {
		return x.RoomProperty
	}
	return nil
}

func (x *JoinRoom) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *JoinRoom) GetPlayerProperty() *CustomProperty {
	if x != nil {
		return x.PlayerProperty
	}
	return nil
}

func (x *JoinRoom) GetRaidId() uint32 {
	if x != nil {
		return x.RaidId
	}
	return 0
}

type InviteRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerIds     []uint64               `protobuf:"varint,1,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRoom) Reset() {
	*x = InviteRoom{}
	mi := &file_crowparty_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRoom) ProtoMessage() {}

func (x *InviteRoom) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRoom.ProtoReflect.Descriptor instead.
func (*InviteRoom) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{12}
}

func (x *InviteRoom) GetPlayerIds() []uint64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

type AutoMatchingStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Role          uint32                 `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	Power         uint32                 `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoMatchingStart) Reset() {
	*x = AutoMatchingStart{}
	mi := &file_crowparty_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoMatchingStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoMatchingStart) ProtoMessage() {}

func (x *AutoMatchingStart) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoMatchingStart.ProtoReflect.Descriptor instead.
func (*AutoMatchingStart) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{13}
}

func (x *AutoMatchingStart) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *AutoMatchingStart) GetRole() uint32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *AutoMatchingStart) GetPower() uint32 {
	if x != nil {
		return x.Power
	}
	return 0
}

type AutoMatchingStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	StageId       uint32                 `protobuf:"varint,2,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	TimeoutSecond uint32                 `protobuf:"varint,3,opt,name=timeout_second,json=timeoutSecond,proto3" json:"timeout_second,omitempty"`
	Risk          uint32                 `protobuf:"varint,4,opt,name=risk,proto3" json:"risk,omitempty"`
	ContentsType  uint32                 `protobuf:"varint,5,opt,name=contents_type,json=contentsType,proto3" json:"contents_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoMatchingStage) Reset() {
	*x = AutoMatchingStage{}
	mi := &file_crowparty_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoMatchingStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoMatchingStage) ProtoMessage() {}

func (x *AutoMatchingStage) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoMatchingStage.ProtoReflect.Descriptor instead.
func (*AutoMatchingStage) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{14}
}

func (x *AutoMatchingStage) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *AutoMatchingStage) GetStageId() uint32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *AutoMatchingStage) GetTimeoutSecond() uint32 {
	if x != nil {
		return x.TimeoutSecond
	}
	return 0
}

func (x *AutoMatchingStage) GetRisk() uint32 {
	if x != nil {
		return x.Risk
	}
	return 0
}

func (x *AutoMatchingStage) GetContentsType() uint32 {
	if x != nil {
		return x.ContentsType
	}
	return 0
}

type AutoMatchingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       uint32                 `protobuf:"varint,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	StartAt       int64                  `protobuf:"varint,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoMatchingInfo) Reset() {
	*x = AutoMatchingInfo{}
	mi := &file_crowparty_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoMatchingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoMatchingInfo) ProtoMessage() {}

func (x *AutoMatchingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoMatchingInfo.ProtoReflect.Descriptor instead.
func (*AutoMatchingInfo) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{15}
}

func (x *AutoMatchingInfo) GetStageId() uint32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *AutoMatchingInfo) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

type AutoMatchingSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	StageId       uint32                 `protobuf:"varint,2,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Timeout       bool                   `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoMatchingSuccess) Reset() {
	*x = AutoMatchingSuccess{}
	mi := &file_crowparty_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoMatchingSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoMatchingSuccess) ProtoMessage() {}

func (x *AutoMatchingSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoMatchingSuccess.ProtoReflect.Descriptor instead.
func (*AutoMatchingSuccess) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{16}
}

func (x *AutoMatchingSuccess) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AutoMatchingSuccess) GetStageId() uint32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *AutoMatchingSuccess) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AutoMatchingSuccess) GetTimeout() bool {
	if x != nil {
		return x.Timeout
	}
	return false
}

type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Power         uint32                 `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
	JobLevel      uint32                 `protobuf:"varint,3,opt,name=job_level,json=jobLevel,proto3" json:"job_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_crowparty_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{17}
}

func (x *PlayerInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerInfo) GetPower() uint32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *PlayerInfo) GetJobLevel() uint32 {
	if x != nil {
		return x.JobLevel
	}
	return 0
}

type RoomInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LeaderPlayerId  uint64                 `protobuf:"varint,3,opt,name=leader_player_id,json=leaderPlayerId,proto3" json:"leader_player_id,omitempty"`
	MaxPlayers      int32                  `protobuf:"varint,4,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	Approval        bool                   `protobuf:"varint,5,opt,name=approval,proto3" json:"approval,omitempty"`
	StageId         uint32                 `protobuf:"varint,6,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	AutoBattleCount uint32                 `protobuf:"varint,7,opt,name=auto_battle_count,json=autoBattleCount,proto3" json:"auto_battle_count,omitempty"`
	Players         []*PlayerInfo          `protobuf:"bytes,8,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_crowparty_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{18}
}

func (x *RoomInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetLeaderPlayerId() uint64 {
	if x != nil {
		return x.LeaderPlayerId
	}
	return 0
}

func (x *RoomInfo) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *RoomInfo) GetApproval() bool {
	if x != nil {
		return x.Approval
	}
	return false
}

func (x *RoomInfo) GetStageId() uint32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *RoomInfo) GetAutoBattleCount() uint32 {
	if x != nil {
		return x.AutoBattleCount
	}
	return 0
}

func (x *RoomInfo) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type RaiseEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Group ReceiverGroup_Enum     `protobuf:"varint,1,opt,name=group,proto3,enum=CrowParty.ReceiverGroup_Enum" json:"group,omitempty"`
	Code  int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*RaiseEvent_StageId
	//	*RaiseEvent_Message
	Data          isRaiseEvent_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaiseEvent) Reset() {
	*x = RaiseEvent{}
	mi := &file_crowparty_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaiseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaiseEvent) ProtoMessage() {}

func (x *RaiseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaiseEvent.ProtoReflect.Descriptor instead.
func (*RaiseEvent) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{19}
}

func (x *RaiseEvent) GetGroup() ReceiverGroup_Enum {
	if x != nil {
		return x.Group
	}
	return ReceiverGroup_OTHERS
}

func (x *RaiseEvent) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RaiseEvent) GetData() isRaiseEvent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RaiseEvent) GetStageId() uint32 {
	if x != nil {
		if x, ok := x.Data.(*RaiseEvent_StageId); ok {
			return x.StageId
		}
	}
	return 0
}

func (x *RaiseEvent) GetMessage() string {
	if x != nil {
		if x, ok := x.Data.(*RaiseEvent_Message); ok {
			return x.Message
		}
	}
	return ""
}

type isRaiseEvent_Data interface {
	isRaiseEvent_Data()
}

type RaiseEvent_StageId struct {
	StageId uint32 `protobuf:"varint,3,opt,name=stage_id,json=stageId,proto3,oneof"`
}

type RaiseEvent_Message struct {
	Message string `protobuf:"bytes,4,opt,name=message,proto3,oneof"`
}

func (*RaiseEvent_StageId) isRaiseEvent_Data() {}

func (*RaiseEvent_Message) isRaiseEvent_Data() {}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode_Enum         `protobuf:"varint,1,opt,name=code,proto3,enum=CrowParty.ErrorCode_Enum" json:"code,omitempty"`
	Level         ErrorLevel_Enum        `protobuf:"varint,2,opt,name=level,proto3,enum=CrowParty.ErrorLevel_Enum" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_crowparty_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{20}
}

func (x *Error) GetCode() ErrorCode_Enum {
	if x != nil {
		return x.Code
	}
	return ErrorCode_UNKNOWN
}

func (x *Error) GetLevel() ErrorLevel_Enum {
	if x != nil {
		return x.Level
	}
	return ErrorLevel_ERROR
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JoinType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinType) Reset() {
	*x = JoinType{}
	mi := &file_crowparty_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinType) ProtoMessage() {}

func (x *JoinType) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinType.ProtoReflect.Descriptor instead.
func (*JoinType) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{21}
}

type RoomVisibility struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomVisibility) Reset() {
	*x = RoomVisibility{}
	mi := &file_crowparty_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomVisibility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomVisibility) ProtoMessage() {}

func (x *RoomVisibility) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomVisibility.ProtoReflect.Descriptor instead.
func (*RoomVisibility) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{22}
}

type ReceiverGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiverGroup) Reset() {
	*x = ReceiverGroup{}
	mi := &file_crowparty_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiverGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiverGroup) ProtoMessage() {}

func (x *ReceiverGroup) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiverGroup.ProtoReflect.Descriptor instead.
func (*ReceiverGroup) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{23}
}

type ErrorCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorCode) Reset() {
	*x = ErrorCode{}
	mi := &file_crowparty_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorCode) ProtoMessage() {}

func (x *ErrorCode) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorCode.ProtoReflect.Descriptor instead.
func (*ErrorCode) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{24}
}

type ErrorLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorLevel) Reset() {
	*x = ErrorLevel{}
	mi := &file_crowparty_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorLevel) ProtoMessage() {}

func (x *ErrorLevel) ProtoReflect() protoreflect.Message {
	mi := &file_crowparty_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorLevel.ProtoReflect.Descriptor instead.
func (*ErrorLevel) Descriptor() ([]byte, []int) {
	return file_crowparty_proto_rawDescGZIP(), []int{25}
}

var File_crowparty_proto protoreflect.FileDescriptor

const file_crowparty_proto_rawDesc = "" +
	"\n" +
	"\x0fcrowparty.proto\x12\tCrowParty\"\xb9\t\n" +
	"\fPartyRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x05R\tmessageId\x128\n" +
	"\vresume_room\x18\x02 \x01(\v2\x15.CrowParty.ResumeRoomH\x00R\n" +
	"resumeRoom\x12C\n" +
	"\x12apply_room_request\x18\x03 \x01(\v2\x13.CrowParty.JoinRoomH\x00R\x10applyRoomRequest\x12H\n" +
	"\x13cancel_room_request\x18\x04 \x01(\v2\x16.CrowParty.RoomRequestH\x00R\x11cancelRoomRequest\x120\n" +
	"\x13accept_room_request\x18\x05 \x01(\x04H\x00R\x11acceptRoomRequest\x120\n" +
	"\x13reject_room_request\x18\x06 \x01(\x04H\x00R\x11rejectRoomRequest\x122\n" +
	"\tjoin_room\x18\a \x01(\v2\x13.CrowParty.JoinRoomH\x00R\bjoinRoom\x12\x1f\n" +
	"\n" +
	"leave_room\x18\b \x01(\bH\x00R\tleaveRoom\x12\x1d\n" +
	"\tkick_room\x18\t \x01(\x04H\x00R\bkickRoom\x12#\n" +
	"\fdisband_room\x18\n" +
	" \x01(\bH\x00R\vdisbandRoom\x12%\n" +
	"\rchange_leader\x18\v \x01(\x04H\x00R\fchangeLeader\x12M\n" +
	"\x14change_room_property\x18\f \x01(\v2\x19.CrowParty.CustomPropertyH\x00R\x12changeRoomProperty\x12Q\n" +
	"\x16change_player_property\x18\r \x01(\v2\x19.CrowParty.CustomPropertyH\x00R\x14changePlayerProperty\x12N\n" +
	"\x13auto_matching_start\x18\x0e \x01(\v2\x1c.CrowParty.AutoMatchingStartH\x00R\x11autoMatchingStart\x12Y\n" +
	"\x19auto_matching_start_stage\x18\x0f \x01(\v2\x1c.CrowParty.AutoMatchingStageH\x00R\x16autoMatchingStartStage\x12[\n" +
	"\x1aauto_matching_cancel_stage\x18\x10 \x01(\v2\x1c.CrowParty.AutoMatchingStageH\x00R\x17autoMatchingCancelStage\x129\n" +
	"\x18auto_matching_cancel_all\x18\x11 \x01(\x04H\x00R\x15autoMatchingCancelAll\x129\n" +
	"\x18auto_matching_room_break\x18\x12 \x01(\bH\x00R\x15autoMatchingRoomBreak\x128\n" +
	"\vinvite_room\x18\x13 \x01(\v2\x15.CrowParty.InviteRoomH\x00R\n" +
	"inviteRoom\x128\n" +
	"\vraise_event\x18\x14 \x01(\v2\x15.CrowParty.RaiseEventH\x00R\n" +
	"raiseEventB\t\n" +
	"\arequest\"\xa0\t\n" +
	"\rPartyResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x05R\tmessageId\x12(\n" +
	"\x10sender_player_id\x18\x02 \x01(\x04R\x0esenderPlayerId\x12(\n" +
	"\x05error\x18\x03 \x01(\v2\x10.CrowParty.ErrorH\x00R\x05error\x12.\n" +
	"\tjoin_room\x18\x04 \x01(\v2\x0f.CrowParty.RoomH\x00R\bjoinRoom\x12#\n" +
	"\fdisband_room\x18\x05 \x01(\bH\x00R\vdisbandRoom\x12%\n" +
	"\rchange_leader\x18\x06 \x01(\x04H\x00R\fchangeLeader\x12M\n" +
	"\x14change_room_property\x18\a \x01(\v2\x19.CrowParty.CustomPropertyH\x00R\x12changeRoomProperty\x12.\n" +
	"\x12apply_room_request\x18\b \x01(\tH\x00R\x10applyRoomRequest\x120\n" +
	"\x13cancel_room_request\x18\t \x01(\bH\x00R\x11cancelRoomRequest\x120\n" +
	"\x13accept_room_request\x18\n" +
	" \x01(\tH\x00R\x11acceptRoomRequest\x120\n" +
	"\x13reject_room_request\x18\v \x01(\tH\x00R\x11rejectRoomRequest\x124\n" +
	"\vjoin_player\x18\f \x01(\v2\x11.CrowParty.PlayerH\x00R\n" +
	"joinPlayer\x126\n" +
	"\fleave_player\x18\r \x01(\v2\x11.CrowParty.PlayerH\x00R\vleavePlayer\x12!\n" +
	"\vkick_player\x18\x0e \x01(\bH\x00R\n" +
	"kickPlayer\x12Q\n" +
	"\x16change_player_property\x18\x0f \x01(\v2\x19.CrowParty.CustomPropertyH\x00R\x14changePlayerProperty\x12\x14\n" +
	"\x04kill\x18\x10 \x01(\x05H\x00R\x04kill\x12X\n" +
	"\x19auto_matching_start_stage\x18\x11 \x01(\v2\x1b.CrowParty.AutoMatchingInfoH\x00R\x16autoMatchingStartStage\x12=\n" +
	"\x1aauto_matching_cancel_stage\x18\x12 \x01(\rH\x00R\x17autoMatchingCancelStage\x129\n" +
	"\x18auto_matching_cancel_all\x18\x13 \x01(\bH\x00R\x15autoMatchingCancelAll\x12T\n" +
	"\x15auto_matching_success\x18\x14 \x01(\v2\x1e.CrowParty.AutoMatchingSuccessH\x00R\x13autoMatchingSuccess\x12!\n" +
	"\vinvite_room\x18\x15 \x01(\x05H\x00R\n" +
	"inviteRoom\x128\n" +
	"\vraise_event\x18\x16 \x01(\v2\x15.CrowParty.RaiseEventH\x00R\n" +
	"raiseEventB\n" +
	"\n" +
	"\bresponse\"L\n" +
	"\x14IsPartyMemberRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"4\n" +
	"\x15IsPartyMemberResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\"\xd4\x01\n" +
	"\x12PartySearchRequest\x12-\n" +
	"\x06player\x18\x01 \x01(\v2\x15.CrowParty.PlayerInfoR\x06player\x12\x19\n" +
	"\bstage_id\x18\x02 \x01(\rR\astageId\x12\x19\n" +
	"\bguild_id\x18\x03 \x01(\x04R\aguildId\x12/\n" +
	"\x14is_guild_member_only\x18\x04 \x01(\bR\x11isGuildMemberOnly\x12(\n" +
	"\x10max_player_count\x18\x05 \x01(\x05R\x0emaxPlayerCount\"@\n" +
	"\x13PartySearchResponse\x12)\n" +
	"\x05rooms\x18\x01 \x03(\v2\x13.CrowParty.RoomInfoR\x05rooms\"~\n" +
	"\x0eCustomProperty\x124\n" +
	"\x03map\x18\x01 \x03(\v2\".CrowParty.CustomProperty.MapEntryR\x03map\x1a6\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x125\n" +
	"\bproperty\x18\x02 \x01(\v2\x19.CrowParty.CustomPropertyR\bproperty\x12\x1f\n" +
	"\vis_inactive\x18\x03 \x01(\bR\n" +
	"isInactive\"\xa4\x01\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\bproperty\x18\x02 \x01(\v2\x19.CrowParty.CustomPropertyR\bproperty\x12(\n" +
	"\x10leader_player_id\x18\x03 \x01(\x04R\x0eleaderPlayerId\x12+\n" +
	"\aplayers\x18\x04 \x03(\v2\x11.CrowParty.PlayerR\aplayers\"m\n" +
	"\n" +
	"ResumeRoom\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12B\n" +
	"\x0fplayer_property\x18\x02 \x01(\v2\x19.CrowParty.CustomPropertyR\x0eplayerProperty\"C\n" +
	"\vRoomRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"\x8b\x02\n" +
	"\bJoinRoom\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.CrowParty.JoinType.EnumR\x04type\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12>\n" +
	"\rroom_property\x18\x03 \x01(\v2\x19.CrowParty.CustomPropertyR\froomProperty\x12\x1b\n" +
	"\tplayer_id\x18\x04 \x01(\x04R\bplayerId\x12B\n" +
	"\x0fplayer_property\x18\x05 \x01(\v2\x19.CrowParty.CustomPropertyR\x0eplayerProperty\x12\x17\n" +
	"\araid_id\x18\x06 \x01(\rR\x06raidId\"+\n" +
	"\n" +
	"InviteRoom\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x01 \x03(\x04R\tplayerIds\"Z\n" +
	"\x11AutoMatchingStart\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\rR\x04role\x12\x14\n" +
	"\x05power\x18\x03 \x01(\rR\x05power\"\xab\x01\n" +
	"\x11AutoMatchingStage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x19\n" +
	"\bstage_id\x18\x02 \x01(\rR\astageId\x12%\n" +
	"\x0etimeout_second\x18\x03 \x01(\rR\rtimeoutSecond\x12\x12\n" +
	"\x04risk\x18\x04 \x01(\rR\x04risk\x12#\n" +
	"\rcontents_type\x18\x05 \x01(\rR\fcontentsType\"H\n" +
	"\x10AutoMatchingInfo\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\rR\astageId\x12\x19\n" +
	"\bstart_at\x18\x02 \x01(\x03R\astartAt\"y\n" +
	"\x13AutoMatchingSuccess\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x19\n" +
	"\bstage_id\x18\x02 \x01(\rR\astageId\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\bR\atimeout\"O\n" +
	"\n" +
	"PlayerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05power\x18\x02 \x01(\rR\x05power\x12\x1b\n" +
	"\tjob_level\x18\x03 \x01(\rR\bjobLevel\"\x8d\x02\n" +
	"\bRoomInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x10leader_player_id\x18\x03 \x01(\x04R\x0eleaderPlayerId\x12\x1f\n" +
	"\vmax_players\x18\x04 \x01(\x05R\n" +
	"maxPlayers\x12\x1a\n" +
	"\bapproval\x18\x05 \x01(\bR\bapproval\x12\x19\n" +
	"\bstage_id\x18\x06 \x01(\rR\astageId\x12*\n" +
	"\x11auto_battle_count\x18\a \x01(\rR\x0fautoBattleCount\x12/\n" +
	"\aplayers\x18\b \x03(\v2\x15.CrowParty.PlayerInfoR\aplayers\"\x96\x01\n" +
	"\n" +
	"RaiseEvent\x123\n" +
	"\x05group\x18\x01 \x01(\x0e2\x1d.CrowParty.ReceiverGroup.EnumR\x05group\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x1b\n" +
	"\bstage_id\x18\x03 \x01(\rH\x00R\astageId\x12\x1a\n" +
	"\amessage\x18\x04 \x01(\tH\x00R\amessageB\x06\n" +
	"\x04data\"\x82\x01\n" +
	"\x05Error\x12-\n" +
	"\x04code\x18\x01 \x01(\x0e2\x19.CrowParty.ErrorCode.EnumR\x04code\x120\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1a.CrowParty.ErrorLevel.EnumR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"c\n" +
	"\bJoinType\"W\n" +
	"\x04Enum\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\b\n" +
	"\x04JOIN\x10\x01\x12\n" +
	"\n" +
	"\x06ACCEPT\x10\x02\x12\n" +
	"\n" +
	"\x06REJOIN\x10\x03\x12\b\n" +
	"\x04AUTO\x10\x04\x12\v\n" +
	"\aINTRUDE\x10\x05\x12\n" +
	"\n" +
	"\x06RESCUE\x10\x06\"<\n" +
	"\x0eRoomVisibility\"*\n" +
	"\x04Enum\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x00\x12\t\n" +
	"\x05GUILD\x10\x01\x12\v\n" +
	"\aPRIVATE\x10\x02\"8\n" +
	"\rReceiverGroup\"'\n" +
	"\x04Enum\x12\n" +
	"\n" +
	"\x06OTHERS\x10\x00\x12\a\n" +
	"\x03ALL\x10\x01\x12\n" +
	"\n" +
	"\x06LEADER\x10\x02\"\xaa\x03\n" +
	"\tErrorCode\"\x9c\x03\n" +
	"\x04Enum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x17\n" +
	"\x13ROOM_ALREADY_EXISTS\x10\x01\x12\x13\n" +
	"\x0fALREADY_IN_ROOM\x10\x02\x12\x0f\n" +
	"\vNOT_IN_ROOM\x10\x03\x12\x12\n" +
	"\x0eROOM_NOT_FOUND\x10\x04\x12\x12\n" +
	"\x0eROOM_CONDITION\x10\x05\x12\x10\n" +
	"\fROOM_IS_FULL\x10\x06\x12\x1a\n" +
	"\x16ROOM_REQUEST_NOT_FOUND\x10\a\x12\x13\n" +
	"\x0fROOM_IDMISMATCH\x10\b\x12\x0e\n" +
	"\n" +
	"NOT_LEADER\x10\t\x12\x14\n" +
	"\x10PLAYER_NOT_FOUND\x10\n" +
	"\x12\x16\n" +
	"\x12PLAYER_IS_INACTIVE\x10\v\x12!\n" +
	"\x1dAUTO_MATCHING_ALREADY_STARTED\x10\f\x12\x1d\n" +
	"\x19AUTO_MATCHING_NOT_STARTED\x10\r\x12\x1a\n" +
	"\x16AUTO_MATCHING_RUNNNING\x10\x0e\x12\x16\n" +
	"\x12AUTO_MATCHING_ROOM\x10\x0f\x12\x1a\n" +
	"\x16NOT_AUTO_MATCHING_ROOM\x10\x10\x12\r\n" +
	"\tIN_BATTLE\x10\x11\")\n" +
	"\n" +
	"ErrorLevel\"\x1b\n" +
	"\x04Enum\x12\t\n" +
	"\x05ERROR\x10\x00\x12\b\n" +
	"\x04WARN\x10\x012\xef\x01\n" +
	"\tCrowParty\x12@\n" +
	"\aConnect\x12\x17.CrowParty.PartyRequest\x1a\x18.CrowParty.PartyResponse(\x010\x01\x12R\n" +
	"\rIsPartyMember\x12\x1f.CrowParty.IsPartyMemberRequest\x1a .CrowParty.IsPartyMemberResponse\x12L\n" +
	"\vSearchRooms\x12\x1d.CrowParty.PartySearchRequest\x1a\x1e.CrowParty.PartySearchResponseB/Z-example.com/brave-revival/src/proto/crowpartyb\x06proto3"

var (
	file_crowparty_proto_rawDescOnce sync.Once
	file_crowparty_proto_rawDescData []byte
)

func file_crowparty_proto_rawDescGZIP() []byte {
	file_crowparty_proto_rawDescOnce.Do(func() {
		file_crowparty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crowparty_proto_rawDesc), len(file_crowparty_proto_rawDesc)))
	})
	return file_crowparty_proto_rawDescData
}

var file_crowparty_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_crowparty_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_crowparty_proto_goTypes = []any{
	(JoinType_Enum)(0),            // 0: CrowParty.JoinType.Enum
	(RoomVisibility_Enum)(0),      // 1: CrowParty.RoomVisibility.Enum
	(ReceiverGroup_Enum)(0),       // 2: CrowParty.ReceiverGroup.Enum
	(ErrorCode_Enum)(0),           // 3: CrowParty.ErrorCode.Enum
	(ErrorLevel_Enum)(0),          // 4: CrowParty.ErrorLevel.Enum
	(*PartyRequest)(nil),          // 5: CrowParty.PartyRequest
	(*PartyResponse)(nil),         // 6: CrowParty.PartyResponse
	(*IsPartyMemberRequest)(nil),  // 7: CrowParty.IsPartyMemberRequest
	(*IsPartyMemberResponse)(nil), // 8: CrowParty.IsPartyMemberResponse
	(*PartySearchRequest)(nil),    // 9: CrowParty.PartySearchRequest
	(*PartySearchResponse)(nil),   // 10: CrowParty.PartySearchResponse
	(*CustomProperty)(nil),        // 11: CrowParty.CustomProperty
	(*Player)(nil),                // 12: CrowParty.Player
	(*Room)(nil),                  // 13: CrowParty.Room
	(*ResumeRoom)(nil),            // 14: CrowParty.ResumeRoom
	(*RoomRequest)(nil),           // 15: CrowParty.RoomRequest
	(*JoinRoom)(nil),              // 16: CrowParty.JoinRoom
	(*InviteRoom)(nil),            // 17: CrowParty.InviteRoom
	(*AutoMatchingStart)(nil),     // 18: CrowParty.AutoMatchingStart
	(*AutoMatchingStage)(nil),     // 19: CrowParty.AutoMatchingStage
	(*AutoMatchingInfo)(nil),      // 20: CrowParty.AutoMatchingInfo
	(*AutoMatchingSuccess)(nil),   // 21: CrowParty.AutoMatchingSuccess
	(*PlayerInfo)(nil),            // 22: CrowParty.PlayerInfo
	(*RoomInfo)(nil),              // 23: CrowParty.RoomInfo
	(*RaiseEvent)(nil),            // 24: CrowParty.RaiseEvent
	(*Error)(nil),                 // 25: CrowParty.Error
	(*JoinType)(nil),              // 26: CrowParty.JoinType
	(*RoomVisibility)(nil),        // 27: CrowParty.RoomVisibility
	(*ReceiverGroup)(nil),         // 28: CrowParty.ReceiverGroup
	(*ErrorCode)(nil),             // 29: CrowParty.ErrorCode
	(*ErrorLevel)(nil),            // 30: CrowParty.ErrorLevel
	nil,                           // 31: CrowParty.CustomProperty.MapEntry
}
var file_crowparty_proto_depIdxs = []int32{
	14, // 0: CrowParty.PartyRequest.resume_room:type_name -> CrowParty.ResumeRoom
	16, // 1: CrowParty.PartyRequest.apply_room_request:type_name -> CrowParty.JoinRoom
	15, // 2: CrowParty.PartyRequest.cancel_room_request:type_name -> CrowParty.RoomRequest
	16, // 3: CrowParty.PartyRequest.join_room:type_name -> CrowParty.JoinRoom
	11, // 4: CrowParty.PartyRequest.change_room_property:type_name -> CrowParty.CustomProperty
	11, // 5: CrowParty.PartyRequest.change_player_property:type_name -> CrowParty.CustomProperty
	18, // 6: CrowParty.PartyRequest.auto_matching_start:type_name -> CrowParty.AutoMatchingStart
	19, // 7: CrowParty.PartyRequest.auto_matching_start_stage:type_name -> CrowParty.AutoMatchingStage
	19, // 8: CrowParty.PartyRequest.auto_matching_cancel_stage:type_name -> CrowParty.AutoMatchingStage
	17, // 9: CrowParty.PartyRequest.invite_room:type_name -> CrowParty.InviteRoom
	24, // 10: CrowParty.PartyRequest.raise_event:type_name -> CrowParty.RaiseEvent
	25, // 11: CrowParty.PartyResponse.error:type_name -> CrowParty.Error
	13, // 12: CrowParty.PartyResponse.join_room:type_name -> CrowParty.Room
	11, // 13: CrowParty.PartyResponse.change_room_property:type_name -> CrowParty.CustomProperty
	12, // 14: CrowParty.PartyResponse.join_player:type_name -> CrowParty.Player
	12, // 15: CrowParty.PartyResponse.leave_player:type_name -> CrowParty.Player
	11, // 16: CrowParty.PartyResponse.change_player_property:type_name -> CrowParty.CustomProperty
	20, // 17: CrowParty.PartyResponse.auto_matching_start_stage:type_name -> CrowParty.AutoMatchingInfo
	21, // 18: CrowParty.PartyResponse.auto_matching_success:type_name -> CrowParty.AutoMatchingSuccess
	24, // 19: CrowParty.PartyResponse.raise_event:type_name -> CrowParty.RaiseEvent
	22, // 20: CrowParty.PartySearchRequest.player:type_name -> CrowParty.PlayerInfo
	23, // 21: CrowParty.PartySearchResponse.rooms:type_name -> CrowParty.RoomInfo
	31, // 22: CrowParty.CustomProperty.map:type_name -> CrowParty.CustomProperty.MapEntry
	11, // 23: CrowParty.Player.property:type_name -> CrowParty.CustomProperty
	11, // 24: CrowParty.Room.property:type_name -> CrowParty.CustomProperty
	12, // 25: CrowParty.Room.players:type_name -> CrowParty.Player
	11, // 26: CrowParty.ResumeRoom.player_property:type_name -> CrowParty.CustomProperty
	0,  // 27: CrowParty.JoinRoom.type:type_name -> CrowParty.JoinType.Enum
	11, // 28: CrowParty.JoinRoom.room_property:type_name -> CrowParty.CustomProperty
	11, // 29: CrowParty.JoinRoom.player_property:type_name -> CrowParty.CustomProperty
	22, // 30: CrowParty.RoomInfo.players:type_name -> CrowParty.PlayerInfo
	2,  // 31: CrowParty.RaiseEvent.group:type_name -> CrowParty.ReceiverGroup.Enum
	3,  // 32: CrowParty.Error.code:type_name -> CrowParty.ErrorCode.Enum
	4,  // 33: CrowParty.Error.level:type_name -> CrowParty.ErrorLevel.Enum
	5,  // 34: CrowParty.CrowParty.Connect:input_type -> CrowParty.PartyRequest
	7,  // 35: CrowParty.CrowParty.IsPartyMember:input_type -> CrowParty.IsPartyMemberRequest
	9,  // 36: CrowParty.CrowParty.SearchRooms:input_type -> CrowParty.PartySearchRequest
	6,  // 37: CrowParty.CrowParty.Connect:output_type -> CrowParty.PartyResponse
	8,  // 38: CrowParty.CrowParty.IsPartyMember:output_type -> CrowParty.IsPartyMemberResponse
	10, // 39: CrowParty.CrowParty.SearchRooms:output_type -> CrowParty.PartySearchResponse
	37, // [37:40] is the sub-list for method output_type
	34, // [34:37] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_crowparty_proto_init() }
func file_crowparty_proto_init() {
	if File_crowparty_proto != nil {
		return
	}
	file_crowparty_proto_msgTypes[0].OneofWrappers = []any{
		(*PartyRequest_ResumeRoom)(nil),
		(*PartyRequest_ApplyRoomRequest)(nil),
		(*PartyRequest_CancelRoomRequest)(nil),
		(*PartyRequest_AcceptRoomRequest)(nil),
		(*PartyRequest_RejectRoomRequest)(nil),
		(*PartyRequest_JoinRoom)(nil),
		(*PartyRequest_LeaveRoom)(nil),
		(*PartyRequest_KickRoom)(nil),
		(*PartyRequest_DisbandRoom)(nil),
		(*PartyRequest_ChangeLeader)(nil),
		(*PartyRequest_ChangeRoomProperty)(nil),
		(*PartyRequest_ChangePlayerProperty)(nil),
		(*PartyRequest_AutoMatchingStart)(nil),
		(*PartyRequest_AutoMatchingStartStage)(nil),
		(*PartyRequest_AutoMatchingCancelStage)(nil),
		(*PartyRequest_AutoMatchingCancelAll)(nil),
		(*PartyRequest_AutoMatchingRoomBreak)(nil),
		(*PartyRequest_InviteRoom)(nil),
		(*PartyRequest_RaiseEvent)(nil),
	}
	file_crowparty_proto_msgTypes[1].OneofWrappers = []any{
		(*PartyResponse_Error)(nil),
		(*PartyResponse_JoinRoom)(nil),
		(*PartyResponse_DisbandRoom)(nil),
		(*PartyResponse_ChangeLeader)(nil),
		(*PartyResponse_ChangeRoomProperty)(nil),
		(*PartyResponse_ApplyRoomRequest)(nil),
		(*PartyResponse_CancelRoomRequest)(nil),
		(*PartyResponse_AcceptRoomRequest)(nil),
		(*PartyResponse_RejectRoomRequest)(nil),
		(*PartyResponse_JoinPlayer)(nil),
		(*PartyResponse_LeavePlayer)(nil),
		(*PartyResponse_KickPlayer)(nil),
		(*PartyResponse_ChangePlayerProperty)(nil),
		(*PartyResponse_Kill)(nil),
		(*PartyResponse_AutoMatchingStartStage)(nil),
		(*PartyResponse_AutoMatchingCancelStage)(nil),
		(*PartyResponse_AutoMatchingCancelAll)(nil),
		(*PartyResponse_AutoMatchingSuccess)(nil),
		(*PartyResponse_InviteRoom)(nil),
		(*PartyResponse_RaiseEvent)(nil),
	}
	file_crowparty_proto_msgTypes[19].OneofWrappers = []any{
		(*RaiseEvent_StageId)(nil),
		(*RaiseEvent_Message)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crowparty_proto_rawDesc), len(file_crowparty_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crowparty_proto_goTypes,
		DependencyIndexes: file_crowparty_proto_depIdxs,
		EnumInfos:         file_crowparty_proto_enumTypes,
		MessageInfos:      file_crowparty_proto_msgTypes,
	}.Build()
	File_crowparty_proto = out.File
	file_crowparty_proto_goTypes = nil
	file_crowparty_proto_depIdxs = nil
}
