// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: pmaster.proto

package pmaster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resources struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Resource      map[uint32]*ResourceInfo `protobuf:"bytes,1,rep,name=resource,proto3" json:"resource,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_pmaster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_pmaster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_pmaster_proto_rawDescGZIP(), []int{0}
}

func (x *Resources) GetResource() map[uint32]*ResourceInfo {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ResourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInfo) Reset() {
	*x = ResourceInfo{}
	mi := &file_pmaster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInfo) ProtoMessage() {}

func (x *ResourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pmaster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInfo.ProtoReflect.Descriptor instead.
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return file_pmaster_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceInfo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ResourceInfo) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type All struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       []*Version             `protobuf:"bytes,250,rep,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *All) Reset() {
	*x = All{}
	mi := &file_pmaster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *All) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*All) ProtoMessage() {}

func (x *All) ProtoReflect() protoreflect.Message {
	mi := &file_pmaster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use All.ProtoReflect.Descriptor instead.
func (*All) Descriptor() ([]byte, []int) {
	return file_pmaster_proto_rawDescGZIP(), []int{2}
}

func (x *All) GetVersion() []*Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Application   string                 `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	Resource      uint32                 `protobuf:"varint,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Master        uint32                 `protobuf:"varint,4,opt,name=master,proto3" json:"master,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_pmaster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_pmaster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_pmaster_proto_rawDescGZIP(), []int{3}
}

func (x *Version) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Version) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *Version) GetResource() uint32 {
	if x != nil {
		return x.Resource
	}
	return 0
}

func (x *Version) GetMaster() uint32 {
	if x != nil {
		return x.Master
	}
	return 0
}

var File_pmaster_proto protoreflect.FileDescriptor

const file_pmaster_proto_rawDesc = "" +
	"\n" +
	"\rpmaster.proto\x12\aPmaster\"\x9d\x01\n" +
	"\tResources\x12<\n" +
	"\bresource\x18\x01 \x03(\v2 .Pmaster.Resources.ResourceEntryR\bresource\x1aR\n" +
	"\rResourceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.Pmaster.ResourceInfoR\x05value:\x028\x01\"6\n" +
	"\fResourceInfo\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"2\n" +
	"\x03All\x12+\n" +
	"\aversion\x18\xfa\x01 \x03(\v2\x10.Pmaster.VersionR\aversion\"{\n" +
	"\aVersion\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12 \n" +
	"\vapplication\x18\x02 \x01(\tR\vapplication\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\rR\bresource\x12\x16\n" +
	"\x06master\x18\x04 \x01(\rR\x06masterB-Z+example.com/brave-revival/src/proto/pmasterb\x06proto3"

var (
	file_pmaster_proto_rawDescOnce sync.Once
	file_pmaster_proto_rawDescData []byte
)

func file_pmaster_proto_rawDescGZIP() []byte {
	file_pmaster_proto_rawDescOnce.Do(func() {
		file_pmaster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pmaster_proto_rawDesc), len(file_pmaster_proto_rawDesc)))
	})
	return file_pmaster_proto_rawDescData
}

var file_pmaster_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pmaster_proto_goTypes = []any{
	(*Resources)(nil),    // 0: Pmaster.Resources
	(*ResourceInfo)(nil), // 1: Pmaster.ResourceInfo
	(*All)(nil),          // 2: Pmaster.All
	(*Version)(nil),      // 3: Pmaster.Version
	nil,                  // 4: Pmaster.Resources.ResourceEntry
}
var file_pmaster_proto_depIdxs = []int32{
	4, // 0: Pmaster.Resources.resource:type_name -> Pmaster.Resources.ResourceEntry
	3, // 1: Pmaster.All.version:type_name -> Pmaster.Version
	1, // 2: Pmaster.Resources.ResourceEntry.value:type_name -> Pmaster.ResourceInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pmaster_proto_init() }
func file_pmaster_proto_init() {
	if File_pmaster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pmaster_proto_rawDesc), len(file_pmaster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pmaster_proto_goTypes,
		DependencyIndexes: file_pmaster_proto_depIdxs,
		MessageInfos:      file_pmaster_proto_msgTypes,
	}.Build()
	File_pmaster_proto = out.File
	file_pmaster_proto_goTypes = nil
	file_pmaster_proto_depIdxs = nil
}
